package de

// Generated from GermanCompoundTokenizer.addException + ExtendedGermanWordSplitter.extendedList.

// compoundTokenizerExtendedParts ports ExtendedGermanWordSplitter.extendedList additions.
var compoundTokenizerExtendedParts = []string{
	"influencer",
	"katheterisierung",
	"rücklass",
	"abdichtung",
	"laptop",
	"verschattung",
	"paradeiser",
	"einreichung",
	"bestatter",
	"divergenz",
	"schrumpf",
	"degustation",
	"schaft",
	"abstreifer",
	"aufputz",
	"glühwürmchen",
	"aufwertung",
	"einhausung",
	"lackier",
	"zarge",
	"pluralisierung",
	"schanzen",
	"abscheide",
	"rangier",
	"temporal",
	"kartonage",
	"kartonagen",
	"rebellion",
	"binokular",
	"umverlegung",
	"umhausung",
	"überholung",
	"chloroplasten",
	"nachrangigkeit",
	"spital",
	"turnus",
	"teilnehmenden",
	"pensionisten",
	"graduierten",
	"beladung",
	"controller",
	"resilienz",
	"mitführ",
	"trauma",
	"abtau",
	"normung",
	"mikroskopie",
	"bitumen",
	"erfolglosigkeit",
	"pneumatik",
	"anlasser",
	"allozierung",
	"alphabetisierung",
	"aktuator",
	"akademisierung",
	"allergiker",
	"queer",
	"filament",
	"querung",
	"curling",
	"opioid",
	"booster",
	"schmuse",
	"thrombozyten",
	"dysfunktion",
	"storchen",
	"nasch",
	"esperanto",
	"passivierung",
	"radikalisierung",
	"erleuchtung",
	"verwalter",
	"verbiss",
	"ausleih",
	"rutsch",
	"kufen",
	"entferner",
	"debitoren",
	"terrakotta",
	"graffiti",
	"auffahr",
	"anmutung",
	"kritzel",
	"salami",
	"eukalyptus",
	"kreativ",
	"hochvolt",
	"trading",
	"extraktion",
	"verstetigung",
	"diagonal",
	"margen",
	"synonym",
	"aufbringung",
	"robustheit",
	"nachuntersuchung",
	"erstkommunion",
	"hauptstadt",
	"neustart",
	"polarisierung",
	"vollstreckbarkeit",
	"vollziehung",
	"kasko",
	"blitzableiter",
	"abschattungen",
	"kuscheltier",
	"gastro",
	"hortensien",
}

// compoundTokenizerExceptions: surface (lower) -> fixed split parts (lower).
// Applied before greedy DP split (Java WordSplitter exceptions).
var compoundTokenizerExceptions = map[string][]string{
	"sportshorts": {"sport", "shorts"},
	"absolventen": {"absolventen"},
	"acetat": {"acetat"},
	"alkoholabstinenz": {"alkohol", "abstinenz"},
	"androgen": {"androgen"},
	"auberginen": {"auberginen"},
	"auckland": {"auckland"},
	"boston": {"boston"},
	"brandenburg": {"brandenburg"},
	"broadcast": {"broadcast"},
	"buchsbaum": {"buchsbaum"},
	"chiemsee": {"chiemsee"},
	"coffein": {"coffein"},
	"drohnen": {"drohnen"},
	"eiben": {"eiben"},
	"eingroschen": {"eingroschen"},
	"einkomponenten": {"einkomponenten"},
	"elster": {"elster"},
	"engineering": {"engineering"},
	"factoring": {"factoring"},
	"flexodruck": {"flexo", "druck"},
	"graviton": {"graviton"},
	"göttinnen": {"göttinnen"},
	"hallesche": {"hallesche"},
	"hinspiel": {"hinspiel"},
	"homogen": {"homogen"},
	"kolleggen": {"kolleggen"},
	"karstadt": {"karstadt"},
	"kartier": {"kartier"},
	"kaukasus": {"kaukasus"},
	"knoblauch": {"knoblauch"},
	"kollagen": {"kollagen"},
	"kommerz": {"kommerz"},
	"mentoring": {"mentoring"},
	"monarchen": {"monarchen"},
	"oligarchen": {"oligarchen"},
	"optimal": {"optimal"},
	"saunieren": {"saunieren"},
	"schiessen": {"schiessen"},
	"spielgeleier": {"spielgeleier"},
	"halleschen": {"halleschen"},
	"reinigungstab": {"reinigungs", "tab"},
	"reinigungstabs": {"reinigungs", "tabs"},
	"tauschwerte": {"tausch", "werte"},
	"tauschwertes": {"tausch", "wertes"},
	"kinderspielen": {"kinder", "spielen"},
	"buchhaltungstrick": {"buchhaltungs", "trick"},
	"buchhaltungstricks": {"buchhaltungs", "tricks"},
	"haushaltstrick": {"haushalts", "trick"},
	"haushaltstricks": {"haushalts", "tricks"},
	"verkaufstrick": {"verkaufs", "trick"},
	"verkaufstricks": {"verkaufs", "tricks"},
	"ablenkungstrick": {"ablenkungs", "trick"},
	"ablenkungstricks": {"ablenkungs", "tricks"},
	"manipulationstrick": {"manipulations", "trick"},
	"manipulationstricks": {"manipulations", "tricks"},
	"erziehungstrick": {"erziehungs", "trick"},
	"erziehungstricks": {"erziehungs", "tricks"},
	"messetage": {"messe", "tage"},
	"messetagen": {"messe", "tagen"},
	"karamelligen": {"karamelligen"},
	"häkelnadel": {"häkel", "nadel"},
	"häkelnadeln": {"häkel", "nadeln"},
	"freiberg": {"freiberg"},
	"abtestat": {"abtestat"},
	"abtestaten": {"abtestaten"},
	"freibergs": {"freibergs"},
	"kreuzberg": {"kreuzberg"},
	"kreuzbergs": {"kreuzbergs"},
	"digitalisierung": {"digitalisierung"},
	"abtrocknung": {"abtrocknung"},
	"erlösung": {"erlösung"},
	"feuerung": {"feuerung"},
	"aktivierung": {"aktivierung"},
	"protokollierung": {"protokollierung"},
	"budgetierung": {"budgetierung"},
	"faltung": {"faltung"},
	"anhäufung": {"anhäufung"},
	"aufkohlung": {"aufkohlung"},
	"festigung": {"festigung"},
	"allerheiligen": {"allerheiligen"},
	"druckerpressen": {"drucker", "pressen"},
	"habitat": {"habitat"},
	"augarten": {"augarten"},
	"auszeit": {"auszeit"},
	"bewegtbild": {"bewegt", "bild"},
	"bigband": {"bigband"},
	"bisexuelle": {"bisexuelle"},
	"bisexuellen": {"bisexuellen"},
	"bunsenbrenner": {"bunsenbrenner"},
	"carbon": {"carbon"},
	"carsharing": {"carsharing"},
	"castor": {"castor"},
	"catering": {"catering"},
	"cholesterin": {"cholesterin"},
	"damast": {"damast"},
	"dispositiv": {"dispositiv"},
	"emittent": {"emittent"},
	"emittenten": {"emittenten"},
	"express": {"express"},
	"fairness": {"fairness"},
	"fiberglas": {"fiberglas"},
	"globus": {"globus"},
	"illustration": {"illustration"},
	"muttertag": {"muttertag"},
	"muttertags": {"muttertags"},
	"patriarchen": {"patriarchen"},
	"phosgen": {"phosgen"},
	"vatertag": {"vatertag"},
	"vatertags": {"vatertags"},
	"vaterland": {"vaterland"},
	"vaterlands": {"vaterlands"},
	"wehrmacht": {"wehrmacht"},
	"wehrmachts": {"wehrmachts"},
	"maskerade": {"maskerade"},
}

