package uk

import (
	"strings"
	"testing"

	"github.com/lucasew/lang/internal/languagetool/org/languagetool"
	"github.com/stretchr/testify/require"
)

func TestDiscoverUkrainianMultiwords(t *testing.T) {
	p := DiscoverUkrainianMultiwords()
	if p == "" {
		t.Skip("official uk/multiwords.txt not discoverable (submodule missing?)")
	}
	require.Contains(t, p, "multiwords.txt")
	// FromPath must load official tab-separated file without invent glue.
	c, err := NewUkrainianMultiwordChunkerFromPath(p)
	require.NoError(t, err)
	require.NotNil(t, c)
}

func TestLoadUkrainianMultiwords(t *testing.T) {
	lines := LoadUkrainianMultiwordsLines()
	require.NotEmpty(t, lines)
	// all tab form (Java MultiWordChunker2)
	for _, ln := range lines {
		require.Contains(t, ln, "\t", ln)
		parts := strings.Split(ln, "\t")
		require.Len(t, parts, 2, ln)
		require.NotEmpty(t, parts[0])
		require.NotEmpty(t, parts[1])
	}
	// known official phrases (phrase\ttag)
	joined := strings.Join(lines, "\n")
	require.Contains(t, joined, "а капела\tadv")
	require.Contains(t, joined, "для годиться\tadv")
	require.Contains(t, joined, "на жаль\tinsert")
	require.Contains(t, joined, "як правило\tinsert")
	// commented-out official lines must not appear as active entries
	for _, ln := range lines {
		require.NotEqual(t, "#як правило\tadv", ln)
	}
}

func TestParseUkrainianMultiwordReader_TabOnly(t *testing.T) {
	// Official format: tab-separated. Glued invent lines must be rejected.
	ok, err := parseUkrainianMultiwordReader(strings.NewReader("а капела\tadv\nна жаль\tinsert\n"))
	require.NoError(t, err)
	require.Equal(t, []string{"а капела\tadv", "на жаль\tinsert"}, ok)

	_, err = parseUkrainianMultiwordReader(strings.NewReader("а капелаadv\n"))
	require.Error(t, err, "glued POS invent path is not Java MultiWordChunker2")

	_, err = parseUkrainianMultiwordReader(strings.NewReader("no-tag-here\n"))
	require.Error(t, err)

	// Comments and blanks skipped like Java loadWords
	ok, err = parseUkrainianMultiwordReader(strings.NewReader("# comment\n\nfoo bar\ttag\n#skipped\txx\n"))
	require.NoError(t, err)
	require.Equal(t, []string{"foo bar\ttag"}, ok)
}

func TestDefaultChunker_DisambiguatePhrase(t *testing.T) {
	c := NewDefaultUkrainianMultiwordChunker()
	require.NotNil(t, c)
	// "на жаль" → <insert> on both tokens (Java MultiWordChunker2 wrap)
	sent := atrSent2("на", "жаль")
	out := c.Disambiguate(sent)
	require.NotNil(t, out)
	toks := out.GetTokensWithoutWhitespace()
	require.GreaterOrEqual(t, len(toks), 3) // SENT_START + 2
	require.True(t, hasPOSSub(toks[1], "<insert>"), readingsDump(toks[1]))
	require.True(t, hasPOSSub(toks[2], "<insert>"), readingsDump(toks[2]))
}

func TestUkrainianMultiwordChunker_OfficialPhrases(t *testing.T) {
	c := NewDefaultUkrainianMultiwordChunker()
	require.NotNil(t, c)

	type phraseCase struct {
		parts   []string
		wantTag string
		label   string
	}
	positives := []phraseCase{
		{[]string{"на", "жаль"}, "<insert>", "на жаль"},
		{[]string{"а", "капела"}, "<adv>", "а капела"},
		{[]string{"для", "годиться"}, "<adv>", "для годиться"},
		{[]string{"як", "правило"}, "<insert>", "як правило"},
		// allowFirstCapitalized=true: first-cap of lowercase official entry
		{[]string{"На", "жаль"}, "<insert>", "На жаль first-cap"},
		{[]string{"А", "капела"}, "<adv>", "А капела first-cap"},
		{[]string{"Для", "годиться"}, "<adv>", "Для годиться first-cap"},
	}
	for _, tc := range positives {
		out := c.Disambiguate(mwSent(tc.parts...))
		got := contentPOSTagsMW(out)
		require.Len(t, got, len(tc.parts), "%s content token count", tc.label)
		for i := range tc.parts {
			require.True(t, hasExactPOS(got[i], tc.wantTag),
				"%s token[%d] want %q in %v", tc.label, i, tc.wantTag, got[i])
		}
	}

	// Negatives: non-listed multi-token sequences must not receive multiword wrap tags
	negatives := []struct {
		parts []string
		label string
	}{
		{[]string{"zxqwv", "plmnb"}, "random non-listed"},
		// not an official multiword phrase
		{[]string{"на", "стіл"}, "на стіл non-listed"},
		{[]string{"для", "радости"}, "для радости non-listed"},
		// all-upper of lower entry is NOT generated by MultiWordChunker2 (only first-cap)
		{[]string{"НА", "ЖАЛЬ"}, "НА ЖАЛЬ all-upper denied"},
		// titlecase second token denied (second token exact match only)
		{[]string{"На", "Жаль"}, "На Жаль second-cap denied"},
	}
	for _, tc := range negatives {
		out := c.Disambiguate(mwSent(tc.parts...))
		got := contentPOSTagsMW(out)
		for i, tags := range got {
			require.False(t, hasAnyAnglePOS(tags),
				"%s token[%d] should have no multiword wrap tags, got %v", tc.label, i, tags)
		}
	}
}

func TestUkrainianMultiwordChunker_ProcessCachedAndHybridWire(t *testing.T) {
	a := UkrainianMultiwordChunkerDefault()
	b := UkrainianMultiwordChunkerDefault()
	require.NotNil(t, a)
	require.Same(t, a, b, "process-cached singleton")

	d := NewUkrainianHybridDisambiguator()
	require.NotNil(t, d.Chunker)
	// default hybrid Chunker must load official multiwords (not empty)
	lines := LoadUkrainianMultiwordsLines()
	require.NotEmpty(t, lines)

	// Wired hybrid still tags official phrases via Chunker stage
	out := d.Disambiguate(mwSent("на", "жаль"))
	got := contentPOSTagsMW(out)
	require.Len(t, got, 2)
	require.True(t, hasExactPOS(got[0], "<insert>") || hasPOSSub(out.GetTokensWithoutWhitespace()[1], "<insert>"),
		"wired hybrid на: %v", got[0])
	require.True(t, hasExactPOS(got[1], "<insert>") || hasPOSSub(out.GetTokensWithoutWhitespace()[2], "<insert>"),
		"wired hybrid жаль: %v", got[1])
}

func TestNewUkrainianHybrid_LoadsMultiwords(t *testing.T) {
	d := NewUkrainianHybridDisambiguator()
	require.NotNil(t, d.Chunker)
	lines := LoadUkrainianMultiwordsLines()
	require.NotEmpty(t, lines)
}

func hasPOSSub(atr *languagetool.AnalyzedTokenReadings, sub string) bool {
	if atr == nil {
		return false
	}
	for _, r := range atr.GetReadings() {
		if r != nil && r.GetPOSTag() != nil && strings.Contains(*r.GetPOSTag(), sub) {
			return true
		}
	}
	return false
}

func readingsDump(atr *languagetool.AnalyzedTokenReadings) string {
	if atr == nil {
		return ""
	}
	var b []string
	for _, r := range atr.GetReadings() {
		if r != nil && r.GetPOSTag() != nil {
			b = append(b, *r.GetPOSTag())
		}
	}
	return strings.Join(b, ",")
}

func atrSent2(a, b string) *languagetool.AnalyzedSentence {
	return mwSent(a, b)
}

// mwSent builds SENT_START + content tokens (no whitespace between) for MultiWordChunker2.
func mwSent(parts ...string) *languagetool.AnalyzedSentence {
	st := languagetool.SentenceStartTagName
	toks := []*languagetool.AnalyzedTokenReadings{
		languagetool.NewAnalyzedTokenReadings(languagetool.NewAnalyzedToken("", &st, nil)),
	}
	for _, p := range parts {
		pos := "x"
		lem := p
		toks = append(toks, languagetool.NewAnalyzedTokenReadings(
			languagetool.NewAnalyzedToken(p, &pos, &lem)))
	}
	return languagetool.NewAnalyzedSentence(toks)
}

func contentPOSTagsMW(out *languagetool.AnalyzedSentence) [][]string {
	var all [][]string
	for i, tr := range out.GetTokens() {
		if i == 0 || tr.IsWhitespace() {
			continue
		}
		var tags []string
		for _, r := range tr.GetReadings() {
			if r != nil && r.GetPOSTag() != nil {
				tags = append(tags, *r.GetPOSTag())
			}
		}
		all = append(all, tags)
	}
	return all
}

func hasExactPOS(tags []string, want string) bool {
	for _, p := range tags {
		if p == want {
			return true
		}
	}
	return false
}

func hasAnyAnglePOS(tags []string) bool {
	for _, p := range tags {
		if strings.Contains(p, "<") {
			return true
		}
	}
	return false
}
