package uk

// Twin of languagetool-language-modules/uk/src/test/java/org/languagetool/tokenizers/uk/UkrainianSRXSentenceTokenizerTest.java
// Java: TestTools.testSplit — join parts, tokenize, expect same parts (incl. trailing spaces).
// stokenizer = new SRXSentenceTokenizer(Ukrainian.DEFAULT_VARIANT)  // short code "uk"
import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// testSplitUK mirrors Java private testSplit → TestTools.testSplit(sentences, stokenizer).
func testSplitUK(t *testing.T, parts ...string) {
	t.Helper()
	tok := NewUkrainianSRXSentenceTokenizer()
	joined := strings.Join(parts, "")
	got := tok.Tokenize(joined)
	require.Equal(t, parts, got, "joined=%q", joined)
}

// Port of UkrainianSRXSentenceTokenizerTest.testTokenize — all active cases, exact equality.
func TestUkrainianSRXSentenceTokenizer_Tokenize(t *testing.T) {
	testSplitUK(t, "Це просте речення.")
	testSplitUK(t, "Вони приїхали в Париж. ", "Але там їм геть не сподобалося.")
	testSplitUK(t, "Панк-рок — напрям у рок-музиці, що виник у середині 1970-х рр. у США і Великобританії.")
	testSplitUK(t, "Разом із втечами, вже у XV ст. почастішали збройні виступи селян.")
	testSplitUK(t, "На початок 1994 р. державний борг України становив 4,8 млрд. дол. США")
	testSplitUK(t, "4,8 млрд. дол. США. ", "Але наступного року...")
	testSplitUK(t, "Київ, вул. Сагайдачного, буд. 43, кв. 4.")
	testSplitUK(t, "на вул.\n  Сагайдачного.")
	testSplitUK(t, "Є.Бакуліна")
	testSplitUK(t, "Є.В.Бакуліна")
	testSplitUK(t, "Засідав І. П. Єрмолюк.")
	testSplitUK(t, "І. П. Єрмолюк скликав нараду.")
	testSplitUK(t, "Наша зустріч з А. Марчуком і Г. В. Тріскою відбулася в грудні минулого року.")
	testSplitUK(t, "Наша зустріч з А.Марчуком і М.В.Хвилею відбулася в грудні минулого року.")
	testSplitUK(t, "Комендант преподобний С.\u00A0Мокітімі")
	testSplitUK(t, "Комендант преподобний С.\u00A0С.\u00A0Мокітімі 1.")
	testSplitUK(t, "Комендант преподобний С.\u00A0С. Мокітімі 2.")
	testSplitUK(t, "Склад: акад. Вернадський, проф. Харченко, доц. Семеняк.")
	testSplitUK(t, "для др.  Харченко.")
	testSplitUK(t, "и др. ", "Потім вони пішли.")
	testSplitUK(t, "Ів. Франко.")
	testSplitUK(t, "Алисов Н. В. , Хореев Б. С.")
	testSplitUK(t, "і Г.-К. Андерсена")
	testSplitUK(t, " — К. : Наук. думка, 1990.")
	testSplitUK(t, "Маркс К. «Показова держава»")
	testSplitUK(t, "Приходь! — буркнула йому.")
	testSplitUK(t, "«Приходь!» — буркнула йому.")
	testSplitUK(t, "М. Л. Гончарука, I. О. Денисюка")
	testSplitUK(t, "I. I. Дорошенко")
	testSplitUK(t, "елементів множини A. Отже, нехай")
	testSplitUK(t, "Опергрупа приїхала в с. Лісове.")
	testSplitUK(t, "Біля с. Березичі.")
	testSplitUK(t, "300 р. до н. е.")
	testSplitUK(t, "З 300 р. до н.е., і по цей день.")
	testSplitUK(t, "Пролісок (рос. пролесок) — маленька квітка.")
	testSplitUK(t, "Квітка Цісик (англ. Kvitka Cisyk також Kacey Cisyk від ініціалів К.С.); 4 квітня 1953р., Квінз, Нью-Йорк — 29 березня 1998 р., Мангеттен, Нью-Йорк) — американська співачка українського походження.")
	testSplitUK(t, "До Інституту ім. Глієра під'їжджає чорне авто.")
	testSplitUK(t, "До Інституту ім. акад. Вернадського.")
	testSplitUK(t, "До вулиці гетьмана Скоропадського під'їжджає чорне авто.")
	testSplitUK(t, "До табору «Артек».")
	testSplitUK(t, "Спільні пральні й т. д. й т. п. ", "Перемогли!")
	testSplitUK(t, "в Хоролі з п. Кушніренком договорилися")
	testSplitUK(t, "і п. 10 від 23.1.33 р.")
	testSplitUK(t, "і т. п. ", "10 від 23.1.33 р.")
	testSplitUK(t, "і т.п. ", "10 від 23.1.33 р.")
	testSplitUK(t, "див. стор. 24.")
	testSplitUK(t, "Від англ.\n  File.")
	testSplitUK(t, "Від фр.  \nparachute.")
	testSplitUK(t, "фільму\nС. Ейзенштейна")
	testSplitUK(t, "Від р. Дніпро.")
	testSplitUK(t, "В 1941 р. Конрад Цузе побудував.")
	testSplitUK(t, "Наприкінці 1254 р. Данило почав")
	testSplitUK(t, "У травні 1949 р. Грушківський район")
	testSplitUK(t, "У травні 1949 р. \nГрушківський район")
	testSplitUK(t, "Упродовж 2011–2014 р. Швейцарія надасть")
	testSplitUK(t, "15 вересня 1995 р. Україною було підписано")
	testSplitUK(t, "Але закінчилося аж у січні 2013 р. ", "Як бачимо")
	testSplitUK(t, "інкримінують ч. 1 ст. 11")
	testSplitUK(t, "В цих світлих просторих апартаментах...  м’які крісла, килими, дорогі статуетки")
	testSplitUK(t, "А та — навперейми... «давайте мені!»")
	testSplitUK(t, "слугував ...    «витяг з протоколу зустрічі")
	testSplitUK(t, "на... Луганському")
	testSplitUK(t, "(вони самі це визнали. - Ред.)")
	testSplitUK(t, "Всього 33 тис. 356 особи")
	testSplitUK(t, "Всього 33 тис. (за словами прораба)")
	testSplitUK(t, "з яких приблизно   1,2 тис. – чоловіки.")
	testSplitUK(t, "У с. Вижва")
	testSplitUK(t, "Книжка (с. 200)")
	testSplitUK(t, "позначені: «с. Вижва»")
	testSplitUK(t, "в м.Києві")
	testSplitUK(t, "Микола Васюк (с. Корнієнки, Полтавська обл.)")
	testSplitUK(t, "U.S. Marine")
	testSplitUK(t, "B.B. King")
	testSplitUK(t, "Церква Св. Духа і церква св. Духа")
	testSplitUK(t, "Валерій (міліціонер-пародист.  –  Авт.) стане пародистом.")
	testSplitUK(t, "пише ред. Бойків")
	testSplitUK(t, "Сьогодні (у четвер.  - Ред.), вранці.")
	testSplitUK(t, " ([27]див. Тиждень № 9, 2008)")
	testSplitUK(t, "і «Р. Б. К.»")
	testSplitUK(t, "У. Т: ")
	testSplitUK(t, "Іван Ч. (1914 р. н.)")
	testSplitUK(t, "альбом “Сніжність” (2006 р.) – разом із Юрієм")
	testSplitUK(t, "СК “Слон” (2008 р.) ", "У минулому харків’янка")
	testSplitUK(t, "рис. 14, Мал. 5; Арт. 88-99")
	testSplitUK(t, "нар. 1945 р.")
	testSplitUK(t, "Гліба (1995 р. нар.)")
	testSplitUK(t, "нар. бл. 1720 р.")
	testSplitUK(t, "(нар. у серпні 1904)")
	testSplitUK(t, "977 — нар. Кріс Мартін")
	testSplitUK(t, "Ради нар. депутатів")
	testSplitUK(t, "нар. арт. ", "України")
	testSplitUK(t, "біля нар. ", "У таких умовах")
	testSplitUK(t, "поч. 1945 - кін. 1946 р.")
	testSplitUK(t, "кін. ХІ — поч. ХІІІ ст.")
}

// Port of UkrainianSRXSentenceTokenizerTest.testWebEntities — all active cases, exact equality.
func TestUkrainianSRXSentenceTokenizer_WebEntities(t *testing.T) {
	testSplitUK(t, "Паляниця.Інфо")
	testSplitUK(t, "Жмеринка.City")
}

// Port of UkrainianSRXSentenceTokenizerTest.testTokenizeWithSplit — all active cases, exact equality.
func TestUkrainianSRXSentenceTokenizer_TokenizeWithSplit(t *testing.T) {
	testSplitUK(t, "Всього 33 тис.", "А можей й більше")
	testSplitUK(t, "Їх було 7,5 млн.", "В кожного була сорочка.")
	testSplitUK(t, "Довжиною 30 с. ", "Поїхали.")
	testSplitUK(t, "Швидкістю 30 м/с. ", "Поїхали.")
	testSplitUK(t, "до 0,64 г/куб. дм. ", "Найчистіша")
	testSplitUK(t, "Останні 100 м. ", "І тут все пропало.")
	testSplitUK(t, "всього 20 м. ", "Почалося")
	testSplitUK(t, "Корисна площа 67 тис. кв.  м. ", "У 1954 році над Держпромом...")
	testSplitUK(t, "На 0,6°C. ", "Проте ми все маємо.")
	testSplitUK(t, "На 0,6°С. ", "Проте ми все маємо.")
	testSplitUK(t, "На 0,6 °C. ", "Проте ми все маємо.")
	testSplitUK(t, "На 0,6 °С. ", "Проте ми все маємо.")
	testSplitUK(t, "Приїхав у США. ", "Проте на другий рік.")
	testSplitUK(t, "Маємо страшне диво з див. ", "І кращого варіанту немає.")
	testSplitUK(t, "Взяти бодай XIII—XIX ст.", "Раніше п’єса була домінантою.")
	testSplitUK(t, "...Після перемоги у кваліфікації у стрільбі")
	testSplitUK(t, "...Somebody else")
	testSplitUK(t, "доволі стабільну стрільбу. ", "...Після перемоги у кваліфікації у стрільбі")
	testSplitUK(t, "доволі стабільну стрільбу\n ", "...Після перемоги у кваліфікації у стрільбі")
	testSplitUK(t, "Лі Куан Ю. ", "Наприклад")
	testSplitUK(t, "король Георг V. ", "А нині")
	testSplitUK(t, "цар Петро I. ", "Він ухвалив")
	testSplitUK(t, "група В. ", "Усі віруси")
}

// Port of UkrainianSRXSentenceTokenizerTest.testTokenizeWithSpecialChars — all active cases, exact equality.
func TestUkrainianSRXSentenceTokenizer_TokenizeWithSpecialChars(t *testing.T) {
	testSplitUK(t, "– С.\u202f5-7.")
	testSplitUK(t, "товариш С.\u202fОхримович.")
	testSplitUK(t, "З особливим обуренням сприймав С.\u202f Шелухин легітимізацію")
	testSplitUK(t, "відбув у тюрмах.\u202f", "Нещодавно письменник")
	testSplitUK(t, "закрито бібліотеку української літератури.\u202f ", "Раніше відділ боротьби з екстремізмом...")
}
