package de

// Twin of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java
import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/lucasew/lang/internal/languagetool/org/languagetool/tools"
)

var _ = require.Equal
var _ = tools.Unimplemented

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testGetCategoriesCausingError
func TestAgreementRule_GetCategoriesCausingError(t *testing.T) {
	// contains assertTrue
	// contains assertThat
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testCompoundMatch
func TestAgreementRule_CompoundMatch(t *testing.T) {
	// contains assertFalse
	// contains assertThat
	_ = "Es gibt ein Sprichwort, dem zufolge der tägliche Genuss einer Mandel dem Gedächtnis förderlich sei." // assertGood
	_ = "War das Eifersucht?" // assertGood
	_ = "Sie gehörte einst zu den besten Afrikas." // assertGood
	_ = "Dieses Bild stammt von einem lange Zeit unbekannten Maler." // assertGood
	_ = "Das Staatsoberhaupt ist der Verfassung zufolge der König." // assertGood
	_ = "Der Ende der 1960er Jahre umgestaltete Garten ist schön." // assertGood
	_ = "Der Ende der achtziger Jahre umgestaltete Garten hat unter anderem ungefähr 70 verschiedene Sorten von Rosen und Volieren für exotische Vögel." // assertGood
	_ = "Als Vorboten des Discounthandels sind die Ende der 50er Jahre in der Bundesrepublik Deutschland wiederauflebenden Erscheinungsformen des Beziehungs-, Betriebs- und Belegschaftshandels anzusehen." // assertGood
	_ = "Die Anfang des letzten Monats umgestaltete Veranda ist schön." // assertGood
	_ = "Der Mitte 2001 umgestaltete Garten ist schön." // assertGood
	_ = "Das ist die Original Mail" // assertBad
	_ = "Das ist die neue Original Mail" // assertBad
	_ = "Das ist die ganz neue Original Mail" // assertBad
	_ = "Doch dieser kleine Magnesium Anteil ist entscheidend." // assertBad
	_ = "Doch dieser sehr kleine Magnesium Anteil ist entscheidend." // assertBad
	_ = "Die Standard Priorität ist 5." // assertBad
	_ = "Die derzeitige Standard Priorität ist 5." // assertBad
	_ = "Ein neuer LanguageTool Account" // assertBad
	_ = "Danke für deine Account Daten" // assertBad
	_ = "Mit seinem Konkurrent Alistair Müller" // assertBad
	_ = "Wir gehen ins Fitness Studio" // assertBad
	_ = "Wir gehen durchs Fitness Studio" // assertBad
	_ = "Was für eine schöner Sonnenuntergang!" // assertBad
	_ = "Es ist ein sehr interessantes kostenloses Slot Spiel." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testDetNounRule
func TestAgreementRule_DetNounRule(t *testing.T) {
	_ = "Bis zur Anfang Juni geplanten Eröffnung gebe es noch einiges zu tun." // assertGood
	_ = "Der fließend Französisch sprechende Präsident dankt stilvoll ab." // assertGood
	_ = "Inwiefern soll denn das romantische Hoffnungen begründen?" // assertGood
	_ = "Spricht der fließend Französisch?" // assertGood
	_ = "Spricht dieser fließend Französisch, muss er viel Geld verdienen." // assertGood
	_ = "Der letzte Woche beschlossene Etat ist unwirksam." // assertGood
	_ = "Die Einen sagen dies, die Anderen das." // assertGood
	_ = "So ist es in den USA." // assertGood
	_ = "Das ist der Tisch." // assertGood
	_ = "Das ist das Haus." // assertGood
	_ = "Das ist die Frau." // assertGood
	_ = "Das ist das Auto der Frau." // assertGood
	_ = "Das gehört dem Mann." // assertGood
	_ = "Das Auto des Mannes." // assertGood
	_ = "Das interessiert den Mann." // assertGood
	_ = "Das interessiert die Männer." // assertGood
	_ = "Das Auto von einem Mann." // assertGood
	_ = "Das Auto eines Mannes." // assertGood
	_ = "Des großen Mannes." // assertGood
	_ = "Und nach der Nummerierung kommt die Überschrift." // assertGood
	_ = "Sie wiesen dieselben Verzierungen auf." // assertGood
	_ = "Die erwähnte Konferenz ist am Samstag." // assertGood
	_ = "Sie erreichten 5 Prozent." // assertGood
	_ = "Sie erreichten mehrere Prozent Zustimmung." // assertGood
	_ = "Die Bestandteile, aus denen Schwefel besteht." // assertGood
	_ = "Ich tat für ihn, was kein anderer Autor für ihn tat." // assertGood
	_ = "Ich tat für ihn, was keine andere Autorin für ihn tat." // assertGood
	_ = "Ich tat für ihn, was kein anderes Kind für ihn tat." // assertGood
	_ = "Ich tat für ihn, was dieser andere Autor für ihn tat." // assertGood
	_ = "Ich tat für ihn, was diese andere Autorin für ihn tat." // assertGood
	_ = "Ich tat für ihn, was dieses andere Kind für ihn tat." // assertGood
	_ = "Ich tat für ihn, was jener andere Autor für ihn tat." // assertGood
	_ = "Ich tat für ihn, was jeder andere Autor für ihn tat." // assertGood
	_ = "Ich tat für ihn, was jede andere Autorin für ihn tat." // assertGood
	_ = "Ich tat für ihn, was jedes andere Kind für ihn tat." // assertGood
	_ = "Klebe ein Preisschild auf jedes einzelne Produkt." // assertGood
	_ = "Eine Stadt, in der zurzeit eine rege Bautätigkeit herrscht." // assertGood
	_ = "... wo es zu einer regen Bautätigkeit kam." // assertGood
	_ = "Mancher ausscheidende Politiker hinterlässt eine Lücke." // assertGood
	_ = "Kern einer jeden Tragödie ist es, .." // assertGood
	_ = "Das wenige Sekunden alte Baby schrie laut." // assertGood
	_ = "Meistens sind das Frauen, die damit besser umgehen können." // assertGood
	_ = "Er fragte, ob das Spaß macht." // assertGood
	_ = "Das viele Geld wird ihr helfen." // assertGood
	_ = "Er verspricht jedem hohe Gewinne." // assertGood
	_ = "Er versprach allen Renditen jenseits von 15 Prozent." // assertGood
	_ = "Sind das Eier aus Bodenhaltung?" // assertGood
	_ = "Sie sind sehr gute Kameraden, auf die Verlass ist." // assertGood
	_ = "Dir macht doch irgendwas Sorgen." // assertGood
	_ = "Sie fragte, ob das wirklich Kunst sei." // assertGood
	_ = "Für ihn ist das Alltag." // assertGood
	_ = "Für die Religiösen ist das Blasphemie und führt zu Aufständen." // assertGood
	_ = "Das Orange ist schön." // assertGood
	_ = "Dieses rötliche Orange gefällt mir am besten." // assertGood
	_ = "Das ist ein super Tipp." // assertGood
	_ = "Er nahm allen Mut zusammen und ging los." // assertGood
	_ = "Sie kann einem Angst einjagen." // assertGood
	_ = "Damit sollten zum einen neue Energien gefördert werden, zum anderen der Sozialbereich." // assertGood
	_ = "Nichts ist mit dieser einen Nacht zu vergleichen." // assertGood
	_ = "dann muss Schule dem Rechnung tragen." // assertGood
	_ = "Das Dach von meinem Auto." // assertGood
	_ = "Das Dach von meinen Autos." // assertGood
	_ = "Da stellt sich die Frage: Ist das Science-Fiction oder moderne Mobilität?" // assertGood
	_ = "Er hat einen Post veröffentlicht." // assertGood
	_ = "Eine lückenlose Aufklärung sämtlicher physiologischer Gehirnprozesse" // assertGood
	_ = "Sie fragte verwirrt: „Ist das Zucker?“" // assertGood
	_ = "Er versuchte sich vorzustellen, was sein Klient für ein Mensch sei." // assertGood
	_ = "Sie legen ein Teilstück jenes Weges zurück, den die Tausenden Juden 1945 auf sich nehmen mussten." // assertGood
	_ = "Aber das ignorierte Herr Grey bewusst." // assertGood
	_ = "Aber das ignorierte Herr Müller bewusst." // assertGood
	_ = "Ich werde mich zurücknehmen und mich frischen Ideen zuwenden." // assertGood
	_ = "Das, plus ein eigener Firmenwagen." // assertGood
	_ = "Dieses leise Summen stört nicht." // assertGood
	_ = "Die Tiroler Küche" // assertGood
	_ = "Was ist denn das für ein ungewöhnlicher Name?" // assertGood
	_ = "Besonders reizen mich Fahrräder." // assertGood
	_ = "Und nur, weil mich psychische Erkrankungen aus der Bahn werfen" // assertGood
	_ = "Das kostet dich Zinsen." // assertGood
	_ = "Sie hatten keine Chance gegen das kleinere Preußen." // assertGood
	_ = "Den 2019er Wert hatten sie geschätzt." // assertGood
	_ = "Andere formale Systeme, deren Semantiken jeweils..." // assertGood
	_ = "Gesetz zur Änderung des Kündigungsrechts und anderer arbeitsrechtlicher Vorschriften" // assertGood
	_ = "Die dauerhafte Abgrenzung des später Niedersachsen genannten Gebietes von Westfalen begann im 12. Jahrhundert." // assertGood
	_ = "Lieber jemanden, der einem Tipps gibt." // assertGood
	_ = "Jainas ist sogar der Genuss jeglicher tierischer Nahrungsmittel strengstens untersagt." // assertGood
	_ = "Es sind jegliche tierische Nahrungsmittel untersagt." // assertGood
	_ = "Das reicht bis weit ins heutige Hessen." // assertGood
	_ = "Die Customer Journey." // assertGood
	_ = "Für dich gehört Radfahren zum perfekten Urlaub dazu?" // assertGood
	_ = ":D:D Leute, bitte!" // assertGood
	_ = "Es genügt, wenn ein Mann sein eigenes Geschäft versteht und sich nicht in das anderer Leute einmischt." // assertGood
	_ = "Ich habe das einige Male versucht." // assertGood
	_ = "Und keine Märchen erzählst, die dem anderen Hoffnungen machen können." // assertGood
	_ = "Um diese Körpergrößen zu erreichen, war das Wachstum der Vertreter der Gattung Dinornis offenbar gegenüber dem anderer Moa-Gattungen beschleunigt" // assertGood
	_ = "Der Schädel entspricht in den Proportionen dem anderer Vulpes-Arten, besitzt aber sehr große Paukenhöhlen, ein typisches Merkmal von Wüstenbewohnern." // assertGood
	_ = "Deuterium lässt sich aufgrund des großen Massenunterschieds leichter anreichern als die Isotope der anderer Elemente wie z. B. Uran." // assertGood
	_ = "Unklar ist, ob er zwischen der Atemseele des Menschen und der anderer Lebewesen unterschied." // assertGood
	_ = "Die Liechtensteiner Grenze ist im Verhältnis zu der anderer Länder kurz, da Liechtenstein ein eher kleines Land ist." // assertGood
	_ = "Picassos Kunstwerke werden häufiger gestohlen als die anderer Künstler." // assertGood
	_ = "Schreibe einen Artikel über deine Erfahrungen im Ausland oder die anderer Leute in deinem Land." // assertGood
	_ = "Die Bevölkerungen Chinas und Indiens lassen die anderer Staaten als Zwerge erscheinen." // assertGood
	_ = "Der eine mag Obst, ein anderer Gemüse, wieder ein anderer mag Fisch; allen kann man es nicht recht machen." // assertGood
	_ = "Mittels eines Bootloaders und zugehöriger Software kann nach jedem Anstecken des Adapters eine andere Firmware-Varianten geladen werden" // assertGood
	_ = "Wenn sie eine andere Größe benötigen, teilen uns ihre speziellen Wünsche mit und wir unterbreiten ihnen ein Angebot über Preis und Lieferung." // assertGood
	_ = "Dabei wird in einer Vakuumkammer eine einige Mikrometer dicke CVD-Diamantschicht auf den Substraten abgeschieden." // assertGood
	_ = "1916 versuchte Gilbert Newton Lewis, die chemische Bindung durch Wechselwirkung der Elektronen eines Atoms mit einem anderen Atomen zu erklären." // assertGood
	_ = "Vom einen Ende der Straße zum anderen." // assertGood
	_ = "Er war müde vom vielen Laufen." // assertGood
	_ = "Sind das echte Diamanten?" // assertGood
	_ = "Es wurde eine Verordnung erlassen, der zufolge jeder Haushalt Energie einsparen muss." // assertGood
	_ = "Im Jahr 1922 verlieh ihm König George V. den erblichen Titel eines Baronet. " // assertGood
	_ = "... der zu dieser Zeit aber ohnehin schon allen Einfluss verloren hatte." // assertGood
	_ = "Ein Geschenk, das Maßstäbe setzt" // assertGood
	_ = "Einwohnerzahl stieg um das Zweieinhalbfache" // assertGood
	_ = "Die Müllers aus Hamburg." // assertGood
	_ = "Es ist noch unklar, wann und für wen Impfungen vorgenommen werden könnten." // assertGood
	_ = "Macht dir das Hoffnung?" // assertGood
	_ = "Mich fasziniert Macht." // assertGood
	_ = "Der solchen Einsätzen gegenüber kritische Hitler wurde nicht im Voraus informiert." // assertGood
	_ = "Gregor wählte die Gestalt des wenige Jahrzehnte zuvor verstorbenen Klostergründers." // assertGood
	_ = "Wir machen das Januar." // assertGood
	_ = "Wir teilen das Morgen mit." // assertGood
	_ = "Wir präsentierten das vorletzten Sonnabend." // assertGood
	_ = "Ich release das Vormittags." // assertGood
	_ = "Sie aktualisieren das Montags." // assertGood
	_ = "Kannst du das Mittags machen?" // assertGood
	_ = "Können Sie das nächsten Monat erledigen?" // assertGood
	_ = "Können Sie das auch nächsten Monat erledigen?" // assertGood
	_ = "War das Absicht?" // assertGood
	_ = "Alles Große und Edle ist einfacher Art." // assertGood
	_ = "Dieser vereint Sprachprüfung, Thesaurus und Umformuliertool in einem." // assertGood
	_ = "Das Dach meines Autos." // assertGood
	_ = "Das Dach meiner Autos." // assertGood
	_ = "Das Dach meines großen Autos." // assertGood
	_ = "Das Dach meiner großen Autos." // assertGood
	_ = "Dann schlug er so kräftig wie er konnte mit den Schwingen." // assertGood
	_ = "Also wenn wir Glück haben, ..." // assertGood
	_ = "Wenn wir Pech haben, ..." // assertGood
	_ = "Ledorn öffnete eines der an ihr vorhandenen Fächer." // assertGood
	_ = "Auf der einen Seite endlose Dünen" // assertGood
	_ = "In seinem Maul hielt er einen blutigen Fleischklumpen." // assertGood
	_ = "Gleichzeitig dachte er intensiv an Nebelschwaden, aus denen Wolken ja bestanden." // assertGood
	_ = "Warum stellte der bloß immer wieder dieselben Fragen?" // assertGood
	_ = "Bei der Hinreise." // assertGood
	_ = "Schließlich tauchten in einem Waldstück unter ihnen Schienen auf." // assertGood
	_ = "Das Wahlrecht, das Frauen damals zugesprochen bekamen." // assertGood
	_ = "Es war Karl, dessen Leiche Donnerstag gefunden wurde." // assertGood
	_ = "Erst recht ich Arbeiter." // assertGood
	_ = "Erst recht wir Arbeiter." // assertGood
	_ = "Erst recht wir fleißigen Arbeiter." // assertGood
	_ = "Dann lud er Freunde ein." // assertGood
	_ = "Dann lud sie Freunde ein." // assertGood
	_ = "Aller Kommunikation liegt dies zugrunde." // assertGood
	_ = "Pragmatisch wählt man solche Formeln als Axiome." // assertGood
	_ = "Der eine Polizist rief dem anderen zu..." // assertGood
	_ = "Der eine große Polizist rief dem anderen zu..." // assertGood
	_ = "Das eine Kind rief dem anderen zu..." // assertGood
	_ = "Er wollte seine Interessen wahrnehmen." // assertGood
	_ = "Es birgt für mich ein zu hohes juristisches Risiko." // assertGood
	_ = "... wo Krieg den Unschuldigen Leid und Tod bringt." // assertGood
	_ = "Der Abschuss eines Papageien." // assertGood
	_ = "Die Beibehaltung des Art. 1 ist geplant." // assertGood
	_ = "Die Verschiebung des bisherigen Art. 1 ist geplant." // assertGood
	_ = "In diesem Fall hatte das Vorteile." // assertGood
	_ = "So hat das Konsequenzen." // assertGood
	_ = "Ein für viele wichtiges Anliegen." // assertGood
	_ = "Das weckte bei vielen ungute Erinnerungen." // assertGood
	_ = "Etwas, das einem Angst macht." // assertGood
	_ = "Einem geschenkten Gaul schaut man nicht ins Maul." // assertGood
	_ = "Das erfordert Können." // assertGood
	_ = "Ist das Kunst?" // assertGood
	_ = "Ist das Kunst oder Abfall?" // assertGood
	_ = "Die Zeitdauer, während der Wissen nützlich bleibt, wird kürzer." // assertGood
	_ = "Es sollte nicht viele solcher Bilder geben" // assertGood
	_ = "In den 80er Jahren." // assertGood
	_ = "Hast du etwas das Carina machen kann?" // assertGood
	_ = "Ein Artikel in den Ruhr Nachrichten." // assertGood
	_ = "Ich wollte nur allen Hallo sagen." // assertGood
	_ = "Ich habe deshalb allen Freund*innen Bescheid gegeben." // assertGood
	_ = "Ich habe deshalb allen Freund_innen Bescheid gegeben." // assertGood
	_ = "Ich habe deshalb allen Freund:innen Bescheid gegeben." // assertGood
	_ = "Das betrifft auch eure Werkstudent:innen-Zielgruppe." // assertGood
	_ = "Das betrifft auch eure Werkstudent:innenzielgruppe." // assertGood
	_ = "Das betrifft auch eure Jurist:innenausbildung." // assertGood
	_ = "Sein*e Mitarbeiter*in ist davon auch betroffen." // assertGood
	_ = "Jede*r Mitarbeiter*in ist davon betroffen." // assertGood
	_ = "Alle Professor*innen" // assertGood
	_ = "Gleichzeitig wünscht sich Ihr frostresistenter Mitbewohner einige Grad weniger im eigenen Zimmer?" // assertGood
	_ = "Ein Trainer, der zum einen Fußballspiele sehr gut lesen und analysieren kann" // assertGood
	_ = "Eine Massengrenze, bis zu der Lithium nachgewiesen werden kann." // assertGood
	_ = "Bei uns im Krankenhaus betrifft das Operationssäle." // assertGood
	_ = "Macht dir das Freude?" // assertGood
	_ = "Das macht jedem Angst." // assertGood
	_ = "Dann macht das Sinn." // assertGood
	_ = "Das sind beides Lichtschalter." // assertGood
	_ = "Spielst du vielleicht auf das Bordell neben unserm Hotel an?" // assertGood
	_ = "Spielst du vielleicht auf das Bordell neben unsrem Hotel an?" // assertGood
	_ = "Dieses ungeahnt prophetische Wort" // assertGood
	_ = "Das bestätigte Regierungssprecher Steffen Hebestreit am Freitag" // assertGood
	_ = "Es kann gut sein, dass bei sowas Probleme erkannt werden." // assertGood
	_ = "Das Recht, das Frauen eingeräumt wird." // assertGood
	_ = "Der Mann, in dem quadratische Fische schwammen." // assertGood
	_ = "Der Mann, durch den quadratische Fische schwammen." // assertGood
	_ = "Gutenberg, der quadratische Mann." // assertGood
	_ = "Die größte Stuttgarter Grünanlage ist der Friedhof." // assertGood
	_ = "Die meisten Lebensmittel enthalten das." // assertGood
	_ = "Die wärmsten Monate sind August und September, die kältesten Januar und Februar." // assertGood
	_ = "Das Münchener Fest." // assertGood
	_ = "Das Münchner Fest." // assertGood
	_ = "Die Planung des Münchener Festes." // assertGood
	_ = "Das Berliner Wetter." // assertGood
	_ = "Den Berliner Arbeitern ist das egal." // assertGood
	_ = "Das Haus des Berliner Arbeiters." // assertGood
	_ = "Es gehört dem Berliner Arbeiter." // assertGood
	_ = "Das Stuttgarter Auto." // assertGood
	_ = "Das Bielefelder Radio." // assertGood
	_ = "Das Gütersloher Radio." // assertGood
	_ = "Das wirklich Wichtige kommt jetzt erst." // assertGood
	_ = "Besonders wenn wir Wermut oder Absinth trinken." // assertGood
	_ = "Ich wünsche dir alles Gute." // assertGood
	_ = "Es ist nicht bekannt, mit welchem Alter Kinder diese Fähigkeit erlernen." // assertGood
	_ = "Dieser ist nun in den Ortungsbereich des einen Roboters gefahren." // assertGood
	_ = "Wenn dies großen Erfolg hat, werden wir es weiter fördern." // assertGood
	_ = "Alles Gute!" // assertGood
	_ = "Das bedeutet nichts Gutes." // assertGood
	_ = "Die Ereignisse dieses einen Jahres waren sehr schlimm." // assertGood
	_ = "Er musste einen Hochwasser führenden Fluss nach dem anderen überqueren." // assertGood
	_ = "Darf ich Ihren Füller für ein paar Minuten ausleihen?" // assertGood
	_ = "Bringen Sie diesen Gepäckaufkleber an Ihrem Gepäck an." // assertGood
	_ = "Extras, die den Wert Ihres Autos erhöhen." // assertGood
	_ = "Er hat einen 34-jährigen Sohn." // assertGood
	_ = "Die Polizei erwischte die Diebin, weil diese Ausweis und Visitenkarte hinterließ." // assertGood
	_ = "Dieses Versäumnis soll vertuscht worden sein - es wurde Anzeige erstattet." // assertGood
	_ = "Die Firmen - nicht nur die ausländischen, auch die katalanischen - treibt diese Frage um." // assertGood
	_ = "Stell dich dem Leben lächelnd!" // assertGood
	_ = "Die Messe wird auf das vor der Stadt liegende Ausstellungsgelände verlegt." // assertGood
	_ = "Sie sind ein den Frieden liebendes Volk." // assertGood
	_ = "Zum Teil sind das Krebsvorstufen." // assertGood
	_ = "Er sagt, dass das Rache bedeutet." // assertGood
	_ = "Wenn das Kühe sind, bin ich ein Elefant." // assertGood
	_ = "Karl sagte, dass sie niemandem Bescheid gegeben habe." // assertGood
	_ = "Es blieb nur dieser eine Satz." // assertGood
	_ = "Oder ist das Mathematikern vorbehalten?" // assertGood
	_ = "Wenn hier einer Fragen stellt, dann ich." // assertGood
	_ = "Wenn einer Katzen mag, dann meine Schwester." // assertGood
	_ = "Ergibt das Sinn?" // assertGood
	_ = "Sie ist über die Maßen schön." // assertGood
	_ = "Ich vertraue ganz auf die Meinen." // assertGood
	_ = "Was nützt einem Gesundheit, wenn man sonst ein Idiot ist?" // assertGood
	_ = "Auch das hatte sein Gutes." // assertGood
	_ = "Auch wenn es sein Gutes hatte, war es doch traurig." // assertGood
	_ = "Er wollte doch nur jemandem Gutes tun." // assertGood
	_ = "und das erst Jahrhunderte spätere Auftauchen der Legende" // assertGood
	_ = "Texas und New Mexico, beides spanische Kolonien, sind..." // assertGood
	_ = "Texas und New Mexico - beides spanische Kolonien - sind..." // assertGood
	_ = "Texas und New Mexico – beides spanische Kolonien – sind..." // assertGood
	_ = "Weitere Brunnen sind insbesondere der Wittelsbacher und der Vater-Rhein-Brunnen auf der Museumsinsel, beides Werke von Adolf von Hildebrand." // assertGood
	_ = "Für manche ist das Anlass genug, darüber nicht weiter zu diskutieren." // assertGood
	_ = "Vielleicht schreckt das Frauen ab." // assertGood
	_ = "Unser Hund vergräbt seine Knochen im Garten." // assertGood
	_ = "Ob das Mehrwert bringt?" // assertGood
	_ = "Warum das Sinn macht?" // assertGood
	_ = "Das hängt davon ab, ob die Deutsch sprechen" // assertGood
	_ = "Die meisten Coaches wissen nichts." // assertGood
	_ = "Die Präsent AG." // assertGood
	_ = "In New York war er der Titelheld in Richard III. und spielte den Mark Anton in Julius Cäsar." // assertGood
	_ = "Vielen Dank fürs Bescheid geben." // assertGood
	_ = "Welche Display Ads?" // assertGood
	_ = "Das letzte Mal war das Anfang der 90er Jahre des vergangenen Jahrhunderts" // assertGood
	_ = "Der vom Rat der Justizminister gefasste Beschluss zur Aufnahme von Vertriebenen..." // assertGood
	_ = "Der letzte Woche vom Rat der Justizminister gefasste Beschluss zur Aufnahme von Vertriebenen..." // assertGood
	_ = "Was war sie nur für eine dumme Person!" // assertGood
	_ = "Was war ich für ein Idiot!" // assertGood
	_ = "Was für ein Idiot!" // assertGood
	_ = "Was für eine blöde Kuh!" // assertGood
	_ = "Was ist sie nur für eine blöde Kuh!" // assertGood
	_ = "Wie viele Paar Stiefel brauche ich eigentlich?" // assertGood
	_ = "Dieses versuchten Mathematiker 400 Jahre lang vergeblich zu beweisen." // assertGood
	_ = "Gemälde informieren uns über das Leben von den vergangenen Jahrhunderten…" // assertGood
	_ = "Die Partei, die bei den vorangegangenen Wahlen noch seine Politik unterstützt hatte." // assertGood
	_ = "Bei Zunahme der aufgelösten Mineralstoffe, bei denen..." // assertGood
	_ = "Je mehr Muskelspindeln in einem Muskel vorhanden sind, desto feiner können die mit diesem verbundenen Bewegungen abgestimmt werden." // assertGood
	_ = "Diese datentechnischen Operationen werden durch Computerprogramme ausgelöst, d. h. über entsprechende, in diesen enthaltene Befehle (als Teil eines implementierten Algorithmus') vorgegeben." // assertGood
	_ = "Aus diesen resultierten Konflikte wie der Bauernkrieg und der Pfälzische Erbfolgekrieg." // assertGood
	_ = "Die Staatshandlungen einer Mikronation und von dieser herausgegebene Ausweise, Urkunden und Dokumente gelten im Rechtsverkehr als unwirksam" // assertGood
	_ = "Auf der Hohen See und auf den mit dieser verbundenen Gewässern gelten die internationalen Kollisionsverhütungsregeln." // assertGood
	_ = "Art. 11 Abs. 2 GGV setzt dem bestimmte Arten der außergemeinschaftlichen Zugänglichmachung gleich" // assertGood
	_ = "Grundsätzlich sind die Heilungschancen von Männern mit Brustkrebs nicht schlechter als die betroffener Frauen." // assertGood
	_ = "In diesem Viertel bin ich aufgewachsen." // assertGood
	_ = "Im November wurde auf dem Gelände der Wettbewerb ausgetragen." // assertGood
	_ = "Er ist Eigentümer des gleichnamigen Schemas und stellt dieses interessierten Domänen zur Verfügung." // assertGood
	_ = "Dort finden sie viele Informationen rund um die Themen Schwangerschaft, Geburt, Stillen, Babys und Kinder." // assertGood
	_ = "Die Galerie zu den Bildern findet sich hier." // assertGood
	_ = "Ganz im Gegensatz zu den Blättern des Brombeerstrauches." // assertGood
	_ = "Er erzählte von den Leuten und den Dingen, die er auf seiner Reise gesehen hatte." // assertGood
	_ = "Diese Partnerschaft wurde 1989 nach dem Massaker auf dem Platz des Himmlischen Friedens eingefroren." // assertGood
	_ = "Die Feuergefahr hingegen war für für die Londoner Teil des Alltags." // assertGood
	_ = "Was ist, wenn ein Projekt bei den Berliner Type Awards mit einem Diplom ausgezeichnet wird?" // assertGood
	_ = "Was ist mit dem Liechtensteiner Kulturleben los?" // assertGood
	_ = "Das ist der Mann den Präsident Xi Jinping verurteilte." // assertGood
	_ = "Wie viele Kolleg/-innen haben sie?" // assertGood
	_ = "Die Ideen der neuen Kolleg/-innen sind gut!" // assertGood
	_ = "Das erlaubt Forschern, neue Versuche durchzuführen." // assertGood
	_ = "Dies ermöglicht Forschern, neue Versuche durchzuführen." // assertGood
	_ = "Je länger zugewartet wird, desto schwieriger dürfte es werden, die Jungtiere von den Elterntieren zu unterscheiden." // assertGood
	_ = "Er schrieb ein von 1237 bis 1358 reichendes Geschichtswerk, dessen Schwerpunkt auf den Ereignissen in der Lombardei liegt." // assertGood
	_ = "Private Veranstaltungen waren, darauf hat die Strandhaus Norderstedt GmbH im Rahmen rechtlicher Klärungen selbst bestanden, nicht Bestandteil dieser Verträge." // assertGood
	_ = "Die Klientel der Partei." // assertGood
	_ = "Wenn die Gott zugeschriebenen Eigenschaften stimmen, dann..." // assertGood
	_ = "Dieses Grünkern genannte Getreide ist aber nicht backbar." // assertGood
	_ = "Außerdem unterstützt mich Herr Müller beim abheften" // assertGood
	_ = "Außerdem unterstützt mich Frau Müller beim abheften" // assertGood
	_ = "Ich gebe dir ein kleines Kaninchen." // assertGood
	_ = "Ich gebe dir das kleine Kaninchen." // assertGood
	_ = "Die Top 3 der Umfrage" // assertGood
	_ = "Dein Vorschlag befindet sich unter meinen Top 5." // assertGood
	_ = "Unter diesen rief das großen Unmut hervor." // assertGood
	_ = "Bei mir löste das Panik aus." // assertGood
	_ = "Sie können das machen in dem sie die CAD.pdf öffnen." // assertGood
	_ = "Ich mache eine Ausbildung zur Junior Digital Marketing Managerin." // assertGood
	_ = "Dann wird das Konsequenzen haben." // assertGood
	_ = "Dann hat das Konsequenzen." // assertGood
	_ = "Sollte das Konsequenzen nach sich ziehen?" // assertGood
	_ = "Der Echo Show von Amazon" // assertGood
	_ = "Die BVG kommen immer zu spät." // assertGood
	_ = "In der Frühe der Nacht." // assertGood
	_ = "Der TV Steinfurt." // assertGood
	_ = "Ein ID 3 von Volkswagen." // assertGood
	_ = "Der ID.3 von Volkswagen." // assertGood
	_ = "Der ID3 von Volkswagen." // assertGood
	_ = "Das bedeutet Krieg!" // assertGood
	_ = "Im Tun zu sein verhindert Prokrastination." // assertGood
	_ = "Das ist doch lächerlich, was ist denn das für eine Klinik?" // assertGood
	_ = "Was ist denn das für ein Typ?" // assertGood
	_ = "Hier geht's zur Customer Journey." // assertGood
	_ = "Das führt zur Verbesserung der gesamten Customer Journey." // assertGood
	_ = "Meint er das wirklich Ernst?" // assertGood
	_ = "Meinen Sie das Ernst?" // assertGood
	_ = "Die können sich in unserer Hall of Fame verewigen." // assertGood
	_ = "Die können sich in unserer neuen Hall of Fame verewigen." // assertGood
	_ = "Auch, wenn das weite Teile der Bevölkerung betrifft." // assertGood
	_ = "Hat das Einfluss auf Ihr Trinkverhalten?" // assertGood
	_ = "Ihr wisst aber schon, dass das Blödsinn ist." // assertGood
	_ = "Aber mein Wissen über die Antike ist ausbaufähig." // assertGood
	_ = "Sie werden merken, dass das echte Nutzer sind." // assertGood
	_ = "Dieses neue Mac OS trug den Codenamen Rhapsody." // assertGood
	_ = "Das Mac OS is besser als Windows." // assertGood
	_ = "Damit steht das Porsche Museum wie kaum ein anderes Museum für Lebendigkeit und Abwechslung." // assertGood
	_ = "Weitere Krankenhäuser sind dass Eastern Shore Memorial Hospital, IWK Health Centre, Nova Scotia Hospital und das Queen Elizabeth II Health Sciences Centre." // assertGood
	_ = "Ich bin von Natur aus ein sehr neugieriger Mensch." // assertGood
	_ = "Ich bin auf der Suche nach einer Junior Developerin." // assertGood
	_ = "War das Eifersucht?" // assertGood
	_ = "Waren das schwierige Entscheidungen?" // assertGood
	_ = "Soll das Demokratie sein?" // assertGood
	_ = "Hat das Spaß gemacht?" // assertGood
	_ = "Soll das Sinn stiften?" // assertGood
	_ = "Soll das Freude machen?" // assertGood
	_ = "Die Trial ist ausgelaufen." // assertGood
	_ = "Ein geworbener Neukunde interagiert zusätzlich mit dem Unternehmen." // assertGood
	_ = "Ich weiß, dass jeder LanguageTool benutzen sollte." // assertGood
	_ = "1992 übernahm die damalige Ernst Klett Schulbuchverlag GmbH, Stuttgart, den reprivatisierten Verlag Haack Gotha" // assertGood
	_ = "Überlegst du dir einen ID.3 zu leasen?" // assertGood
	_ = "Der Deutsch Langhaar ist ein mittelgroßer Jagdhund" // assertGood
	_ = "Eine Lösung die Spaß macht" // assertGood
	_ = "Mir machte das Spaß." // assertGood
	_ = "Wir möchten nicht, dass irgendjemand Fragen stellt." // assertGood
	_ = "Die Multiple Sklerose hat 1000 Gesichter." // assertGood
	_ = "Na ja, einige nennen das Freundschaft plus, aber das machen wir besser nicht." // assertGood
	_ = "Vogue, eigentlich als B-Seite der letzten Like A Prayer-Auskopplung Keep It Together gedacht, wurde kurzfristig als eigenständige Single herausgebracht" // assertGood
	_ = "..., die laufend Gewaltsituationen ausgeliefert sind" // assertGood
	_ = "Dann folgte die Festnahme der dringend Tatverdächtigen." // assertGood
	_ = "Von der ersten Spielminute an machten die Münsteraner Druck und ..." // assertGood
	_ = "Wenn diese Prognose bestätigt wird, wird empfohlen, dass Unternehmen die gefährliche Güter benötigen, die Transporte am Montag und Dienstag machen." // assertGood
	_ = "Ich habe meine Projektidee (die riesiges finanzielles Potenzial hat) an einen Unternehmenspräsidenten geschickt." // assertGood
	_ = "Als weitere Rechtsquelle gelten gelegentlich noch immer der Londoner Court of Appeal und das britische House of Lords." // assertGood
	_ = "Die Evangelische Kirche befindet sich in der Bad Sodener Altstadt direkt neben dem Quellenpark." // assertGood
	_ = "Der volle Windows 10 Treibersupport" // assertGood
	_ = "Zugleich stärkt es die renommierte Berliner Biodiversitätsforschung." // assertGood
	_ = "Der Windows 10 Treibersupport" // assertGood
	_ = "Kennt irgendwer Tipps wie Kopfhörer länger halten?" // assertGood
	_ = "George Lucas 1999 über seine sechsteilige Star Wars Saga." // assertGood
	_ = "… und von denen mehrere Gegenstand staatsanwaltlicher Ermittlungen waren." // assertGood
	_ = "Natürlich ist das Quatsch!" // assertGood
	_ = "Die Xi Jinping Ära ist …" // assertGood
	_ = "Die letzte unter Windows 98 lauffähige Version ist 5.1." // assertGood
	_ = "Das veranlasste Bürgermeister Adam, selbst tätig zu werden, denn er wollte es nicht zulassen, dass in seiner Stadt Notleidende ohne Hilfe dastehen." // assertGood
	_ = "Die südlichste Düsseldorfer Rheinbrücke ist die Fleher Brücke, eine Schrägseilbrücke mit dem höchsten Brückenpylon in Deutschland und einer Vielzahl von fächerförmig angeordneten Seilen." // assertGood
	_ = "Ein zeitweise wahres Stakkato an einschlägigen Patenten, das Benz & Cie." // assertGood
	_ = "Wem Rugby nicht sehr geläufig ist, dem wird auch das Six Nations nicht viel sagen." // assertGood
	_ = "Eine Boeing 767 der Air China stürzt beim Landeanflug in ein Waldgebiet." // assertGood
	_ = "Wir sind immer offen für Mitarbeiter die Teil eines der traditionellsten Malerbetriebe auf dem Platz Zürich werden möchten." // assertGood
	_ = "Gelingt das mit Erregern rechtzeitig, könnte das Infektionen sogar oft verhindern." // assertGood
	_ = "In der aktuellen Niedrigzinsphase bedeutet das sehr geringe Zinsen, die aber deutlich ansteigen können." // assertGood
	_ = "Es gibt viele Stock Screener." // assertGood
	_ = "Wir gehen zur Learning Academy." // assertGood
	_ = "Es ist ein stiller Bank Run." // assertGood
	_ = "Whirlpool Badewanne der europäische Marke SPAtec Modell Infinity." // assertGood
	_ = "1944 eroberte diese weite Teile von Südosteuropa." // assertGood
	_ = "Auch die Monopolstellung des staatlichen All India Radio, das in 24 Sprachen sendet" // assertGood
	_ = "Das schwedischen Entwicklerstudio MachineGames hat uns vor drei Jahren mit Wolfenstein: The New Order positiv überrascht." // assertGood
	_ = "In einem normalen Joint habe es etwa ein halbes Gramm Hanf." // assertGood
	_ = "den leidenschaftlichen Lobpreis der texanischen Gateway Church aus" // assertGood
	_ = "die gegnerischen Shooting Guards" // assertGood
	_ = "Bald läppert sich das zu richtigem Geld zusammen." // assertGood
	_ = "Die Weimarer Parks laden ja förmlich ein zu Fotos im öffentlichen Raum." // assertGood
	_ = "Es is schwierig für mich, diese zu Sätzen zu verbinden." // assertGood
	_ = "Es kam zum einen zu technischen Problemen, zum anderen wurde es unübersichtlich." // assertGood
	_ = "Das Spiel wird durch den zu neuer Größe gewachsenen Torwart dominiert." // assertGood
	_ = "Dort findet sich schlicht und einfach alles & das zu sagenhafter Hafenkulisse." // assertGood
	_ = "Man darf gespannt sein, wen Müller für diese Aufgabe gewinnt." // assertGood
	_ = "Das Vereinslokal in welchem Zusammenkünfte stattfinden." // assertGood
	_ = "Er lässt niemanden zu Wort kommen." // assertGood
	_ = "Es war eine alles in allem spannende Geschichte." // assertGood
	_ = "Eine mehrere hundert Meter lange Startbahn." // assertGood
	_ = "Wir müssen jetzt um ein vielfaches höhere Preise zahlen." // assertGood
	_ = "Und eine von manchem geforderte Übergewinnsteuer." // assertGood
	_ = "Sie hat niemandem wirkliches Leid zugefügt." // assertGood
	_ = "Die Organe eines gerade Verstorbenen" // assertGood
	_ = "Da wusste keiner Bescheid bezüglich dieser Sache." // assertGood
	_ = "Es braucht keiner Bescheid wissen." // assertGood
	_ = "Das sind auch beides staatliche Organe." // assertGood
	_ = "Ein Haus für die weniger Glücklichen." // assertGood
	_ = "Wir können sowas Mittwoch machen." // assertGood
	_ = "Den schlechter Verdienenden geht es schlecht." // assertGood
	_ = "Mit der weit weniger bekannten Horrorkomödie begann ihre Karriere." // assertGood
	_ = "Die Adelmanns wohnen in Herford." // assertGood
	_ = "Die Idee des Werbekaufmanns kam gut an." // assertGood
	_ = "Solch harte Worte!" // assertGood
	_ = "Ich habe es an unseren amerikanischen Commercial Lawyer geschickt." // assertGood
	_ = "Dieser eine Schritt hat gedauert." // assertGood
	_ = "Es besteht durchaus die Gefahr, dass die Telekom eine solch starke monopolistische Stellung auf dem Markt hat, dass sich kaum Wettbewerb entfalten kann." // assertGood
	_ = "Wenn ein Tiger einen Menschen tötet, ist das Grausamkeit." // assertGood
	_ = "Kombinieren Sie diese zu ganzen Bewegungsprogrammen" // assertGood
	_ = "Erst später wurde Kritik hauptsächlich an den Plänen zu einem Patriot Act II laut." // assertGood
	_ = "Laut Charlie XCX selbst sind das Personen, die vielleicht eine ..." // assertGood
	_ = "Solch frivolen Gedanken wollen wir gar nicht erst nachgehen." // assertGood
	_ = "Er erwartete solch aggressives Verhalten." // assertGood
	_ = "Eine solch schöne Frau." // assertGood
	_ = "Einer solch schönen Frau." // assertGood
	_ = "Ein solch schöner Tisch." // assertGood
	_ = "Ein solch schöner neuer Tisch." // assertGood
	_ = "Eine solch begnadete Fotografin mit dabei zu haben und Tipps für die Fotosession zu bekommen, wäre schon toll." // assertGood
	_ = "Wie können wir als globale Gemeinschaft solch brennende Themen wie Klimawandel und Rezession in entwickelten Märkten in Angriff nehmen?" // assertGood
	_ = "Wir waren überrascht, von ihm solch beißende Bemerkungen über seinen besten Freund zu hören." // assertGood
	_ = "Worten, wohl gewählt, wohnt solch große Macht inne." // assertGood
	_ = "Warum gelingt es den Stuten die Hengste in solch großen Rennen zu schlagen." // assertGood
	_ = "Eine solch gute Beratung kann natürlich nicht kostenlos sein, daher lassen Sie mich bitte wissen welche Kosten für die PKV und BU-Beratung auf mich zukommen werden." // assertGood
	_ = "Ein solch großer Ausbruch außerhalb des Nahen Ostens ist eine neue Entwicklung, heißt es weiter." // assertGood
	_ = "Natürlich dürfen unsere Sporteinheiten nicht fehlen, vor allem nicht bei solch gutem Essen." // assertGood
	_ = "Wie konnten Sie solch harte Songs gegen Ihre Familie schreiben?" // assertGood
	_ = "Zur Krönung auf dem schönsten Aussichtsberg in der Ferienregion Tirol West gelegen, bietet die Venet Gipfelhütte alle Annehmlichkeiten, die man sich auf solch hohem Niveau (2.212 m) wünschen kann." // assertGood
	_ = "Vor allem nicht einen, der sich ein solch hohen Ballbesitz organisierte und die Berliner nicht zur Entfaltung kommen ließ." // assertGood
	_ = "Du solltest im Winter keinen solch hohen Berg besteigen." // assertGood
	_ = "Man darf an dieser Stelle fragen, wie ein solch hoher Verlust zustande kommt, wo doch der Stuttgarter Weg aus Sparen bestand." // assertGood
	_ = "Kann der Patient eine solch lange Operation überstehen?" // assertGood
	_ = "Er kennt sich aus mit solch monumentalen Projekten." // assertGood
	_ = "Eine solch schöne hübsche Frau." // assertGood
	_ = "Bisher hat Gül einen solch offenen Affront gegen die ErdoganRegierung vermieden." // assertGood
	_ = "Umso dankbarer bin ich für Brüder, die klare Kante in theologischer Hinsicht zeigen und nachvollziehbar die Bibel auch in solch schwierigen unpopulären Themen auslegen." // assertGood
	_ = "Denn die einzelnen sehen sich einer sehr verschieden starken Macht des..." // assertBad
	_ = "Es birgt für mich ein zu hohes juristische Risiko." // assertBad
	_ = "Das betrifft auch eure Werkstudent:innen-Xihfrisfgds." // assertBad
	_ = "Das betrifft auch eure Jurist:innenxyzdfsdf." // assertBad
	_ = "Gutenberg, die Genie." // assertBad
	_ = "Wahrlich ein äußerst kritische Jury." // assertBad
	_ = "Das ist ein enorm großer Auto." // assertBad
	_ = "Ein Buch mit einem ganz ähnlichem Titel." // assertBad
	_ = "Meiner Chef raucht." // assertBad
	_ = "Er hat eine 34-jährigen Sohn." // assertBad
	_ = "Es sind die Tisch." // assertBad
	_ = "Es sind das Tisch." // assertBad
	_ = "Es sind die Haus." // assertBad
	_ = "Es sind der Haus." // assertBad
	_ = "Es sind das Frau." // assertBad
	_ = "Das Auto des Mann." // assertBad
	_ = "Das interessiert das Mann." // assertBad
	_ = "Das interessiert die Mann." // assertBad
	_ = "Das Auto ein Mannes." // assertBad
	_ = "Das Auto einem Mannes." // assertBad
	_ = "Das Auto einer Mannes." // assertBad
	_ = "Das Auto einen Mannes." // assertBad
	_ = "Die Galerie zu den Bilder findet sich hier." // assertBad
	_ = "Ganz im Gegensatz zu den Blätter des Brombeerstrauches." // assertBad
	_ = "Die erwähnt Konferenz ist am Samstag." // assertBad
	_ = "Die erwähntes Konferenz ist am Samstag." // assertBad
	_ = "Die erwähnten Konferenz ist am Samstag." // assertBad
	_ = "Die erwähnter Konferenz ist am Samstag." // assertBad
	_ = "Die erwähntem Konferenz ist am Samstag." // assertBad
	_ = "Die gemessen Werte werden in die länderspezifische Höhe über dem Meeresspiegel umgerechnet." // assertBad
	_ = "Darüber hinaus haben wir das berechtigte Interessen, diese Daten zu verarbeiten." // assertBad
	_ = "Eine Amnestie kann den Hingerichteten nicht das Leben und dem heimgesuchten Familien nicht das Glück zurückgeben." // assertBad
	_ = "Z. B. therapeutisches Klonen, um aus den gewonnen Zellen in vitro Ersatzorgane für den Patienten zu erzeugen" // assertBad
	_ = "Die Partei, die bei den vorangegangen Wahlen noch seine Politik unterstützt hatte." // assertBad
	_ = "Bei Zunahme der aufgelösten Mineralstoffen, bei denen..." // assertBad
	_ = "Durch die große Vielfalt der verschiedene Linien ist für jeden Anspruch die richtige Brille im Portfolio." // assertBad
	_ = "In diesen Viertel bin ich aufgewachsen." // assertBad
	_ = "Im November wurde auf den Gelände der Wettbewerb ausgetragen." // assertBad
	_ = "Dort finden sie Testberichte und viele Informationen rund um das Themen Schwangerschaft, Geburt, Stillen, Babys und Kinder." // assertBad
	_ = "Je länger zugewartet wird, desto schwieriger dürfte es werden, die Jungtiere von den Elterntiere zu unterscheiden." // assertBad
	_ = "Er schrieb ein von 1237 bis 1358 reichendes Geschichtswerk, dessen Schwerpunkt auf den Ereignisse in der Lombardei liegt." // assertBad
	_ = "Des großer Mannes." // assertBad
	_ = "Er erzählte von den Leute und den Dingen, die er gesehen hatte." // assertBad
	_ = "Diese Partnerschaft wurde 1989 nach den Massaker auf dem Platz des Himmlischen Friedens eingefroren." // assertBad
	_ = "Das Dach von meine Auto." // assertBad
	_ = "Das Dach von meinen Auto." // assertBad
	_ = "Das Dach mein Autos." // assertBad
	_ = "Das Dach meinem Autos." // assertBad
	_ = "Das Dach meinem großen Autos." // assertBad
	_ = "Das Dach mein großen Autos." // assertBad
	_ = "Das Klientel der Partei." // assertBad
	_ = "Der Haus ist groß" // assertBad
	_ = "Aber der Haus ist groß" // assertBad
	_ = "Ich habe einen Feder gefunden." // assertBad
	_ = "Der Zustand meiner Gehirns." // assertBad
	_ = "Lebensmittel sind da, um den menschliche Körper zu ernähren." // assertBad
	_ = "Geld ist da, um den menschliche Überleben sicherzustellen." // assertBad
	_ = "Sie hatte das kleinen Kaninchen." // assertBad
	_ = "Frau Müller hat das wichtigen Dokument gefunden." // assertBad
	_ = "Ich gebe dir ein kleine Kaninchen." // assertBad
	_ = "Ich gebe dir ein kleinen Kaninchen." // assertBad
	_ = "Ich gebe dir ein kleinem Kaninchen." // assertBad
	_ = "Ich gebe dir ein kleiner Kaninchen." // assertBad
	_ = "Ich gebe dir das kleinen Kaninchen." // assertBad
	_ = "Ich gebe dir das kleinem Kaninchen." // assertBad
	_ = "Ich gebe dir das kleiner Kaninchen." // assertBad
	_ = "Geprägt ist der Platz durch einen 142 Meter hoher Obelisken" // assertBad
	_ = "Es birgt für mich ein überraschend hohes juristische Risiko." // assertBad
	_ = "Es birgt für mich ein zu hohes juristische Risiko." // assertBad
	_ = "Hier steht Ihre Text." // assertBad
	_ = "Hier steht ihre Text." // assertBad
	_ = "Antje Last, Inhaberin des Berliner Kult Hotels Auberge, freute sich ebenfalls über die Gastronomenfamilie aus Bayern." // assertBad
	_ = "Das ist doch lächerlich, was ist denn das für ein Klinik?" // assertBad
	_ = "Ich weiß nicht mehr, was unser langweiligen Thema war." // assertBad
	_ = "Er ging ins Küche." // assertBad
	_ = "Er ging ans Luft." // assertBad
	_ = "Eine Niereninsuffizienz führt zur Störungen des Wasserhaushalts." // assertBad
	_ = "Er stieg durchs Fensters." // assertBad
	_ = "Ich habe heute ein Krankenwagen gesehen." // assertBad
	_ = "Funktioniert das Software auch mit Windows?" // assertBad
	_ = "So soll er etwa Texte des linken Literaturwissenschaftler Helmut Lethen mit besonderem Interesse gelesen haben." // assertBad
	_ = "Auf dieser Website werden allerdings keine solche Daten weiterverxxx." // assertBad
	_ = "Bei größeren Gruppen und/oder mehrere Tagen gibts einen nennenswerten Nachlass." // assertBad
	_ = "Mit der weit weniger bekannte Horrorkomödie begann ihre Karriere." // assertBad
	_ = "Die Idee des Werbekaufmann kam gut an." // assertBad
	_ = "Ich habe keine Zeit für solche kleinlichen Belangen." // assertBad
	_ = "Einen Dämonen wird er nicht aufhalten." // assertBad
	_ = "Das versetzte den Kronprinz in Schrecken." // assertBad
	_ = "Solche kleinen Anbietern nutzen dann eines der drei großen Mobilfunknetze Deutschlands." // assertBad
	_ = "..., das heißt solche natürliche Personen, welche unsere Leistungen in Anspruch nehmen, ..." // assertBad
	_ = "Der Erwerb solcher kultureller Güter ist natürlich stark an das ökonomische Kapital gebunden." // assertBad
	_ = "Wir haben das Abo beendet und des Betrag erstattet." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testZurReplacement
func TestAgreementRule_ZurReplacement(t *testing.T) {
	_ = "Hier geht's zur Sonne." // assertGood
	_ = "Hier geht's zum Schrank." // assertGood
	_ = "Niereninsuffizienz führt zu Störungen des Wasserhaushalts." // assertGood
	_ = "Das hat der fließend Englisch sprechende Mitarbeiter veranlasst." // assertGood
	_ = "Hier geht's zur Schrank." // assertBad
	_ = "Hier geht's zur Schränken." // assertBad
	_ = "Hier geht's zur Männern." // assertBad
	_ = "Hier geht's zur Portal." // assertBad
	_ = "Hier geht's zur Portalen." // assertBad
	_ = "Sie gehen zur Frauen." // assertBad
	_ = "Niereninsuffizienz führt zur Störungen des Wasserhaushalts." // assertBad
	_ = "Das Motiv wird in der Klassik auch zur Darstellungen übernommen." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testVieleWenige
func TestAgreementRule_VieleWenige(t *testing.T) {
	_ = "Zusammenschluss mehrerer dörflicher Siedlungen an einer Furt" // assertGood
	_ = "Für einige markante Szenen" // assertGood
	_ = "Für einige markante Szenen baute Hitchcock ein Schloss." // assertGood
	_ = "Haben Sie viele glückliche Erfahrungen in Ihrer Kindheit gemacht?" // assertGood
	_ = "Es gibt viele gute Sachen auf der Welt." // assertGood
	_ = "Viele englische Wörter haben lateinischen Ursprung" // assertGood
	_ = "Ein Bericht über Fruchtsaft, einige ähnliche Erzeugnisse und Fruchtnektar" // assertGood
	_ = "Der Typ, der seit einiger Zeit immer wieder hierher kommt." // assertGood
	_ = "Jede Schnittmenge abzählbar vieler offener Mengen" // assertGood
	_ = "Es kam zur Fusion der genannten und noch einiger weiterer Unternehmen." // assertGood
	_ = "Zu dieser Fragestellung gibt es viele unterschiedliche Meinungen." // assertGood
	_ = "Wir zeigen die Gründe auf, wieso noch nicht jeder solche Anschlüsse hat." // assertGood
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testDetNounRuleErrorMessages
func TestAgreementRule_DetNounRuleErrorMessages(t *testing.T) {
	tools.Unimplemented("AgreementRuleTest.testDetNounRuleErrorMessages")
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testRegression
func TestAgreementRule_Regression(t *testing.T) {
	// contains assertEquals — full values in Java twin source
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testDetAdjNounRule
func TestAgreementRule_DetAdjNounRule(t *testing.T) {
	_ = "Die Übernahme der früher selbständigen Gesellschaft" // assertGood
	_ = "Das ist, weil man oft bei anderen schreckliches Essen vorgesetzt bekommt." // assertGood
	_ = "Das ist der riesige Tisch." // assertGood
	_ = "Der riesige Tisch ist groß." // assertGood
	_ = "Die Kanten der der riesigen Tische." // assertGood
	_ = "Den riesigen Tisch mag er." // assertGood
	_ = "Es mag den riesigen Tisch." // assertGood
	_ = "Die Kante des riesigen Tisches." // assertGood
	_ = "Dem riesigen Tisch fehlt was." // assertGood
	_ = "Die riesigen Tische sind groß." // assertGood
	_ = "Der riesigen Tische wegen." // assertGood
	_ = "An der roten Ampel." // assertGood
	_ = "Dann hat das natürlich Nachteile." // assertGood
	_ = "Ihre erste Nr. 1" // assertGood
	_ = "Wir bedanken uns bei allen Teams." // assertGood
	_ = "Als Heinrich versuchte, seinen Kandidaten für den Mailänder Bischofssitz durchzusetzen, reagierte der Papst sofort." // assertGood
	_ = "Den neuen Finanzierungsweg wollen sie daher Hand in Hand mit dem Leser gehen." // assertGood
	_ = "Lieber den Spatz in der Hand..." // assertGood
	_ = "Wir wollen sein ein einzig Volk von Brüdern" // assertGood
	_ = "Eine Zeitreise durch die 68er Revolte" // assertGood
	_ = "Ich besitze ein Modell aus der 300er Reihe." // assertGood
	_ = "Aber ansonsten ist das erste Sahne" // assertGood
	_ = "...damit diese ausreichend Sauerstoff geben." // assertGood
	_ = "...als auch die jedem zukommende Freiheit." // assertGood
	_ = "...als auch die daraus jedem zukommende Freiheit." // assertGood
	_ = "Damit zeigen wir, wie bedeutungsreich manche deutsche Begriffe sein können." // assertGood
	_ = "Damit zeigen wir, wie bedeutungsreich manche deutschen Begriffe sein können." // assertGood
	_ = "2009 gab es im Rathaus daher Bestrebungen ein leichter handhabbares Logo einzuführen." // assertGood
	_ = "Das ist eine leichter handhabbare Situation." // assertGood
	_ = "Es gibt viele verschiedene Stock Screener." // assertGood
	_ = "Die Ware umräumen, um einer anderen genügend Platz zu schaffen." // assertGood
	_ = "Ich widerrufe den mit Ihnen geschlossenen Vertrag." // assertGood
	_ = "Er klagte auch gegen den ohne ihn verkündeten Sachbeschluss." // assertGood
	_ = "Dieser relativ gesehen starke Mann." // assertGood
	_ = "Diese relativ gesehen starke Frau." // assertGood
	_ = "Dieses relativ gesehen starke Auto." // assertGood
	_ = "Es kann gut sein, dass bei sowas echte Probleme erkannt werden." // assertGood
	_ = "Er hatte ein anstrengenden Tag" // assertBad
	_ = "Es sind die riesigen Tisch." // assertBad
	_ = "Als die riesigen Tischs kamen." // assertBad
	_ = "Als die riesigen Tisches kamen." // assertBad
	_ = "Der riesigen Tisch und so." // assertBad
	_ = "An der roter Ampel." // assertBad
	_ = "An der rote Ampel." // assertBad
	_ = "An der rotes Ampel." // assertBad
	_ = "An der rotem Ampel." // assertBad
	_ = "Er hatte ihn aus dem 1,4 Meter tiefem Wasser gezogen." // assertBad
	_ = "Das ist ein sehr schönes Tisch." // assertBad
	_ = "Er hatte eine sehr schweren Infektion." // assertBad
	_ = "Ein fast 5 Meter hohem Haus." // assertBad
	_ = "Ein fünf Meter hohem Haus." // assertBad
	_ = "Es wurden Karavellen eingesetzt, da diese für die flachen Gewässern geeignet waren." // assertBad
	_ = "Wir bedanken uns bei allem Teams." // assertBad
	_ = "Dabei geht es um das altbekannte Frage der Dynamiken der Eigenbildung.." // assertBad
	_ = "Den neue Finanzierungsweg wollen sie daher Hand in Hand mit dem Leser gehen." // assertBad
	_ = "Den neuen Finanzierungsweg wollen sie daher Hand in Hand mit dem Lesern gehen." // assertBad
	_ = "Ich widerrufe den mit Ihnen geschlossene Vertrag." // assertBad
	_ = "Er klagte auch gegen den ohne ihn verkündete Sachbeschluss." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testDetAdjAdjNounRule
func TestAgreementRule_DetAdjAdjNounRule(t *testing.T) {
	_ = "Das verlangt reifliche Überlegung." // assertGood
	_ = "Das bedeutet private Versicherungssummen ab 100€." // assertGood
	_ = "Das erfordert einigen Mut." // assertGood
	_ = "Die abnehmend aufwendige Gestaltung der Portale..." // assertGood
	_ = "Die strahlend roten Blumen." // assertGood
	_ = "Der weiter vorhandene Widerstand konnte sich nicht durchsetzen." // assertGood
	_ = "Das jetzige gemeinsame Ergebnis..." // assertGood
	_ = "Das früher übliche Abdecken mit elementarem Schwefel..." // assertGood
	_ = "Das einzig wirklich Schöne..." // assertGood
	_ = "Andere weniger bekannte Vorschläge waren „Konsistenter Empirismus“ oder..." // assertGood
	_ = "Werden mehrere solcher physikalischen Elemente zu einer Einheit zusammengesetzt..." // assertGood
	_ = "Aufgrund ihrer weniger guten Bonitätslage." // assertGood
	_ = "Mit ihren teilweise eigenwilligen Außenformen..." // assertGood
	_ = "Die deutsche Kommasetzung bedarf einiger technischer Ausarbeitung." // assertGood
	_ = "Die deutsche Kommasetzung bedarf einiger guter technischer Ausarbeitung." // assertGood
	_ = "Das ist eine solides strategisches Fundament" // assertBad
	_ = "Das ist eine solide strategisches Fundament" // assertBad
	_ = "Das ist ein solide strategisches Fundament" // assertBad
	_ = "Das ist ein solides strategische Fundament" // assertBad
	_ = "Das ist ein solides strategisches Fundamente" // assertBad
	_ = "Das ist ein solides strategisches Fundaments" // assertBad
	_ = "Die deutsche Kommasetzung bedarf einiger technisches Ausarbeitung." // assertBad
	_ = "Die deutsche Kommasetzung bedarf einiger guter technische Ausarbeitung." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testKonUntArtDefSub
func TestAgreementRule_KonUntArtDefSub(t *testing.T) {
	_ = "Wieso verstehst du nicht, dass das komplett verschiedene Dinge sind?" // assertGood
	_ = "Ich frage mich sehr, ob die wirklich zusätzliche Gebühren abdrücken wollen" // assertGood
	_ = "Dies wurde durchgeführt um das moderne Charakter zu betonen." // assertBad
	_ = "Nur bei Topfpflanzung ist eine regelmäßige Düngung wichtig, da die normalen Bodenbildungsprozessen nicht stattfinden." // assertBad
	_ = "Die Höhe kommt oft darauf an, ob die richtigen Leuten gut mit einen können oder nicht." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java :: AgreementRuleTest.testBugFixes
func TestAgreementRule_BugFixes(t *testing.T) {
	_ = "Das passiert nur, wenn der zu Pflegende bereit ist." // assertGood
	_ = "Peter, iss nicht meine" // assertGood
	_ = "Denn die einzelnen sehen sich einer sehr verschieden starken Macht des..." // assertBad
}
