package de

import "github.com/lucasew/lang/internal/languagetool/org/languagetool/rules/patterns"

// AgreementRuleAntiPatterns2 ports Java AgreementRuleAntiPatterns2.ANTI_PATTERNS (auto-converted).
// Coverage: 135/135; 0 omitted. Do not invent missing ones.
var AgreementRuleAntiPatterns2 = [][]*patterns.PatternToken{
	{
		patterns.Token("Eurovision"),
		patterns.Token("Song"),
		patterns.Token("Contest"),
	},
	{
		patterns.Token("Account"),
		patterns.TokenRegex("Managers?"),
	},
	{
		patterns.Token("Wohnungsbau"),
		patterns.Token("Aalen"),
	},
	{
		patterns.Token("Display"),
		patterns.TokenRegex("Ads?|Advertising"),
	},
	{
		patterns.Token("Private"),
		patterns.TokenRegex("Equitys?|Clouds?"),
	},
	{
		patterns.Token("Personal"),
		patterns.TokenRegex("Agents?|Computers?|Data|Firewalls?"),
	},
	{
		patterns.Token("Junge"),
		patterns.TokenRegex("Union|Freiheit|Welt|Europäische|Alternative|Volkspartei|Akademie"),
	},
	{
		patterns.PosRegex("ART:.+"),
		patterns.PosRegex("SUB:.+"),
		patterns.Pos("UNKNOWN"),
	},
	{
		patterns.CsToken(","),
		patterns.PosRegex("KON:UNT|ADV:INR"),
		patterns.CsToken("das"),
		patterns.PosRegex("SUB:.+"),
		patterns.PosRegex("VER:3:SIN.*"),
	},
	{
		patterns.TokenRegex("viele|etliche|wenige|einige|mehrere"),
		patterns.CsToken("solcher"),
		patterns.PosRegex("SUB:GEN:PLU:.*"),
	},
	{
		patterns.TokenRegex("[dD](ie|er)"),
		patterns.CsToken("First"),
		patterns.CsToken("Lady"),
	},
	{
		patterns.TokenRegex("[dD](ie|er)"),
		patterns.PosRegex("ADJ:.*"),
		patterns.CsToken("First"),
		patterns.CsToken("Lady"),
	},
	{
		patterns.TokenRegex("[dD](ie|er)"),
		patterns.CsToken("Super"),
		patterns.CsToken("Nintendo"),
	},
	{
		patterns.CsToken("Pizza"),
		patterns.CsToken("Hut"),
	},
	{
		patterns.CsToken(","),
		patterns.CsToken("beides"),
		patterns.NewPatternTokenBuilder().PosRegex("ADJ:NOM:PLU.+").Min(0).Build(),
		patterns.PosRegex("SUB:NOM:PLU.+"),
		patterns.Pos("PKT"),
	},
	{
		patterns.Pos("SENT_START"),
		patterns.CsToken("Beides"),
		patterns.PosRegex("SUB:NOM:PLU.+"),
	},
	{
		patterns.TokenRegex("[dD]e[rn]"),
		patterns.CsToken("Gold"),
		patterns.CsToken("Cup"),
	},
	{
		patterns.Token("das"),
		patterns.TokenRegex("viele|wenige"),
		patterns.PosRegex("SUB:.*"),
	},
	{
		patterns.Token("das"),
		patterns.PosRegex("SUB:.+"),
		patterns.NewPatternTokenBuilder().CsToken("dauern").MatchInflectedForms().Build(),
	},
	{
		patterns.TokenRegex("allen|(nieman|je(man)?)dem"),
		patterns.PosRegex("ADJ:AKK:PLU:.*"),
		patterns.PosRegex("SUB:AKK:PLU:.*"),
	},
	{
		patterns.TokenRegex("allen|(nieman|je(man)?)dem"),
		patterns.PosRegex("SUB:AKK:PLU:.*"),
	},
	{
		patterns.NewPatternTokenBuilder().PosRegex("PRP:.+|ADV:MOD").SetSkip(2).Build(),
		patterns.NewPatternTokenBuilder().Token("sein").MatchInflectedForms().Build(),
		patterns.CsToken("das"),
		patterns.PosRegex("SUB:NOM:.*"),
		patterns.PosRegex("PKT|SENT_END|KON.*"),
	},
	{
		patterns.Regex("sind|waren|wären"),
		patterns.CsToken("das"),
		patterns.PosRegex("ADJ:NOM:PLU.*"),
		patterns.PosRegex("SUB:NOM:PLU.*"),
		patterns.PosRegex("PKT|KON.*"),
	},
	{
		patterns.Regex("ist|war|wär"),
		patterns.CsToken("das"),
		patterns.PosRegex("ADJ:NOM:SIN.*"),
		patterns.PosRegex("SUB:NOM:SIN.*"),
		patterns.PosRegex("PKT|KON.*"),
	},
	{
		patterns.NewPatternTokenBuilder().Token("sein").MatchInflectedForms().Build(),
		patterns.CsToken("das"),
		patterns.CsToken("erste"),
		patterns.CsToken("Sahne"),
	},
	{
		patterns.Pos("KON:UNT"),
		patterns.CsToken("das"),
		patterns.NewPatternTokenBuilder().PosRegex("ADJ:.*").Min(0).Build(),
		patterns.PosRegex("SUB:.+"),
		patterns.NewPatternTokenBuilder().TokenRegex("bedeuten|sein").MatchInflectedForms().Build(),
	},
	{
		patterns.Pos("KON:UNT"),
		patterns.CsToken("das"),
		patterns.Pos("ADV:MOD"),
		patterns.PosRegex("SUB:.+"),
		patterns.NewPatternTokenBuilder().TokenRegex("bedeuten|sein").MatchInflectedForms().Build(),
	},
	{
		patterns.NewPatternTokenBuilder().Token("niemand").MatchInflectedForms().Build(),
		patterns.PosRegex("SUB:.+"),
	},
	{
		patterns.Token("alles"),
		patterns.CsToken("Walzer"),
	},
	{
		patterns.CsToken("der"),
		patterns.CsToken("Daus"),
	},
	{
		patterns.PosRegex("PRO:...:...:SIN:NEU.*"),
		patterns.CsToken("Orange"),
	},
	{
		patterns.PosRegex("PRO:...:...:SIN:NEU.*"),
		patterns.PosRegex("ADJ:.+"),
		patterns.CsToken("Orange"),
	},
	{
		patterns.CsToken("dem"),
		patterns.NewPatternTokenBuilder().CsToken("Achtung").SetSkip(1).Build(),
		patterns.NewPatternTokenBuilder().CsToken("schenken").MatchInflectedForms().Build(),
	},
	{
		patterns.NewPatternTokenBuilder().CsToken("schenken").MatchInflectedForms().Build(),
		patterns.CsToken("dem"),
		patterns.CsToken("Achtung"),
	},
	{
		patterns.CsToken("dem"),
		patterns.NewPatternTokenBuilder().CsToken("Rechnung").SetSkip(1).Build(),
		patterns.NewPatternTokenBuilder().CsToken("tragen").MatchInflectedForms().Build(),
	},
	{
		patterns.NewPatternTokenBuilder().CsToken("tragen").MatchInflectedForms().Build(),
		patterns.CsToken("dem"),
		patterns.CsToken("Rechnung"),
	},
	{
		patterns.CsToken("zum"),
		patterns.CsToken("einen"),
		patterns.PosRegex("(ADJ|PA[12]):.+"),
	},
	{
		patterns.Token("auf"),
		patterns.CsToken("die"),
		patterns.CsToken("Lauer"),
	},
	{
		patterns.TokenRegex("(eben)?dieser"),
		patterns.CsToken("eine"),
		patterns.Pos("SUB:NOM:SIN:MAS"),
	},
	{
		patterns.Token("das"),
		patterns.PosRegex("SUB:DAT:.+"),
		patterns.Token("vorbehalten"),
	},
	{
		patterns.NewPatternTokenBuilder().Token("wenn").SetSkip(1).Build(),
		patterns.CsToken("einer"),
		patterns.PosRegex("SUB:AKK:.+"),
		patterns.PosRegex("VER:(MOD:)?3:SIN:.+"),
		patterns.CsToken(","),
	},
	{
		patterns.TokenRegex("eine[rs]"),
		patterns.TokenRegex("jed(wed)?en"),
	},
	{
		patterns.Token("die"),
		patterns.TokenRegex("[MDS]einen"),
	},
	{
		patterns.CsToken("über"),
		patterns.CsToken("die"),
		patterns.TokenRegex("Ma(ß|ss)en"),
	},
	{
		patterns.Token("was"),
		patterns.NewPatternTokenBuilder().CsToken("nützen").MatchInflectedForms().Build(),
		patterns.CsToken("einem"),
		patterns.PosRegex("SUB:NOM:.+"),
	},
	{
		patterns.NewPatternTokenBuilder().CsToken("haben").MatchInflectedForms().Build(),
		patterns.CsToken("sein"),
		patterns.CsToken("Gutes"),
	},
	{
		patterns.CsToken("Gutes"),
		patterns.NewPatternTokenBuilder().TokenRegex("haben|tun").MatchInflectedForms().Build(),
	},
	{
		patterns.TokenRegex("(eben)?dieser"),
		patterns.CsToken("einen"),
		patterns.Pos("SUB:DAT:SIN:FEM"),
	},
	{
		patterns.CsToken("Rede"),
		patterns.CsToken("und"),
		patterns.CsToken("Antwort"),
	},
	{
		patterns.PosRegex("ABK:.+:SUB"),
	},
	{
		patterns.TokenRegex("(all|je(d|glich))en"),
		patterns.CsToken("Reiz"),
	},
	{
		patterns.TokenRegex("wieso|ob|warum|w[ae]nn"),
		patterns.Token("das"),
		patterns.TokenRegex("sinn|mehrwert"),
		patterns.TokenRegex("macht|ergibt|stiftet|bringt"),
	},
	{
		patterns.TokenRegex("hat|hätte|kann|wird|dürfte|muss|soll(te)?|könnte|müsste|würde"),
		patterns.Token("das"),
		patterns.Token("Konsequenzen"),
	},
	{
		patterns.NewPatternTokenBuilder().PosRegex("VER:.*[1-3]:.+").SetSkip(1).Build(),
		patterns.CsToken("vermehrt"),
	},
	{
		patterns.CsToken("Ruhr"),
		patterns.CsToken("Nachrichten"),
	},
	{
		patterns.CsToken("Joint"),
		patterns.TokenRegex("Ventures?|Cares?"),
	},
	{
		patterns.CsToken("Premier"),
		patterns.CsToken("League"),
	},
	{
		patterns.CsToken("Software"),
		patterns.TokenRegex("Engineers?|Developer[sn]?|(Back|Front)end"),
	},
	{
		patterns.CsToken("Mark"),
		patterns.PosRegex("EIG:.*"),
	},
	{
		patterns.CsToken("Sales"),
		patterns.TokenRegex("Agent"),
	},
	{
		patterns.CsToken("Total"),
		patterns.TokenRegex("Tankstellen?"),
	},
	{
		patterns.PosRegex("ART:.*"),
		patterns.CsToken("Bund"),
		patterns.CsToken("Naturschutz"),
	},
	{
		patterns.CsToken("Real"),
		patterns.TokenRegex("Madrid|Valladolid|Mallorca"),
	},
	{
		patterns.CsToken("Real"),
		patterns.Pos("UNKNOWN"),
	},
	{
		patterns.CsToken("Hammer"),
		patterns.TokenRegex("Stra(ß|ss)e"),
	},
	{
		patterns.CsToken("Personal"),
		patterns.TokenRegex("Trainers?"),
	},
	{
		patterns.Token("Hallo"),
		patterns.NewPatternTokenBuilder().CsToken("sagen").MatchInflectedForms().Build(),
	},
	{
		patterns.Token("die"),
		patterns.TokenRegex("Deutsch|Englisch|Spanisch|Französisch|Russisch|Polnisch|Holländisch|Niederländisch|Portugiesisch"),
		patterns.NewPatternTokenBuilder().CsToken("sprechen").MatchInflectedForms().Build(),
	},
	{
		patterns.Token("zum"),
		patterns.Token("einen"),
		patterns.PosRegex("SUB:.*"),
	},
	{
		patterns.CsToken("Fake"),
		patterns.PosRegex("News"),
	},
	{
		patterns.TokenRegex("Steinberg|Park"),
		patterns.CsToken("Apotheke"),
	},
	{
		patterns.CsToken("IT"),
		patterns.CsToken("Finanzmagazin"),
	},
	{
		patterns.CsToken("Golden"),
		patterns.CsToken("Gate"),
	},
	{
		patterns.Token("fürs"),
		patterns.Token("Bescheid"),
		patterns.TokenRegex("geben|sagen"),
	},
	{
		patterns.Token("Los"),
		patterns.TokenRegex("Angeles|Zetas"),
	},
	{
		patterns.CsToken("Auto"),
		patterns.CsToken("Zeitung"),
	},
	{
		patterns.CsToken("Mal"),
		patterns.NewPatternTokenBuilder().Token("sein").MatchInflectedForms().Build(),
		patterns.CsToken("das"),
		patterns.PosRegex("SUB:NOM:.*"),
	},
	{
		patterns.CsToken("FC"),
		patterns.CsToken("Bayern"),
	},
	{
		patterns.CsToken("Super"),
		patterns.CsToken("Mario"),
	},
	{
		patterns.TokenRegex(".+"),
		patterns.TokenRegex(".+"),
		patterns.CsToken("Toyota"),
		patterns.CsToken("Motor"),
		patterns.TokenRegex("Corp(oration)?|Company"),
	},
	{
		patterns.TokenRegex(".+"),
		patterns.TokenRegex(".+"),
		patterns.CsToken("Metropolitan"),
		patterns.TokenRegex("Police|Community|City|Books"),
	},
	{
		patterns.TokenRegex("Office|Microsoft"),
		patterns.CsToken("365"),
	},
	{
		patterns.CsToken("Prinz"),
		patterns.TokenRegex("Charles|William"),
	},
	{
		patterns.Token(":"),
		patterns.CsToken("D"),
	},
	{
		patterns.TokenRegex("ist|war(en)?|sind|wird|werden"),
		patterns.CsToken("das"),
		patterns.CsToken("reine"),
		patterns.PosRegex("SUB:NOM:.*"),
	},
	{
		patterns.CsToken("Android"),
		patterns.TokenRegex("Wear|Watch(es)?|Smartwatch(es)?|OS"),
	},
	{
		// "Bitte öffnen Sie die CAD.pdf"
		patterns.TokenRegex("\\w+"),
		patterns.NewPatternTokenBuilder().Token(".").SetIsWhiteSpaceBefore(false).Build(),
		patterns.NewPatternTokenBuilder().TokenRegex("pdf|zip|jpe?g|gif|png|rar|mp[34]|mpe?g|avi|docx?|xlsx?|pptx?|html?").SetIsWhiteSpaceBefore(false).Build(),
	},
	{
		patterns.NewPatternTokenBuilder().TokenRegex("Junior|Senior|Account").SetSkip(3).Build(),
		patterns.TokenRegex("Manager[ns]?|Managerin(nen)?|Developer(in)?"),
	},
	{
		patterns.NewPatternTokenBuilder().TokenRegex("Junior|Senior").Build(),
		patterns.Token("Software"),
		patterns.TokenRegex("Engineers?|Architects?|Managers?|Directors?"),
	},
	{
		patterns.NewPatternTokenBuilder().TokenRegex("Junior|Senior").Build(),
		patterns.Token("Engineering"),
		patterns.TokenRegex("Manager[ns]?|Directors?"),
	},
	{
		patterns.CsToken("Business"),
		patterns.TokenRegex("Angel[ns]?|Cases?"),
	},
	{
		patterns.CsToken("Manager"),
		patterns.TokenRegex("Magazins?"),
	},
	{
		patterns.CsToken("Junior"),
		patterns.TokenRegex("Suite[sn]?"),
	},
	{
		patterns.TokenRegex("die|eine|unsere|meine|ihre|eure|(eben)?diese|seine|deine"),
		patterns.CsToken("Abt"),
		patterns.Token("."),
		patterns.TokenRegex(".+"),
	},
	{
		patterns.TokenRegex(".+"),
		patterns.TokenRegex(".+"),
		patterns.TokenRegex("Customer|User"),
		patterns.TokenRegex("Journeys?|Service"),
	},
	{
		patterns.TokenRegex(".+"),
		patterns.TokenRegex(".+"),
		patterns.Token("Hall"),
		patterns.Token("of"),
		patterns.Token("Fame"),
	},
	{
		patterns.Token("kühles"),
		patterns.Token("Blondes"),
	},
	{
		patterns.TokenRegex("Vitamin|Buchstabe"),
		patterns.TokenRegex("D|B[1-9]?|B12"),
	},
	{
		patterns.NewPatternTokenBuilder().Token("betreffen").MatchInflectedForms().Build(),
		patterns.CsToken("das"),
		patterns.PosRegex("SUB:AKK:PLU:.*"),
	},
	{
		patterns.Token("was"),
		patterns.CsToken("für"),
		patterns.CsToken("ein"),
		patterns.NewPatternTokenBuilder().PosRegex("ADJ:NOM:SIN:(MAS|NEU).*").Min(0).Build(),
		patterns.PosRegex("SUB:NOM:SIN:(MAS|NEU)"),
	},
	{
		patterns.Token("was"),
		patterns.CsToken("für"),
		patterns.CsToken("eine"),
		patterns.NewPatternTokenBuilder().PosRegex("ADJ:NOM:SIN:FEM.*").Min(0).Build(),
		patterns.Pos("SUB:NOM:SIN:FEM"),
	},
	{
		patterns.Token("was"),
		patterns.NewPatternTokenBuilder().Token("sein").MatchInflectedForms().SetSkip(2).Build(),
		patterns.CsToken("für"),
		patterns.CsToken("ein"),
		patterns.NewPatternTokenBuilder().PosRegex("ADJ:NOM:SIN:(MAS|NEU).*").Min(0).Build(),
		patterns.PosRegex("SUB:NOM:SIN:(MAS|NEU)"),
	},
	{
		patterns.Token("was"),
		patterns.NewPatternTokenBuilder().Token("sein").MatchInflectedForms().SetSkip(2).Build(),
		patterns.CsToken("für"),
		patterns.CsToken("eine"),
		patterns.NewPatternTokenBuilder().PosRegex("ADJ:NOM:SIN:FEM.*").Min(0).Build(),
		patterns.Pos("SUB:NOM:SIN:FEM"),
	},
	{
		patterns.CsRegex("vielen?|etliche|wenigen?|einigen?"),
		patterns.CsToken("Paar"),
		patterns.PosRegex("SUB:NOM:PLU:..."),
	},
	{
		patterns.CsRegex("machte?|ergibt|ergab|stiftete?"),
		patterns.CsToken("das"),
		patterns.CsToken("Sinn"),
	},
	{
		patterns.CsRegex("machte?"),
		patterns.CsToken("das"),
		patterns.CsRegex("Spa(ß|ss)|Freude"),
	},
	{
		patterns.CsRegex("sind|waren"),
		patterns.CsToken("beides"),
		patterns.NewPatternTokenBuilder().PosRegex("ADJ:.*").Min(0).Build(),
		patterns.PosRegex("SUB:NOM:PLU:.*"),
	},
	{
		patterns.Token("Heinrich"),
		patterns.Token("von"),
		patterns.Token("der"),
		patterns.CsRegex("Haars?"),
	},
	{
		patterns.Token("Präsident"),
		patterns.Token("Xi"),
	},
	{
		patterns.Token("Porsche"),
		patterns.Token("Museum"),
	},
	{
		patterns.Token("Auto"),
		patterns.Token("Club"),
		patterns.Token("Europa"),
	},
	{
		patterns.Token("Queen"),
		patterns.PosRegex("EIG:.*"),
	},
	{
		patterns.Token("King"),
		patterns.PosRegex("EIG:.*"),
	},
	{
		patterns.Token("des"),
		patterns.Token("Sturm"),
		patterns.Token("und"),
		patterns.CsRegex("Drangs?"),
	},
	{
		patterns.Token("die"),
		patterns.Token("Funke"),
		patterns.Token("Mediengruppe"),
	},
	{
		patterns.NewPatternTokenBuilder().CsToken("meinen").MatchInflectedForms().SetSkip(3).Build(),
		patterns.CsRegex("das|(eben)?dies(es)?"),
		patterns.NewPatternTokenBuilder().Token("wirklich").Min(0).Build(),
		patterns.Token("Ernst"),
	},
	{
		patterns.NewPatternTokenBuilder().CsToken("nehmen").MatchInflectedForms().SetSkip(3).Build(),
		patterns.CsRegex("das|(eben)?dies(es)?"),
		patterns.NewPatternTokenBuilder().Token("wirklich").Min(0).Build(),
		patterns.Token("Ernst"),
	},
	{
		patterns.NewPatternTokenBuilder().CsToken("sparen").MatchInflectedForms().SetSkip(3).Build(),
		patterns.CsRegex("das|(eben)?dies(es)?"),
		patterns.Token("Zeit"),
		patterns.Token("und"),
		patterns.CsRegex("Geld|Nerven"),
	},
	{
		patterns.CsRegex("das|es|(eben)?dies"),
		patterns.CsRegex("bedeutete?"),
		patterns.CsRegex("Krieg|Ärger"),
	},
	{
		patterns.TokenRegex("bedeutete?"),
		patterns.CsRegex("das|(eben)?dies"),
	},
	{
		patterns.TokenRegex("bietete?"),
		patterns.CsRegex("das|(eben)?dies"),
		patterns.PosRegex("SUB.*PLU.*"),
	},
	{
		patterns.CsRegex("bietete?"),
		patterns.CsRegex("das|(eben)?dies"),
		patterns.PosRegex("ADJ.*PLU.*"),
		patterns.PosRegex("SUB.*PLU.*"),
	},
	{
		patterns.CsRegex("bietete?"),
		patterns.CsRegex("das|(eben)?dies"),
		patterns.PosRegex("ADV.*"),
		patterns.PosRegex("ADJ.*PLU.*"),
		patterns.PosRegex("SUB.*PLU.*"),
	},
	{
		patterns.CsRegex("das|es|(eben)?dies"),
		patterns.CsRegex("weite"),
		patterns.Token("Teile"),
	},
	{
		patterns.Token("hat"),
		patterns.Token("das"),
		patterns.CsRegex("Einfluss|Auswirkungen"),
		patterns.CsRegex("auf|darauf"),
	},
	{
		patterns.PosRegex("VER.*[123].*"),
		patterns.TokenRegex("und|oder|aber"),
		patterns.NewPatternTokenBuilder().PosRegex("PRP.*").Min(0).Build(),
		patterns.TokenRegex("der|die|das|dem|den"),
	},
	{
		patterns.TokenRegex("bei|zum"),
		patterns.Token("anderen"),
		patterns.PosRegex("ADJ.*"),
		patterns.PosRegex("SUB.*"),
	},
	{
		patterns.Token("jeder"),
		patterns.PosRegex("SUB:(AKK|DAT).*"),
		patterns.PosRegex("VER.*"),
	},
	{
		patterns.PosRegex("(ART|PRO:DEM).*"),
		patterns.PosRegex("ADV.*"),
		patterns.PosRegex("SUB.*"),
		patterns.PosRegex("PA[12].*"),
	},
	{
		patterns.PosRegex("VER.*[123].*"),
		patterns.PosRegex("(ART|PRO:DEM).*"),
		patterns.PosRegex("ADV.*"),
		patterns.PosRegex("SUB.*"),
	},
	{
		patterns.Token("Deutsch"),
		patterns.Token("Langhaar"),
	},
	{
		patterns.NewPatternTokenBuilder().CsToken("nennen").MatchInflectedForms().Build(),
		patterns.Token("das"),
		patterns.PosRegex("SUB:NOM:SIN:(FEM|MAS)"),
	},
	{
		patterns.CsToken("Made"),
		patterns.CsToken("in"),
		patterns.CsToken("Germany"),
	},
	{
		patterns.CsRegex("[A-Z].+"),
		patterns.CsRegex("del?"),
		patterns.CsRegex("[A-Z].+"),
	},
	{
		patterns.CsRegex("[A-Z].+"),
		patterns.CsToken("de"),
		patterns.Regex("l[ao]s?"),
		patterns.CsRegex("[A-Z].+"),
	},
}
