package de

// Twin of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java
import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/lucasew/lang/internal/languagetool/org/languagetool/tools"
)

var _ = require.Equal
var _ = tools.Unimplemented

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java :: CaseRuleTest.testRuleActivation
func TestCaseRule_RuleActivation(t *testing.T) {
	// contains assertTrue
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java :: CaseRuleTest.testRule
func TestCaseRule_Rule(t *testing.T) {
	// contains assertEquals — full values in Java twin source
	_ = "(Dauer, Raum, Anwesende)" // assertGood
	_ = "Es gibt wenige Befragte." // assertGood
	_ = "Es gibt weniger Befragte, die das machen würden." // assertGood
	_ = "Es gibt mehr Befragte, die das machen würden." // assertGood
	_ = "Das ist eine Abkehr von Gottes Geboten." // assertGood
	_ = "Dem Hund Futter geben" // assertGood
	_ = "Heute spricht Frau Stieg." // assertGood
	_ = "So könnte es auch den Handwerksbetrieben gehen, die ausbilden und deren Ausbildung dann Industriebetrieben zugutekäme." // assertGood
	_ = "Die Firma Drosch hat nicht pünktlich geliefert." // assertGood
	_ = "3.1 Technische Dokumentation" // assertGood
	_ = "Ein einfacher Satz zum Testen." // assertGood
	_ = "Das Laufen fällt mir leicht." // assertGood
	_ = "Das Winseln stört." // assertGood
	_ = "Das schlägt nicht so zu Buche." // assertGood
	_ = "Dirk Hetzel ist ein Name." // assertGood
	_ = "Aber sie tat es, sodass unsere Klasse das sehen und fotografieren konnte." // assertGood
	_ = "Sein Verhalten war okay." // assertGood
	_ = "Hier ein Satz. \"Ein Zitat.\"" // assertGood
	_ = "Hier ein Satz. 'Ein Zitat.'" // assertGood
	_ = "Hier ein Satz. «Ein Zitat.»" // assertGood
	_ = "Hier ein Satz. »Ein Zitat.«" // assertGood
	_ = "Hier ein Satz. (Noch einer.)" // assertGood
	_ = "Hier geht es nach Tel Aviv." // assertGood
	_ = "Unser Jüngster ist da." // assertGood
	_ = "Alles Erfundene ist wahr." // assertGood
	_ = "Sie hat immer ihr Bestes getan." // assertGood
	_ = "Er wird etwas Verrücktes träumen." // assertGood
	_ = "Er wird etwas schön Verrücktes träumen." // assertGood
	_ = "Er wird etwas ganz schön Verrücktes träumen." // assertGood
	_ = "Mit aufgewühltem Innerem." // assertGood
	_ = "Mit völlig aufgewühltem Innerem." // assertGood
	_ = "Er wird etwas so Verrücktes träumen." // assertGood
	_ = "Tom ist etwas über dreißig." // assertGood
	_ = "Diese Angriffe bleiben im Verborgenen." // assertGood
	_ = "Ihr sollt mich das wissen lassen." // assertGood
	_ = "Wenn er mich das rechtzeitig wissen lässt, gerne." // assertGood
	_ = "Und sein völlig aufgewühltes Inneres erzählte von den Geschehnissen." // assertGood
	_ = "Aber sein aufgewühltes Inneres erzählte von den Geschehnissen." // assertGood
	_ = "Sein aufgewühltes Inneres erzählte von den Geschehnissen." // assertGood
	_ = "Aber sein Inneres erzählte von den Geschehnissen." // assertGood
	_ = "Ein Kaninchen, das zaubern kann." // assertGood
	_ = "Keine Ahnung, wie ich das prüfen sollte." // assertGood
	_ = "Und dann noch Strafrechtsdogmatikerinnen." // assertGood
	_ = "Er kann ihr das bieten, was sie verdient." // assertGood
	_ = "Das fragen sich mittlerweile viele." // assertGood
	_ = "Ich habe gehofft, dass du das sagen würdest." // assertGood
	_ = "Eigentlich hätte ich das wissen müssen." // assertGood
	_ = "Mir tut es wirklich leid, Ihnen das sagen zu müssen." // assertGood
	_ = "Der Wettkampf endete im Unentschieden." // assertGood
	_ = "Er versuchte, Neues zu tun." // assertGood
	_ = "Du musst das wissen, damit du die Prüfung bestehst" // assertGood
	_ = "Er kann ihr das bieten, was sie verdient." // assertGood
	_ = "Er fragte, ob das gelingen wird." // assertGood
	_ = "Er mag Obst, wie zum Beispel Apfelsinen." // assertGood
	_ = "Er will die Ausgaben für Umweltschutz und Soziales kürzen." // assertGood
	_ = "Die Musicalverfilmung „Die Schöne und das Biest“ bricht mehrere Rekorde." // assertGood
	_ = "Joachim Sauer lobte Johannes Rau." // assertGood
	_ = "Im Falle des Menschen ist dessen wirkendes Wollen gegeben." // assertGood
	_ = "Szenario: 1) Zwei Galaxien verschmelzen." // assertGood
	_ = "Existieren Außerirdische im Universum?" // assertGood
	_ = "Tom vollbringt Außerordentliches." // assertGood
	_ = "Er führt Böses im Schilde." // assertGood
	_ = "Es gab Überlebende." // assertGood
	_ = "'Wir werden das stoppen.'" // assertGood
	_ = "Wahre Liebe muss das aushalten." // assertGood
	_ = "Du kannst das machen." // assertGood
	_ = "Vor dem Aus stehen." // assertGood
	_ = "Ich Armer!" // assertGood
	_ = "Hallo Malte," // assertGood
	_ = "Parks Vertraute Choi Soon Sil ist zu drei Jahren Haft verurteilt worden." // assertGood
	_ = "Bei einer Veranstaltung Rechtsextremer passierte es." // assertGood
	_ = "Eine Gruppe Betrunkener singt." // assertGood
	_ = "Bei Betreten des Hauses." // assertGood
	_ = "Das Aus für Italien ist bitter." // assertGood
	_ = "Das Aus kam unerwartet." // assertGood
	_ = "Anmeldung bis Fr. 1.12." // assertGood
	_ = "Gibt es die Schuhe auch in Gr. 43?" // assertGood
	_ = "Weil er Unmündige sexuell missbraucht haben soll, wurde ein Lehrer verhaftet." // assertGood
	_ = "Tausende Gläubige kamen." // assertGood
	_ = "Es kamen Tausende Gläubige." // assertGood
	_ = "Das schließen Forscher aus den gefundenen Spuren." // assertGood
	_ = "Wieder Verletzter bei Unfall" // assertGood
	_ = "Eine Gruppe Aufständischer verwüstete die Bar." // assertGood
	_ = "‚Dieser Satz.‘ Hier kommt der nächste Satz." // assertGood
	_ = "Dabei werden im Wesentlichen zwei Prinzipien verwendet:" // assertGood
	_ = "Er fragte, ob das gelingen oder scheitern wird." // assertGood
	_ = "Einen Tag nach Bekanntwerden des Skandals" // assertGood
	_ = "Das machen eher die Erwachsenen." // assertGood
	_ = "Das ist ihr Zuhause." // assertGood
	_ = "Das ist Sandras Zuhause." // assertGood
	_ = "Das machen eher wohlhabende Leute." // assertGood
	_ = "Als Erstes würde ich sofort die Struktur ändern." // assertGood
	_ = "Er sagte: Als Erstes würde ich sofort die Struktur ändern." // assertGood
	_ = "Das schaffen moderne E-Autos locker." // assertGood
	_ = "Das schaffen moderne E-Autos schneller" // assertGood
	_ = "Das schaffen moderne und effizientere E-Autos schneller." // assertGood
	_ = "Das verwalten User." // assertGood
	_ = "Man kann das generalisieren" // assertGood
	_ = "Aber wie wir das machen und sicher gestalten, darauf konzentriert sich unsere Arbeit." // assertGood
	_ = "Vielleicht kann man das erweitern" // assertGood
	_ = "Vielleicht soll er das generalisieren" // assertGood
	_ = "Wahrscheinlich müssten sie das überarbeiten" // assertGood
	_ = "Assistenzsysteme warnen rechtzeitig vor Gefahren." // assertGood
	_ = "Jeremy Schulte rannte um sein Leben." // assertGood
	_ = "Er arbeitet im Bereich Präsidiales." // assertGood
	_ = "Er spricht Sunnitisch & Schiitisch." // assertGood
	_ = "Er sagte, Geradliniges und Krummliniges sei unvergleichbar." // assertGood
	_ = "Dort erfahren sie Kurioses und Erstaunliches zum Zusammenspiel von Mensch und Natur." // assertGood
	_ = "Dabei unterscheidet die Shareware zwischen Privatem und Dienstlichem bei Fahrten ebenso wie bei Autos." // assertGood
	_ = "Besucher erwartet Handegefertigtes, Leckeres und Informatives rund um den Hund." // assertGood
	_ = "Der Unterschied zwischen Vorstellbarem und Machbarem war niemals geringer." // assertGood
	_ = "Das war Fiete Lang." // assertGood
	_ = "Wenn du an das glaubst, was du tust, kannst du Großes erreichen." // assertGood
	_ = "Dann hat er Großes erreicht." // assertGood
	_ = "Dann hat er Großes geleistet." // assertGood
	_ = "Das Thema Datenaustauschverfahren ist mir wichtig." // assertGood
	_ = "Ist das eine Frage ? Müsste das nicht anders sein?" // assertGood
	_ = "Das ist ein Satz !!! Das auch." // assertGood
	_ = "Der russische Erdölmagnat Emanuel Nobel, der Erbauer des ersten Dieselmotorschiffes." // assertGood
	_ = "Zur Versöhnung: Jüdische Gläubige sollen beten." // assertGood
	_ = "Fast im Stundentakt wurden neue Infizierte gemeldet." // assertGood
	_ = "Bert Van Den Brink" // assertGood
	_ = "“In den meisten Bundesländern werden solche Studien per se nicht durchgeführt.”" // assertGood
	_ = "Aber “in den meisten Bundesländern werden solche Studien per se nicht durchgeführt.”" // assertGood
	_ = "A) Das Haus" // assertGood
	_ = "Rabi und Polykarp Kusch an der Columbia-Universität" // assertGood
	_ = "Man geht davon aus, dass es sich dabei nicht um Reinigungsverhalten handelt." // assertGood
	_ = "Wenn dort oft Gefahren lauern." // assertGood
	_ = "3b) Den Bereich absichern" // assertGood
	_ = "@booba Da der Holger keine Zeit hat ..." // assertGood
	_ = "Es gibt infizierte Ärzt*innen." // assertGood
	_ = "WUrzeln" // assertGood
	_ = "🙂 Übrigens finde ich dein neues Ordnungssystem richtig genial!" // assertGood
	_ = "Ein 10,4 Ah Lithium-Akku" // assertGood
	_ = "14:15 Uhr SpVgg Westheim" // assertGood
	_ = "Unser Wärmestrom-Tarif WärmeKompakt im Detail" // assertGood
	_ = "Autohaus Dornig GmbH" // assertGood
	_ = "Hans Pries GmbH" // assertGood
	_ = "Der Kund*innenservice war auch sehr kulant und persönlich." // assertGood
	_ = ":D Auf dieses Frl." // assertGood
	_ = "@b_fischer Der Bonussemester-Antrag oder der Widerspruch?" // assertGood
	_ = "Das Gedicht “Der Panther”." // assertGood
	_ = "Klar, dass wir das brauchen." // assertGood
	_ = "Das wird Scholz' engster Vertrauter Wolfgang Schmidt übernehmen." // assertGood
	_ = "Bei der Fülle an Vorgaben kann das schnell vergessen werden." // assertGood
	_ = "Majid ergänzte: ”Vorläufigen Analysen der Terrakottaröhren aus Ardais liegen ..." // assertGood
	_ = "Ist das eine Frage ? Müsste das nicht anders sein?" // assertGood
	_ = "Das ist ein Satz !!! Das auch." // assertGood
	_ = "Liebe Kund:in" // assertGood
	_ = "Wir sollten das mal labeln." // assertGood
	_ = "Teil 1: Der unaufhaltsame Aufstieg Bonapartes" // assertGood
	_ = "Der Absatz bestimmt, in welchem Maße diese Daten Dritten zugänglich gemacht werden." // assertGood
	_ = "Der TN spricht Russisch - Muttersprache" // assertGood
	_ = "Ich musste das Video mehrmals stoppen, um mir über das Gesagte Gedanken zu machen." // assertGood
	_ = "Während Besagtes Probleme verursachte." // assertGood
	_ = "Während der Befragte Geschichten erzählte." // assertGood
	_ = "Während ein Befragter Geschichten erzählte." // assertGood
	_ = "... für welche ein Befragter Geld ausgegeben hat." // assertGood
	_ = "Während die Befragte Geld verdiente." // assertGood
	_ = "Während die Besagte Geschichten erzählte." // assertGood
	_ = "Sind dem Zahlungspflichtigen Kosten entstanden?" // assertGood
	_ = "Jetzt, wo Protestierende und Politiker sich streiten" // assertGood
	_ = "Während die Besagte Geld verdiente." // assertGood
	_ = "Die Nacht, die Liebe, dazu der Wein — zu nichts Gutem Ratgeber sein." // assertGood
	_ = "Warum tun die Menschen Böses?" // assertGood
	_ = "Und das Vergangene Revue passieren lassen" // assertGood
	_ = "Seither ist das Französische Amtssprache in Frankreich." // assertGood
	_ = "Für die Betreute Kontoauszüge holen." // assertGood
	_ = "Das verstehen Deutsche halt nicht." // assertGood
	_ = "12:00 - 13:00 Gemeinsames Mittagessen" // assertGood
	_ = "12:00 Gemeinsames Mittagessen" // assertGood
	_ = "Meld dich, wenn du Großes vorhast." // assertGood
	_ = "Muss nicht der Einzelne Einschränkungen der Freiheit hinnehmen, wenn die Sicherheit der Menschen und des Staates mehr gefährdet sind?" // assertGood
	_ = "Wie reißt ein Einzelner Millionen aus ihren Sitzen?" // assertGood
	_ = "Der Aphorismus will nicht Dumme gescheit, sondern Gescheite nachdenklich machen." // assertGood
	_ = "Während des Hochwassers den Eingeschlossenen Wasser und Nahrung bringen" // assertGood
	_ = "Aus dem Stein der Weisen macht ein Dummer Schotter." // assertGood
	_ = "Auf dem Weg zu ihnen begegnet der Halbwüchsige Revolverhelden und Indianern." // assertGood
	_ = "▶︎ Dies ist ein Test" // assertGood
	_ = "▶ Dies ist ein Test" // assertGood
	_ = "* Dies ist ein Test" // assertGood
	_ = "- Dies ist ein Test" // assertGood
	_ = "• Dies ist ein Test" // assertGood
	_ = ":-) Dies ist ein Test" // assertGood
	_ = ";-) Dies ist ein Test" // assertGood
	_ = ":) Dies ist ein Test" // assertGood
	_ = ";) Dies ist ein Test" // assertGood
	_ = "..., die ins Nichts griff." // assertGood
	_ = "Er fragte, was sie über das denken und zwinkerte ihnen zu." // assertGood
	_ = "dem Ägyptischen, Berberischen, Semitischen, Kuschitischen, Omotischen und dem Tschadischen" // assertGood
	_ = "mit S-Bahn-ähnlichen Verkehrsmitteln" // assertGood
	_ = "mit U-Bahn-ähnlichen und günstigen Verkehrsmitteln" // assertGood
	_ = "mit Ü-Ei-großen, schweren Hagelkörnern" // assertGood
	_ = "mit E-Musik-artigen, komplizierten Harmonien" // assertGood
	_ = "eBay International AG" // assertGood
	_ = "Harald & Schön" // assertGood
	_ = "Nicholas and Stark" // assertGood
	_ = "Die Schweizerische Bewachungsgesellschaft" // assertGood
	_ = "Stets suchte er das Extreme." // assertGood
	_ = "Ich möchte zwei Kilo Zwiebeln." // assertGood
	_ = "Ein Menschenfreund." // assertGood
	_ = "Der Nachfahre." // assertGood
	_ = "Hier ein Satz, \"Ein Zitat.\"" // assertGood
	_ = "Hier ein Satz, \"ein Zitat.\"" // assertGood
	_ = "Schon Le Monde schrieb das." // assertGood
	_ = "In Blubberdorf macht man das so." // assertGood
	_ = "Der Thriller spielt zur Zeit des Zweiten Weltkriegs" // assertGood
	_ = "Anders als physikalische Konstanten werden mathematische Konstanten unabhängig von jedem physikalischen Maß definiert." // assertGood
	_ = "Eine besonders einfache Klasse bilden die polylogarithmischen Konstanten." // assertGood
	_ = "Das südlich von Berlin gelegene Dörfchen." // assertGood
	_ = "Weil er das kommen sah, traf er Vorkehrungen." // assertGood
	_ = "Sie werden im Allgemeinen gefasst." // assertGood
	_ = "Sie werden im allgemeinen Fall gefasst." // assertGood
	_ = "Das sind Euroscheine." // assertGood
	_ = "John Stallman isst." // assertGood
	_ = "Das ist die neue Gesellschafterin hier." // assertGood
	_ = "Das ist die neue Dienerin hier." // assertGood
	_ = "Das ist die neue Geigerin hier." // assertGood
	_ = "Die ersten Gespanne erreichen Köln." // assertGood
	_ = "Er beschrieb den Angeklagten wie einen Schuldigen" // assertGood
	_ = "Er beschrieb den Angeklagten wie einen Schuldigen." // assertGood
	_ = "Es dauerte bis ins neunzehnte Jahrhundert" // assertGood
	_ = "Das ist das Dümmste, was ich je gesagt habe." // assertGood
	_ = "Wacht auf, Verdammte dieser Welt!" // assertGood
	_ = "Er sagt, dass Geistliche davon betroffen sind." // assertGood
	_ = "Man sagt, Liebe mache blind." // assertGood
	_ = "Die Deutschen sind sehr listig." // assertGood
	_ = "Der Lesestoff bestimmt die Leseweise." // assertGood
	_ = "Ich habe nicht viel von einem Reisenden." // assertGood
	_ = "Die Vereinigten Staaten" // assertGood
	_ = "Der Satz vom ausgeschlossenen Dritten." // assertGood
	_ = "Die Ausgewählten werden gut betreut." // assertGood
	_ = "Die ausgewählten Leute werden gut betreut." // assertGood
	_ = "Die Schlinge zieht sich zu." // assertGood
	_ = "Die Schlingen ziehen sich zu." // assertGood
	_ = "Sie fällt auf durch ihre hilfsbereite Art. Zudem zeigt sie soziale Kompetenz." // assertGood
	_ = "Die Lieferadresse ist Obere Brandstr. 4-7" // assertGood
	_ = "Das ist es: kein Satz." // assertGood
	_ = "Werner Dahlheim: Die Antike." // assertGood
	_ = "1993: Der talentierte Mr. Ripley" // assertGood
	_ = "Ian Kershaw: Der Hitler-Mythos: Führerkult und Volksmeinung." // assertGood
	_ = "Ich frage mich: Warum?" // assertGood
	_ = "Ich frage mich: Wieso?" // assertGood
	_ = "Ich frage mich: Weshalb?" // assertGood
	_ = "Ich frage mich: Und warum?" // assertGood
	_ = "Ich frage mich: Oder wieso?" // assertGood
	_ = "Ich frage mich: Aber warum?" // assertGood
	_ = "Das wirklich Wichtige ist dies:" // assertGood
	_ = "Das wirklich wichtige Verfahren ist dies:" // assertGood
	_ = "Im Norwegischen klingt das schöner." // assertGood
	_ = "Übersetzt aus dem Norwegischen von Ingenieur Frederik Dingsbums." // assertGood
	_ = "Dem norwegischen Ingenieur gelingt das gut." // assertGood
	_ = "Peter Peterson, dessen Namen auf Griechisch Stein bedeutet." // assertGood
	_ = "Peter Peterson, dessen Namen auf Griechisch gut klingt." // assertGood
	_ = "Das dabei Erlernte und Erlebte ist sehr nützlich." // assertGood
	_ = "Ein Kapitän verlässt als Letzter das sinkende Schiff." // assertGood
	_ = "Es hilft, die Harmonie zwischen Führer und Geführten zu stützen." // assertGood
	_ = "Das Gebäude des Auswärtigen Amts." // assertGood
	_ = "Das Gebäude des Auswärtigen Amtes." // assertGood
	_ = "   Im Folgenden beschreibe ich das Haus." // assertGood
	_ = "\"Im Folgenden beschreibe ich das Haus.\"" // assertGood
	_ = "Gestern habe ich 10 Spieße gegessen." // assertGood
	_ = "Die Verurteilten wurden mit dem Fallbeil enthauptet." // assertGood
	_ = "Den Begnadigten kam ihre Reue zugute." // assertGood
	_ = "Die Zahl Vier ist gerade." // assertGood
	_ = "Ich glaube, dass das geschehen wird." // assertGood
	_ = "Ich glaube, dass das geschehen könnte." // assertGood
	_ = "Ich glaube, dass mir das gefallen wird." // assertGood
	_ = "Ich glaube, dass mir das gefallen könnte." // assertGood
	_ = "Alldem wohnte etwas faszinierend Rätselhaftes inne." // assertGood
	_ = "Schau mich an, Kleine!" // assertGood
	_ = "Schau mich an, Süßer!" // assertGood
	_ = "Weißt du, in welchem Jahr das geschehen ist?" // assertGood
	_ = "Das wissen viele nicht." // assertGood
	_ = "Die zum Tode Verurteilten wurden in den Hof geführt." // assertGood
	_ = "Wenn Sie das schaffen, retten Sie mein Leben!" // assertGood
	_ = "Etwas Grünes, Schleimiges klebte an dem Stein." // assertGood
	_ = "Er befürchtet Schlimmeres." // assertGood
	_ = "#4 Aktuelle Situation" // assertGood
	_ = "Er trinkt ein kühles Blondes." // assertGood
	_ = "* [ ] Ein GitHub Markdown Listenpunkt" // assertGood
	_ = "Tom ist ein engagierter, gutaussehender Vierzigjähriger, der..." // assertGood
	_ = "a.) Im Zusammenhang mit ..." // assertGood
	_ = "✔︎ Weckt Aufmerksamkeit." // assertGood
	_ = "Hallo Eckhart," // assertGood
	_ = "Er kann Polnisch und Urdu." // assertGood
	_ = "---> Der USB 3.0 Stecker" // assertGood
	_ = "Black Lives Matter" // assertGood
	_ = "== Schrittweise Erklärung" // assertGood
	_ = "Audi A5 Sportback 2.0 TDI" // assertGood
	_ = "§ 1 Allgemeine Bedingungen" // assertGood
	_ = "§1 Allgemeine Bedingungen" // assertGood
	_ = "[H3] Was ist Daytrading?" // assertGood
	_ = " Das ist das Aus des Airbus A380." // assertGood
	_ = "Wir sollten ihr irgendwas Erotisches schenken." // assertGood
	_ = "Er trank ein paar Halbe." // assertGood
	_ = "Sie/Er hat Schuld." // assertGood
	_ = "Das war irgendein Irrer." // assertGood
	_ = "Wir wagen Neues." // assertGood
	_ = "Grundsätzlich gilt aber: Essen Sie, was die Einheimischen Essen." // assertGood
	_ = "Vielleicht reden wir später mit ein paar Einheimischen." // assertGood
	_ = "Das denken zwar viele, ist aber total falsch." // assertGood
	_ = "Ich habe nix Besseres gefunden." // assertGood
	_ = "Ich habe nichts Besseres gefunden." // assertGood
	_ = "Ich habe noch Dringendes mitzuteilen." // assertGood
	_ = "Er isst UV-bestrahltes Obst." // assertGood
	_ = "Er isst Na-haltiges Obst." // assertGood
	_ = "Er vertraut auf CO2-arme Wasserkraft" // assertGood
	_ = "Das Entweder-oder ist kein Problem." // assertGood
	_ = "Er liebt ihre Makeup-freie Haut." // assertGood
	_ = "Das ist eine Schreibweise." // assertGood
	_ = "Das ist ein Mann." // assertGood
	_ = "Du Ärmste!" // assertGood
	_ = "Ich habe nur Schlechtes über den Laden gehört." // assertGood
	_ = "Du Ärmster, leg dich besser ins Bett." // assertGood
	_ = "Er wohnt Am Hohen Hain 6a" // assertGood
	_ = "Das Bauvorhaben Am Wiesenhang 9" // assertGood
	_ = "... und das Zwischenmenschliche Hand in Hand." // assertGood
	_ = "Der Platz auf dem die Ahnungslosen Kopf an Kopf stehen." // assertGood
	_ = "4.)   Bei Beschäftigung von Hilfskräften: Schadenfälle durch Hilfskräfte" // assertGood
	_ = "Es besteht aus Schülern, Arbeitstätigen und Studenten." // assertGood
	_ = "Sie starrt ständig ins Nichts." // assertGood
	_ = "Sowas aber auch.\u2063Das Haus ist schön." // assertGood
	_ = "\u2063Das Haus ist schön." // assertGood
	_ = "\u2063\u2063Das Haus ist schön." // assertGood
	_ = "Die Mannschaft ist eine gelungene Mischung aus alten Haudegen und jungen Wilden." // assertGood
	_ = "Alleine durch die bloße Einwohnerzahl des Landes leben im Land zahlreiche Kulturschaffende, nach einer Schätzung etwa 30.000 Künstler." // assertGood
	_ = "Ich hatte das offenbar vergessen oder nicht ganz verstanden." // assertGood
	_ = "Ich hatte das vergessen oder nicht ganz verstanden." // assertGood
	_ = "Das ist ein zwingendes Muss." // assertGood
	_ = "Er hält eine Handbreit Abstand." // assertGood
	_ = "Das ist das Debakel und Aus für Podolski." // assertGood
	_ = "Ein Highlight für Klein und Groß!" // assertGood
	_ = "Der schwedische Psychologe Dan Katz, Autor von 'Angst kocht auch nur mit Wasser', sieht in der Corona-Krise dennoch nicht nur Negatives." // assertGood
	_ = "Während des Hochwassers den Eingeschlossenen Menschen Nahrung bringen" // assertBad
	_ = "Während Gefragte Menschen antworteten." // assertBad
	_ = "Ich brauche eine Gratis App die Ohne WLAN." // assertBad
	_ = "Alle Kommunikationsmedien die Meinem Widersacher dienen werden." // assertBad
	_ = "Ich wünsche dir Alles Liebe." // assertBad
	_ = "Das Auto Meines Vaters wird in Italien produziert." // assertBad
	_ = "Nach Böhm-Bawerk steht die Allgemeine Profitrate und die Theorie der Produktionspreise im Widerspruch zum Wertgesetz des ersten Bandes." // assertBad
	_ = "Ich sehe da keine Absolute Schranke." // assertBad
	_ = "Manns und Fontanes Gesammelten Werken." // assertBad
	_ = "Und das Neue Haus." // assertBad
	_ = "Das sind die Die Lehrer." // assertBad
	_ = "An der flachen Decke zeigt ein Großes Bildnis die Geburt Christi und die ewige Anbetung der Hirten." // assertBad
	_ = "Und das Gesagte Wort." // assertBad
	_ = "Und die Gesagten Wörter." // assertBad
	_ = "Und meine Erzählte Geschichte." // assertBad
	_ = "Und diese Erzählten Geschichten." // assertBad
	_ = "Und eine Neue Zeit." // assertBad
	_ = "Das machen der Töne ist schwierig." // assertBad
	_ = "Sie Vertraute niemandem." // assertBad
	_ = "Beten Lernt man in Nöten." // assertBad
	_ = "Ich habe Heute keine Zeit." // assertBad
	_ = "Er sagte, Geradliniges und krummliniges sei unvergleichbar." // assertBad
	_ = "Er sagte, ein Geradliniges und Krummliniges Konzept ist nicht tragbar." // assertBad
	_ = "Ä Was?" // assertBad
	_ = "… die preiswerte Variante unserer Topseller im Bereich Alternativ Mehle." // assertBad
	_ = "…  jahrzehntelangen Mitstreitern und vielen Freunden aus Nah und Fern." // assertBad
	_ = "Hi und Herzlich willkommen auf meiner Seite." // assertBad
	_ = "Er ist Groß." // assertBad
	_ = "Die Zahl ging auf Über 1.000 zurück." // assertBad
	_ = "Er sammelt Große und kleine Tassen." // assertBad
	_ = "Er sammelt Große, mittlere und kleine Tassen." // assertBad
	_ = "Dann will sie mit London Über das Referendum verhandeln." // assertBad
	_ = "Sie kann sich täglich Über vieles freuen." // assertBad
	_ = "Der Vater (51) Fuhr nach Rom." // assertBad
	_ = "Er müsse Überlegen, wie er das Problem löst." // assertBad
	_ = "Er sagte, dass er Über einen Stein stolperte." // assertBad
	_ = "Tom ist etwas über Dreißig." // assertBad
	_ = "Unser warten wird sich lohnen." // assertBad
	_ = "Tom kann mit fast Allem umgehen." // assertBad
	_ = "Dabei Übersah er sie." // assertBad
	_ = "Der Brief wird am Mittwoch in Brüssel Übergeben." // assertBad
	_ = "Damit sollen sie die Versorgung in der Region Übernehmen." // assertBad
	_ = "Die Unfallursache scheint geklärt, ein Lichtsignal wurde Überfahren." // assertBad
	_ = "Der Lenker hatte die Höchstgeschwindigkeit um 76 km/h Überschritten." // assertBad
	_ = "Das sind 10 Millionen Euro, Gleichzeitig und zusätzlich." // assertBad
	_ = "Sie werden im Allgemeinen Fall gefasst." // assertBad
	_ = "Das ist das Dümmste Kind." // assertBad
	_ = "Er sagt, dass Geistliche Würdenträger davon betroffen sind." // assertBad
	_ = "Er sagt, dass Geistliche und weltliche Würdenträger davon betroffen sind." // assertBad
	_ = "Er ist begeistert Von der Fülle." // assertBad
	_ = "Er wohnt Über einer Garage." // assertBad
	_ = "Die Anderen 90 Prozent waren krank." // assertBad
	_ = "Die Ausgewählten Leute werden gut betreut." // assertBad
	_ = "Er war dort Im März 2000." // assertBad
	_ = "Er war dort Im Jahr 96." // assertBad
	_ = "Das ist es: Kein Satz." // assertBad
	_ = "Wen magst du lieber: Die Giants oder die Dragons?" // assertBad
	_ = "Ich frage mich: Warum Das so ist." // assertBad
	_ = "Das wirklich Wichtige Verfahren ist dies:" // assertBad
	_ = "Die Schöne Tür" // assertBad
	_ = "Das Blaue Auto." // assertBad
	_ = "Ein Einfacher Satz zum Testen." // assertBad
	_ = "Eine Einfache Frage zum Testen?" // assertBad
	_ = "Er kam Früher als sonst." // assertBad
	_ = "Er rennt Schneller als ich." // assertBad
	_ = "Das Winseln Stört." // assertBad
	_ = "Sein verhalten war okay." // assertBad
	_ = "Dem Norwegischen Ingenieur gelingt das gut." // assertBad
	_ = "Das dabei erlernte und Erlebte Wissen ist sehr nützlich." // assertBad
	_ = "Diese Regelung wurde als Überholt bezeichnet." // assertBad
	_ = "Die Dolmetscherin und Der Vorleser gehen spazieren." // assertBad
	_ = "Das sagen haben hier viele." // assertBad
	_ = "Bis Bald!" // assertBad
	_ = "Das existiert im Jazz zunehmend nicht mehr Bei der weiteren Entwicklung des Jazz zeigt sich das." // assertBad
	_ = "Das ist Eine Schreibweise." // assertBad
	_ = "Das ist Ein Mann." // assertBad
	_ = "Sie erhalten bald unsere Neuesten Insights." // assertBad
	_ = "Auf eine Carvingschiene sollte die Kette schon im Kalten Zustand weit durchhängen." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java :: CaseRuleTest.testSubstantivierteVerben
func TestCaseRule_SubstantivierteVerben(t *testing.T) {
	_ = "Das fahrende Auto." // assertGood
	_ = "Das können wir so machen." // assertGood
	_ = "Denn das Fahren ist einfach." // assertGood
	_ = "Das Fahren ist einfach." // assertGood
	_ = "Das Gehen fällt mir leicht." // assertGood
	_ = "Das Ernten der Kartoffeln ist mühsam." // assertGood
	_ = "Entschuldige das späte Weiterleiten." // assertGood
	_ = "Ich liebe das Lesen." // assertGood
	_ = "Das Betreten des Rasens ist verboten." // assertGood
	_ = "Das haben wir aus eigenem Antrieb getan." // assertGood
	_ = "Das haben wir." // assertGood
	_ = "Das haben wir schon." // assertGood
	_ = "Das lesen sie doch sicher in einer Minute durch." // assertGood
	_ = "Das lesen Sie doch sicher in einer Minute durch!" // assertGood
	_ = "Formationswasser, das oxidiert war." // assertGood
	_ = "Um das herauszubekommen diskutieren zwei Experten." // assertGood
	_ = "Ich würde ihn dann mal nach München schicken, damit die beiden das planen/entwickeln können." // assertGood
	_ = "Das Lesen fällt mir schwer." // assertGood
	_ = "Sie hörten ein starkes Klopfen." // assertGood
	_ = "Wer erledigt das Fensterputzen?" // assertGood
	_ = "Viele waren am Zustandekommen des Vertrages beteiligt." // assertGood
	_ = "Die Sache kam ins Stocken." // assertGood
	_ = "Das ist zum Lachen." // assertGood
	_ = "Euer Fernbleiben fiel uns auf." // assertGood
	_ = "Uns half nur noch lautes Rufen." // assertGood
	_ = "Die Mitbewohner begnügten sich mit Wegsehen und Schweigen." // assertGood
	_ = "Sie wollte auf Biegen und Brechen gewinnen." // assertGood
	_ = "Er klopfte mit Zittern und Zagen an." // assertGood
	_ = "Ich nehme die Tabletten auf Anraten meiner Ärztin." // assertGood
	_ = "Sie hat ihr Soll erfüllt." // assertGood
	_ = "Dies ist ein absolutes Muss." // assertGood
	_ = "Das Lesen fällt mir schwer." // assertGood
	_ = "Das fahren ist einfach." // assertBad
	_ = "Denn das fahren ist einfach." // assertBad
	_ = "Denn das laufen ist einfach." // assertBad
	_ = "Denn das essen ist einfach." // assertBad
	_ = "Denn das gehen ist einfach." // assertBad
	_ = "Das Große Auto wurde gewaschen." // assertBad
	_ = "Ich habe ein Neues Fahrrad." // assertBad
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java :: CaseRuleTest.testPhraseExceptions
func TestCaseRule_PhraseExceptions(t *testing.T) {
	tools.Unimplemented("CaseRuleTest.testPhraseExceptions")
}

// Port of languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java :: CaseRuleTest.testCompareLists
func TestCaseRule_CompareLists(t *testing.T) {
	// contains assertTrue
	// contains assertFalse
}
