package de

import "github.com/lucasew/lang/internal/languagetool/org/languagetool/rules/patterns"

// CompoundInfinitivAntiPatterns ports CompoundInfinitivRule.ANTI_PATTERNS.
// Coverage: 25/25; 0 omitted.
var CompoundInfinitivAntiPatterns = [][]*patterns.PatternToken{
	{
		patterns.Token("auf"),
		patterns.Token("Nummer"),
		patterns.Token("sicher"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("ab"),
		patterns.TokenRegex("und|&"),
		patterns.Token("an"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("ganz"),
		patterns.Token("schön"),
		patterns.Token("zu"),
	},
	{
		patterns.TokenRegex("fang|fängst|fängt|fangt|fangen|fing|fingen"),
		patterns.PosRegex("ADV.*"),
		patterns.Token("an"),
		patterns.Token("zu"),
	},
	{
		patterns.TokenRegex("dazu|darüber"),
		patterns.Token("zu"),
		patterns.Token("machen"),
	},
	{
		patterns.Token("schön"),
		patterns.Token("zu"),
		patterns.Token("machen"),
	},
	{
		patterns.Token("kurz"),
		patterns.Token("davor"),
		patterns.Token("zu"),
	},
	{
		patterns.TokenRegex("Jahr|Monat|Zeit"),
		patterns.Token("über"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("endlich"),
		patterns.Token("wieder"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("bis"),
		patterns.Token("hin"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("von"),
		patterns.TokenRegex(".*[a-z].*"),
		patterns.Token("her"),
		patterns.Token("zu"),
	},
	{
		patterns.TokenRegex("sehr|ganz|äu(ss|ß)erst|zu|nicht|absolut|total|wirklich|möglichst"),
		patterns.PosRegex("ADJ.*"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("Schritt"),
		patterns.Token("weiter"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("und"),
		patterns.Token("so"),
		patterns.Token("weiter"),
	},
	{
		patterns.Token("darauf"),
		patterns.Token("zu"),
		patterns.PosRegex("VER.*"),
		patterns.Token("dass"),
	},
	{
		patterns.Token("darauf"),
		patterns.Token("zu"),
		patterns.PosRegex("VER.*"),
		patterns.Token(","),
	},
	{
		patterns.TokenRegex("Spiel|Tag|Nacht|Morgen|Nachmittag|Abend|Zeit|.+zeit|Jahr(zehnt)?|Monat|.+tag|Mittwoch|Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember"),
		patterns.Token("über"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("kurz"),
		patterns.Token("zu"),
		patterns.Token("machen"),
	},
	{
		patterns.Token("dazu"),
		patterns.Token("zu"),
		patterns.Token("haben"),
	},
	{
		patterns.TokenRegex("deutlich|viel|Stück|nichts|nix|noch"),
		patterns.Token("weiter"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("auf"),
		patterns.TokenRegex("und|&|oder|\\/"),
		patterns.NewPatternTokenBuilder().PosRegex("ADV.*").Min(0).Build(),
		patterns.Token("ab"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("zu"),
		patterns.PosRegex("ADJ.*"),
		patterns.Token("zu"),
	},
	{
		patterns.Token("hin"),
		patterns.TokenRegex("und|&|oder|\\/"),
		patterns.NewPatternTokenBuilder().PosRegex("ADV.*").Min(0).Build(),
		patterns.Token("her"),
		patterns.Token("zu"),
	},
	{
		patterns.TokenRegex("rauf|hoch"),
		patterns.TokenRegex("und|&|oder|\\/"),
		patterns.NewPatternTokenBuilder().PosRegex("ADV.*").Min(0).Build(),
		patterns.Token("runter"),
		patterns.Token("zu"),
	},
	{
		patterns.NewPatternTokenBuilder().Token("aus").SetSkip(3).Build(),
		patterns.Token("heraus"),
		patterns.Token("zu"),
	},
}
