package de

// Code generated from GermanSpellerRule.ADDITIONAL_SUGGESTIONS exact put() entries.
// Regexp-based ADDITIONAL_SUGGESTIONS patterns are not included here.

// additionalSuggestionsExact maps misspelling → curated replacements (exact key match).
var additionalSuggestionsExact = map[string][]string{
	"Abbrechung": {"Abbruch"},
	"Abbrechungen": {"Abbrüche", "Abbrüchen"},
	"Abe": {"Aber", "Ab", "ABE", "Aue"},
	"Adon": {"Add-on"},
	"Adons": {"Add-ons"},
	"Aendert": {"Ändert"},
	"Akteures": {"Akteurs"},
	"Aku": {"Akku"},
	"Ala": {"À la"},
	"Aliegen": {"Anliegen", "Fliegen"},
	"Allalei": {"Allerlei"},
	"Alternatief": {"Alternativ"},
	"Altersheimer": {"Alzheimer"},
	"Amalgane": {"Amalgame"},
	"Analysierung": {"Analyse"},
	"Anbeot": {"Angebot"},
	"Anfage": {"Anfrage", "Anlage"},
	"Angehensweise": {"Vorgehensweise"},
	"Angehensweisen": {"Vorgehensweisen"},
	"Anschovis": {"Anchovis"},
	"Artal": {"Ahrtal"},
	"Arzte": {"Ärzte", "Arzt"},
	"Arzten": {"Ärzten"},
	"As": {"Ass"},
	"Aufm": {"Auf dem", "Auf einem", "Auf"},
	"Aufn": {"Auf den", "Auf einen", "Auf"},
	"Aug": {"Aug.", "Auge"},
	"Ausage": {"Aussage"},
	"Auschluss": {"Ausschluss"},
	"Ausm": {"Aus dem", "Aus einem", "Aus"},
	"Barcadi": {"Bacardi"},
	"Begierigkeit": {"Begierde"},
	"Begierigkeiten": {"Begehrlichkeiten"},
	"Behauptungsthese": {"Behauptung"},
	"Bekennung": {"Bekenntnis"},
	"Beleidung": {"Beleidigung"},
	"Bestellerurkunde": {"Bestellungsurkunde"},
	"Bestellungsdaten": {"Bestelldaten"},
	"Biite": {"Bitte"},
	"Bingerloch": {"Binger Loch"},
	"Bite": {"Bitte"},
	"Bitet": {"Bittet"},
	"Bitt": {"Bitte", "Bett", "Bist"},
	"Biß": {"Biss"},
	"Blat": {"Blatt", "Blut", "Bald", "Bat"},
	"BluRay": {"Blu-ray"},
	"Bole": {"Bowle"},
	"Bonnerstra(ß|ss)e": {"Bonner Straße"},
	"Boomerang": {"Bumerang"},
	"Boomerangs": {"Bumerangs"},
	"Bowl": {"Bowle"},
	"Bravur": {"Bravour"},
	"Briese": {"Brise"},
	"Brotwürfelcro[uû]tons": {"Croûtons"},
	"Bs": {"Bis"},
	"Budge": {"Budget"},
	"Bäckei": {"Bäckerei"},
	"Bäckeien": {"Bäckereien"},
	"Büff?(ee|é)": {"Buffet", "Büfett"},
	"Campagne": {"Kampagne"},
	"Campagnen": {"Kampagnen"},
	"Cand(el|le)lightdinner": {"Candle-Light-Dinner"},
	"Chr": {"Chr."},
	"Copyride": {"Copyright"},
	"Cr[eèé]me-?fra[iî]che": {"Crème fraîche"},
	"D[eèé]ja-?[vV]o?ue?": {"Déjà-vu"},
	"Dak": {"Dank", "Das", "Dock"},
	"Dake": {"Danke"},
	"Dammbock": {"Dambock", "Rammbock"},
	"Dammhirsch": {"Damhirsch"},
	"Danl": {"Dank"},
	"Dark[Ww]eb": {"Darknet"},
	"Datein": {"Dateien"},
	"Definierung": {"Definition"},
	"Definierungen": {"Definitionen"},
	"Defribilator": {"Defibrillator"},
	"Defribilatoren": {"Defibrillatoren"},
	"Deis": {"Dies"},
	"Dez": {"Dez.", "Der"},
	"Di": {"Du", "Die", "Di.", "Der", "Den"},
	"Disastern": {"Desastern"},
	"Durfüh?rung": {"Durchführung"},
	"Dutzen": {"Duzen", "Dutzend"},
	"E-Mal": {"E-Mail"},
	"E-Mals": {"E-Mails"},
	"E-Maul": {"E-Mail"},
	"E-Mauls": {"E-Mails"},
	"E-mail": {"E-Mail"},
	"Ehrenamtpauschale": {"Ehrenamtspauschale"},
	"Einzigst": {"Einzig"},
	"Emai": {"E-Mail"},
	"Emal": {"E-Mail"},
	"Emall?iearbeit": {"Emaillearbeit"},
	"Energiesparung": {"Energieeinsparung", "Energieersparnis"},
	"Entäuschung": {"Enttäuschung"},
	"Entäuschungen": {"Enttäuschungen"},
	"Eon": {"Ein", "E.ON", "Von"},
	"Erbung": {"Vererbung", "Erbschaft"},
	"Erhlich": {"Ehrlich"},
	"Erstsemesterin": {"Erstsemester", "Erstsemesters", "Erstsemesterstudentin"},
	"Erstsemesterinnen": {"Erstsemesterstudentinnen", "Erstsemester", "Erstsemestern"},
	"Essenzubereitung": {"Essenszubereitung"},
	"Ethnocid": {"Ethnozid"},
	"Ettiket": {"Etikett"},
	"Exam": {"Examen"},
	"Exams": {"Examens"},
	"Exel": {"Excel"},
	"Exikose": {"Exsikkose"},
	"Express": {"Express.js"},
	"Fairnis": {"Fairness"},
	"Fals": {"Falls"},
	"Feb": {"Feb.", "Web", "Pep", "Geb", "Gäb"},
	"Filterbubble": {"Filterblase"},
	"Filterbubbles": {"Filterblasen"},
	"Formulares": {"Formulars"},
	"Freiwilligerin": {"Freiwillige"},
	"Fritöse": {"Fritteuse"},
	"Frohndiensts": {"Frondiensts"},
	"Frotté": {"Frottee"},
	"Funieres": {"Furniers"},
	"Fußgängerunterwegs?": {"Fußgängerunterführung"},
	"Gallop": {"Galopp"},
	"Gedaken": {"Gedanken"},
	"Geerte": {"geehrte"},
	"Geldmachung": {"Geltendmachung", "Geldmacherei"},
	"Genehmigerablauf": {"Genehmigungsablauf"},
	"Geraet": {"Gerät"},
	"Geraete": {"Geräte"},
	"Geraeten": {"Geräten"},
	"Geraets": {"Geräts"},
	"Gerelaunch(ed|t)": {"Relauncht"},
	"Germanistiker[ns]": {"Germanisten"},
	"Geräuch": {"Geräusch", "Gesträuch"},
	"Geschnek": {"Geschenk", "Geschmack"},
	"Geschumpfen": {"Geschimpft"},
	"Gesochse": {"Gesocks"},
	"Getrixe": {"Getrickse"},
	"Gewebtrauma": {"Gewebetrauma"},
	"Ghanesen?": {"Ghanaer"},
	"Gibs": {"Gib es", "Gibst", "Gips"},
	"Gladbeckerstrasse": {"Gladbecker Straße"},
	"Glücklichkeit": {"Glück"},
	"Grisli": {"Grizzly"},
	"Grislibär": {"Grizzlybär"},
	"Grislibären": {"Grizzlybären"},
	"Grrösse": {"Größe"},
	"Gutan": {"Gut an", "Guten", "Sudan"},
	"Gutn": {"Guten"},
	"Gym": {"Fitnessstudio", "Gymnasium"},
	"Gyms": {"Fitnessstudios", "Gymnasiums"},
	"Hasue": {"Haus"},
	"Hats": {"Hat es", "Hast", "Hat"},
	"Hautreinheiten": {"Hautunreinheiten"},
	"Herliche": {"Herzliche", "Ehrliche", "Herrliche"},
	"Herlichen": {"Herzlichen", "Ehrlichen", "Herrlichen"},
	"Hijab": {"Hidschāb"},
	"Hinduist": {"Hindu"},
	"Hinduisten": {"Hindus"},
	"Hollundern": {"Holundern"},
	"Hoody": {"Hoodie"},
	"Hoodys": {"Hoodies"},
	"Hst": {"Hast", "Ist", "Hat"},
	"Humuspaste": {"Hummuspaste"},
	"Hungen": {"Hunger", "Hungern"},
	"Hälst": {"Hältst"},
	"Hänchen": {"Hähnchen", "Hänschen"},
	"Händy": {"Handy"},
	"Hühne": {"Bühne", "Hüne", "Hühner"},
	"Hühnen": {"Bühnen", "Hünen", "Hühnern"},
	"Ih": {"Ich", "In", "Im", "Ah"},
	"Ihc": {"Ich", "Ihr", "Ihm"},
	"Ihen": {"Ihren", "Ihnen", "Ihn", "Iren"},
	"Iher": {"Ihre", "Ihr"},
	"Ihrerer": {"Ihrer"},
	"Ihrn": {"Ihren"},
	"Impflicht": {"Impfpflicht"},
	"Importation": {"Import"},
	"Innzahlung": {"In Zahlung", "in Zahlung"},
	"Interdeterminismus": {"Indeterminismus"},
	"Investion": {"Investition"},
	"Jockei": {"Jockey"},
	"Joga": {"Yoga"},
	"Jun": {"Jun."},
	"Kafe": {"Kaffee", "Café"},
	"Kalvinismus": {"Calvinismus"},
	"Kandarren": {"Kandaren"},
	"Kanst": {"Kannst"},
	"Ketschup": {"Ketchup"},
	"Keywort": {"Keyword", "Stichwort"},
	"Keyworts": {"Keywords", "Stichworts"},
	"Keywörter": {"Keywords", "Stichwörter"},
	"Kilimand?jaro": {"Kilimandscharo"},
	"Klappts": {"Klappt’s", "Klappt es", "Klappst"},
	"Kollier": {"Collier"},
	"Kolliers": {"Colliers"},
	"Kommunikee": {"Kommuniqué"},
	"Kompanten": {"Kompasse", "Kompassen"},
	"Komplexheit": {"Komplexität"},
	"Komplexibilität": {"Komplexität"},
	"Kono": {"Kino", "Kongo", "Konto"},
	"Konzeptierung": {"Konzipierung"},
	"Kovult": {"Konvolut"},
	"Krankenhausen": {"Krankenhäusern", "Krankenhäuser"},
	"Krankenheit": {"Krankheit"},
	"Krankenheiten": {"Krankheiten"},
	"Kreativlosigkeit": {"Unkreativität"},
	"Kriese": {"Krise", "Kreise"},
	"Kriesen": {"Krisen", "Kreisen"},
	"Kruks": {"Krux"},
	"Kuden": {"Kunden"},
	"Kundein": {"Kundin"},
	"Kücken": {"Rücken", "Küken"},
	"Laola": {"La-Ola", "Paola", "Layla", "Lala"},
	"Laolas": {"La-Olas", "Paolas", "Laylas"},
	"Latin": {"Latein"},
	"Lexion": {"Lexikon"},
	"Lg": {"LG", "Liebe Grüße"},
	"Lia(si|is)onen": {"Liaisons"},
	"Liben": {"Lieben", "Leben", "Libyen", "Ligen"},
	"MWST": {"MwSt"},
	"Mainzerstrasse": {"Mainzer Straße"},
	"Makieren": {"Markieren"},
	"Mamma": {"Mama"},
	"Margarite": {"Margerite"},
	"Matrikelnr.": {"Matrikel-Nr."},
	"Mei": {"Mai", "Bei", "Sei", "Mein"},
	"Meien": {"Meine", "Meinen", "Mein", "Medien"},
	"Meinste": {"Meiste", "Feinste", "Meinte", "Meinst du"},
	"Meschen": {"Menschen"},
	"Messy": {"Messie"},
	"Mien": {"Mein", "Wien", "Miene"},
	"Migrationspackt": {"Migrationspakt"},
	"Mio": {"Mio."},
	"Mitgliederinnen": {"Mitglieder", "Mitgliedern"},
	"Modelles": {"Modells"},
	"Mogen": {"Mögen", "Morgen", "Zogen"},
	"Monatg": {"Montag", "Monate", "Monats"},
	"Motor-Flugzeug": {"Motorflugzeug"},
	"Motor-Flugzeuge": {"Motorflugzeuge"},
	"Motor-Flugzeugen": {"Motorflugzeugen"},
	"Motor-Flugzeugs": {"Motorflugzeugs"},
	"Mouseclick": {"Mausklick"},
	"Mousepad": {"Mauspad"},
	"Mousepads": {"Mauspads"},
	"Mysql": {"MySQL"},
	"Mü": {"My"},
	"Müllhalte": {"Müllhalde"},
	"Nabend": {"'n Abend"},
	"Negligee": {"Negligé"},
	"Nessessär": {"Necessaire"},
	"Neudefinierung": {"Neudefinition"},
	"Neugierigkeit": {"Neugier", "Neugierde"},
	"Nich": {"Nicht", "Noch"},
	"NodeJS": {"Node.js"},
	"Oke": {"Okay"},
	"Opelarena": {"Opel Arena"},
	"Orga": {"Organisation"},
	"Orgas": {"Organisationen"},
	"Oster": {"Ostern", "Osten"},
	"Package": {"Paket"},
	"Pakur": {"Parcours", "Parkuhr"},
	"Paleten": {"Paletten"},
	"Pann?acott?a": {"Panna cotta"},
	"Parter": {"Partner"},
	"Pearl-Harbou?r": {"Pearl Harbor"},
	"Permanent-Make-Up": {"Permanent-Make-up"},
	"Phyrr?ussieg": {"Pyrrhussieg"},
	"Phyton": {"Python"},
	"Pinn": {"Pin", "PIN"},
	"Pkt": {"Pkt.", "Pakt", "Punkt", "Akt"},
	"Polover": {"Pullover"},
	"Porto?folien": {"Portfolios"},
	"Präse": {"Präsentation"},
	"Präsen": {"Präsentationen"},
	"Re[kc]amiere": {"Récamière"},
	"Rechtspruch": {"Rechtsspruch"},
	"Rechtsschreibreformen": {"Rechtschreibreformen"},
	"Refelektion": {"Reflexion"},
	"Refelektionen": {"Reflexionen"},
	"Referenz-Nr": {"Referenz-Nr."},
	"Registration": {"Registrierung"},
	"Registrationen": {"Registrierungen"},
	"Reinfolge": {"Reihenfolge"},
	"Rekrutings?prozess": {"Recruitingprozess"},
	"Reorga": {"Reorganisation"},
	"Reorgas": {"Reorganisationen"},
	"Revisionierung": {"Revision"},
	"Rollade": {"Rollladen", "Roulade"},
	"Roulett": {"Roulette"},
	"Rämchen": {"Rähmchen"},
	"Rückrad": {"Rückgrat"},
	"Sachs?en-Anhal?t": {"Sachsen-Anhalt"},
	"Schalottenburg": {"Charlottenburg"},
	"Schertz": {"Scherz"},
	"Schicks": {"Schick’s", "Schick es", "Schickst"},
	"Schloß": {"Schloss"},
	"Schonvermögengrenze": {"Schonvermögensgrenze"},
	"Schutzfließ": {"Schutzvlies"},
	"Schwitch": {"Switch"},
	"Second-Hand": {"Secondhand"},
	"Selbstmitleidigkeit": {"Selbstmitleid"},
	"Seminarbeit": {"Seminararbeit"},
	"Seminarbeiten": {"Seminararbeiten"},
	"Seminares": {"Seminars"},
	"Sep": {"Sept.", "Sepp", "September", "Separator", "Sei"},
	"Sept": {"Sept."},
	"Serh": {"Sehr"},
	"Shr": {"Sehr", "Ihr", "Uhr", "Sir"},
	"Simlock": {"SIM-Lock"},
	"Singel": {"Single"},
	"Smilies": {"Smileys"},
	"Soda-Stream": {"SodaStream"},
	"Soda-Streams": {"SodaStreams"},
	"Sodastream": {"SodaStream"},
	"Sodastreams": {"SodaStreams"},
	"Spinnenweben": {"Spinnweben"},
	"Spß": {"Spaß"},
	"Staatsexam": {"Staatsexamen"},
	"Staatsexams": {"Staatsexamens"},
	"Standart": {"Standard", "Standort"},
	"Standbay": {"Stand-by"},
	"Stationskrankenpflegerin": {"Stationsschwester"},
	"Stop": {"Stopp"},
	"Studen": {"Stunden"},
	"Studiumplatzt?": {"Studienplatz"},
	"Subvestitionen": {"Subventionen"},
	"Sunden": {"Sünden", "Stunden", "Kunden"},
	"SwatchGroup": {"Swatch Group"},
	"Tankungen": {"Betankungen", "Tankvorgänge"},
	"Teammitgliederinnen": {"Teammitgliedern", "Teammitglieder"},
	"Teilnehmung": {"Teilnahme"},
	"Teilnehmungen": {"Teilnahmen"},
	"Telefones": {"Telefons"},
	"Thanks": {"Danke"},
	"Theam": {"Thema", "Team"},
	"Themabereich": {"Themenbereich"},
	"Thumberg": {"Thunberg"},
	"Tiefbaumt": {"Tiefbauamt"},
	"Toll-Collect": {"Toll Collect"},
	"Topfen": {"Tropfen"},
	"Treibel": {"Tribal"},
	"Tret": {"Tritt", "Trete", "Trat"},
	"Tütü": {"Tutu"},
	"Unnanehmigkeit": {"Unannehmlichkeit"},
	"Unorganisation": {"Desorganisation", "Unorganisiertheit"},
	"Unwohlbefinden": {"Unwohlsein"},
	"Urteilung": {"Urteil", "Verurteilung"},
	"Varietee": {"Varieté"},
	"Varietees": {"Varietés"},
	"Verschiden": {"Verschieden"},
	"Verwahrlosigkeit": {"Verwahrlosung"},
	"Vieleicht": {"Vielleicht"},
	"Vorraus": {"Voraus"},
	"Wandalismus": {"Vandalismus"},
	"Wandererin": {"Wanderin"},
	"Wasn": {"Was denn", "Was ein", "Was"},
	"Weinverköstigung": {"Weinverkostung"},
	"Werksresett": {"Werksreset"},
	"Wi-?Fi-Dire[ck]t": {"Wi-Fi Direct"},
	"Wi[Ff]i-Router": {"Wi-Fi-Router"},
	"Wiederstandes": {"Widerstandes"},
	"Win": {"Windows"},
	"Wiso": {"Wieso"},
	"Wissbegierigkeit": {"Wissbegier", "Wissbegierde"},
	"Wochendruhezeiten": {"Wochenendruhezeiten"},
	"Wur": {"Wir", "Zur", "War", "Nur"},
	"Zombiefizierungen": {"Zombifizierungen"},
	"[Bb]aldmöglich": {"baldmöglichst"},
	"[Bb]rudi": {"Bruder"},
	"[Ee][Ss]ports": {"E-Sports"},
	"[Ii]nspruchnahme": {"Inanspruchnahme"},
	"[Nn]umber": {"Nummer"},
	"[Rr]eviewing": {"Review"},
	"[Ss]chalge": {"schlage"},
	"[Ss]chalgen": {"schlagen"},
	"[Tt]uneup": {"TuneUp"},
	"[aA]ktuelli?esie?rung": {"Aktualisierung"},
	"[aA]lterego": {"Alter Ego"},
	"[aA]lterschbeschränkung": {"Altersbeschränkung"},
	"[aA]ngagemon": {"Engagement"},
	"[aA]nligen": {"Anliegen"},
	"[aA]nn?[ou]ll?ie?rung": {"Annullierung"},
	"[aA]nung": {"Ahnung"},
	"[aA]nwesenzeiten": {"Anwesenheitszeiten"},
	"[aA]petitt": {"Appetit"},
	"[aA]r?th?rie?th?is": {"Arthritis"},
	"[aA]rr?an?gemont": {"Arrangement"},
	"[aA]uthenzität": {"Authentizität"},
	"[aA]utonomität": {"Autonomie"},
	"[aA]wa": {"AWA", "ach was", "aber"},
	"[bB]equemheit": {"Bequemlichkeit"},
	"[bB]erücksichtung": {"Berücksichtigung"},
	"[bB]esichtung": {"Besichtigung"},
	"[bB]i[sß](s?[ij]|ch)en": {"bisschen"},
	"[bB]o[yi]kutierung": {"Boykottierung"},
	"[bB]oxhorn": {"Bockshorn"},
	"[bB]range": {"Branche"},
	"[cC]asemana?ge?ment": {"Case Management"},
	"[cC]hangse": {"Chance"},
	"[cCkK]ontener": {"Container"},
	"[dD]epp?risonen": {"Depressionen"},
	"[dD]eutsche?sprache": {"deutsche Sprache"},
	"[dD]iseing?": {"Design"},
	"[eE]inbu(ss|ß)ung": {"Einbuße"},
	"[eE]inbu(ss|ß)ungen": {"Einbußen"},
	"[eE]infühlvermögen": {"Einfühlungsvermögen"},
	"[eE]iskrem": {"Eiscreme"},
	"[eE]mphatie": {"Empathie"},
	"[eE]ngangment": {"Engagement"},
	"[eE]ntercott?e": {"Entrecôte"},
	"[eE]rartens": {"Erachtens"},
	"[eE]rledung": {"Erledigung"},
	"[eE]rwachtung": {"Erwartung"},
	"[eEäÄ]klerung": {"Erklärung"},
	"[fF]leißigkeit": {"Fleiß"},
	"[fF]lüchtung": {"Flucht"},
	"[fF]ormalisation": {"Formalisierung"},
	"[fF]r[uü]h?st[uü]c?k": {"Frühstück"},
	"[fF]rühstücksb[uü]ff?(é|ee)": {"Frühstücksbuffet"},
	"[fF]uss?ill?ien": {"Fossilien"},
	"[gG]eborgsamkeit": {"Geborgenheit"},
	"[gG]ebrauchss?puhren": {"Gebrauchsspuren"},
	"[gG]ebrauspuren": {"Gebrauchsspuren"},
	"[gG]eizigkeit": {"Geiz"},
	"[hH]ell?owi[eh]?n": {"Halloween"},
	"[hH]erausfor?dung": {"Herausforderung"},
	"[hH]erstammung": {"Abstammung"},
	"[hH]ifi": {"Hi-Fi"},
	"[hH]irar?chie": {"Hierarchie"},
	"[hH]udd[yi]": {"Hoodie"},
	"[hH]ähme": {"Häme"},
	"[iI]dentifierung": {"Identifikation"},
	"[iI]ngini?eue?r": {"Ingenieur"},
	"[iI]nstall?atör": {"Installateur"},
	"[iI]nstergramm?": {"Instagram"},
	"[iI]ntranzparentheit": {"Intransparenz"},
	"[iI]ntuion": {"Intuition"},
	"[iIüÜuU]b[ea]w[ae]isung": {"Überweisung"},
	"[jJ]ahundert": {"Jahrhundert"},
	"[kK]affeeteria": {"Cafeteria"},
	"[kK]affeeterien": {"Cafeterien"},
	"[kK]aos": {"Chaos"},
	"[kK]autsch": {"Couch"},
	"[kK]onn?ekt?schen": {"Connection"},
	"[kK]ostarika": {"Costa Rica"},
	"[kK]ostarikas": {"Costa Ricas"},
	"[kK]unstoff": {"Kunststoff"},
	"[lL]eerequiment": {"Leerequipment"},
	"[lL]eichtah?tleh?t": {"Leichtathlet"},
	"[lL]ieradd?ress?e": {"Lieferadresse"},
	"[lL]ymph?trie?nasche": {"Lymphdrainage"},
	"[mM]ayonaisse": {"Mayonnaise"},
	"[mM]edikamentation": {"Medikation"},
	"[mM]enegment": {"Management"},
	"[mM]issionarie?sie?rung": {"Missionierung"},
	"[mM]itag": {"Mittag"},
	"[mM]iteillung": {"Mitteilung"},
	"[mM]otorisation": {"Motorisierung"},
	"[nN][ei]gliche": {"Negligé"},
	"[nN]ah?richt": {"Nachricht"},
	"[nN]ah?richten": {"Nachrichten"},
	"[nN]or[dt]rh?einwest(f|ph)alen": {"Nordrhein-Westfalen"},
	"[oO]r?ganisazion": {"Organisation"},
	"[oO]rganisative": {"Organisation"},
	"[pP][qQ]-Formel": {"p-q-Formel"},
	"[pP]allete": {"Palette"},
	"[pP]appa": {"Papa"},
	"[pP]fane": {"Pfanne"},
	"[pP]okemon": {"Pokémon"},
	"[pP]reisnachlassung": {"Preisnachlass"},
	"[pP]u(zz|ss)el": {"Puzzle"},
	"[pP]upatät": {"Pubertät"},
	"[qQ]uicky": {"Quickie"},
	"[qQ]uickys": {"Quickies"},
	"[rR]eflektion": {"Reflexion"},
	"[rR]eschärsche": {"Recherche"},
	"[rR]eschärschen": {"Recherchen"},
	"[rR]evü": {"Revue"},
	"[sS]chanse": {"Chance"},
	"[sS]charm": {"Charme"},
	"[sS]chee?selonge?": {"Chaiselongue"},
	"[sS]chull?igung": {"Entschuldigung"},
	"[sS]chwie?ri?chkeiten": {"Schwierigkeiten"},
	"[sS]itwazion": {"Situation"},
	"[sS]peziellisierung": {"Spezialisierung"},
	"[sS]tandtart": {"Standard"},
	"[sS]tieft": {"Stift"},
	"[sS]äusche": {"Seuche"},
	"[tT]h?elepath?ie": {"Telepathie"},
	"[uU]nangeneh?mheiten": {"Unannehmlichkeiten"},
	"[uU]nangeneh?mlichkeiten": {"Unannehmlichkeiten"},
	"[uU]nreimlichkeiten": {"Ungereimtheiten"},
	"[uU]nstimm?ichkeiten": {"Unstimmigkeiten"},
	"[vV]erlu(ss|ß)t": {"Verlust"},
	"[vV]ollkommnung": {"Vervollkommnung"},
	"[vV]orgensweise": {"Vorgehensweise"},
	"[wW]ah?rscheindlichkeit": {"Wahrscheinlichkeit"},
	"[wW]ahts?app": {"WhatsApp"},
	"[wW]eh?wechen": {"Wehwehchen"},
	"[wW]elan": {"WLAN", "W-LAN"},
	"[wW]ischmöppen?": {"Wischmopps"},
	"[zZ]oolophie": {"Zoophilie"},
	"[zZ]ulaufror": {"Zulaufrohr"},
	"[üÜ]bergrifflichkeiten": {"Übergriffigkeiten"},
	"abbonement": {"Abonnement"},
	"abe": {"habe", "aber", "ab"},
	"abgeharkt": {"abgehakt", "abgehackt"},
	"abgekatertes": {"abgekartetes"},
	"abgeschaffen": {"abgeschafft"},
	"abrechen": {"abbrechen"},
	"abschiednehmen": {"Abschied nehmen"},
	"abzusolvieren": {"zu absolvieren"},
	"abzügl": {"abzgl"},
	"achtungslo[ßs]": {"achtlos"},
	"ads": {"das", "ADS", "Ads", "als", "aus"},
	"aendert": {"ändert"},
	"af": {"auf", "an", "an", "als"},
	"afarung": {"Erfahrung"},
	"aheb": {"habe", "aber"},
	"aich": {"ich", "auch", "sich", "eich"},
	"ala": {"à la"},
	"allmöglichen?": {"alle möglichen", "alle mögliche"},
	"amch": {"mach"},
	"amche": {"mache"},
	"anahme": {"Annahme", "nahmen", "nahe", "nahmen"},
	"ander": {"an der", "andere", "änder", "anders"},
	"angefangt": {"angefangen"},
	"angefordet": {"angefordert"},
	"angelügt": {"angelogen"},
	"angeruft": {"angerufen"},
	"angeschaffen": {"angeschafft"},
	"angeschriehen": {"angeschrien"},
	"anleigen": {"anlegen", "Anliegen", "anliegen", "anzeigen"},
	"anlässig": {"anlässlich"},
	"anschein[dt]": {"anscheinend"},
	"antuhen": {"antun"},
	"artzt?": {"Arzt"},
	"as": {"das"},
	"ass": {"Ass", "aß", "aus", "dass"},
	"aufgesteht": {"aufgestanden"},
	"aufgewägt": {"aufgewogen"},
	"aufgrundedessen": {"aufgrund dessen"},
	"aufm": {"auf dem", "auf einem", "auf"},
	"aufn": {"auf den", "auf einen", "auf"},
	"aufteil": {"aufteile", "aufteilt", "auf Teil"},
	"aufzeichen": {"aufzeichnen"},
	"augeschlossen": {"ausgeschlossen", "angeschlossen"},
	"auschluss": {"Ausschluss", "Ausschuss"},
	"auschreibung": {"Ausschreibung"},
	"ausgeboten": {"ausgebootet"},
	"ausm": {"aus dem", "aus einem", "aus"},
	"ausprache": {"Aussprache"},
	"austehenden": {"ausstehenden"},
	"austellen": {"ausstellen"},
	"aüßerst": {"äußerst"},
	"bachten": {"brachten", "beachten", "machten", "pachten"},
	"befehlte": {"befahl"},
	"befehlten": {"befahlen"},
	"beid": {"beide", "seid", "beim", "bei"},
	"bein": {"Bein", "beim", "ein", "bei"},
	"beinhielt": {"beinhaltete"},
	"beinhielten": {"beinhalteten"},
	"beinhält": {"beinhaltet"},
	"beiten": {"beiden", "bieten"},
	"bekomms": {"bekomm es"},
	"bekommste": {"bekommst du", "bekommst"},
	"beliebn": {"beliebt", "bleiben", "belieben"},
	"ber": {"über", "per", "der", "BER"},
	"beratete": {"beriet"},
	"berücksicht": {"berücksichtigt"},
	"berüht": {"berühmt", "berührt", "bemüht"},
	"bescheid?t": {"Bescheid"},
	"besproch": {"besprach", "besprich", "bespreche", "besprochen"},
	"bess?tetigung": {"Bestätigung"},
	"best": {"beste", "bester", "Best"},
	"bestellun": {"Bestellung"},
	"beu": {"bei", "peu", "neu"},
	"bevorzugs": {"bevorzugst"},
	"bezuggenommen": {"Bezug genommen"},
	"bezweifel": {"bezweifle"},
	"bi": {"bei"},
	"biiten": {"bitten"},
	"bim": {"bin", "im", "bis", "beim"},
	"bissl": {"bissel", "bisserl"},
	"bits": {"bist", "bis", "Bits"},
	"bittete": {"bat"},
	"bizte": {"bitte"},
	"brache": {"brauche", "brachte", "brach", "bräche"},
	"bratete": {"briet"},
	"brateten": {"brieten"},
	"brauchts": {"braucht es", "brauchst", "braucht"},
	"bruchen": {"brauchen", "brachen", "brechen"},
	"bs": {"bis"},
	"bst": {"bist", "ist"},
	"ccm": {"cm³"},
	"check": {"checke"},
	"chouch": {"Couch"},
	"dagen": {"sagen"},
	"dake": {"danke"},
	"dan": {"dann", "den", "das", "an"},
	"darn": {"daran", "darin", "dann", "dar"},
	"dastellen": {"darstellen"},
	"daum": {"da um", "darum", "kaum", "Raum"},
	"daß": {"dass"},
	"dea": {"der", "den", "des", "dem"},
	"deien": {"deine", "dein"},
	"denks": {"denkst", "denkt", "denke", "denk"},
	"derikter": {"direkter", "Direktor"},
	"desweitere?m": {"des Weiteren"},
	"di": {"du", "die", "Di.", "der", "den"},
	"dienem": {"deinem"},
	"dier": {"dir"},
	"dilettant": {"Dilettant", "dilettantisch"},
	"dis": {"die", "dies"},
	"dnn": {"dann", "denn", "den"},
	"dos": {"das", "des", "DOS", "DoS"},
	"drinen": {"drinnen"},
	"ds": {"des", "das", "es"},
	"dunkellilane[mnrs]?": {"dunkellila"},
	"ech": {"euch", "ich"},
	"ect": {"etc"},
	"eh?rgeit?z": {"Ehrgeiz"},
	"ehr": {"eher", "mehr", "sehr", "er"},
	"eie": {"die", "wie", "eine", "sie"},
	"eien": {"eine"},
	"eigl": {"eigtl"},
	"ein[ua]ndhalb": {"eineinhalb"},
	"einamen": {"Einnahmen"},
	"eingelogt": {"eingeloggt"},
	"eingepeilt": {"angepeilt"},
	"eingetragt": {"eingetragen"},
	"eingänglich": {"eingangs"},
	"einhaltest": {"einhältst"},
	"einhergend": {"einhergehend"},
	"einlogen": {"einloggen"},
	"einpar": {"ein paar"},
	"einzigst": {"einzig"},
	"einzulogen": {"einzuloggen", "einzulegen"},
	"elektrität": {"Elektrizität"},
	"em?men[sz]": {"immens"},
	"entchuldigen": {"entschuldigen"},
	"entäscht": {"enttäuscht"},
	"erhaltete": {"erhielt"},
	"erlas": {"Erlass"},
	"erledigigung": {"Erledigung"},
	"erzeiht": {"erzieht", "verzeiht"},
	"fangte": {"fing"},
	"fangten": {"fingen"},
	"fargen": {"fragen"},
	"femist": {"vermisst"},
	"fernsehgucken": {"fernsehen", "Fernsehen gucken"},
	"fithälst": {"fit hältst"},
	"fleicht": {"vielleicht"},
	"folgendermassen": {"folgendermaßen"},
	"forfahren": {"fortfahren"},
	"fr": {"für"},
	"fregen": {"fragen"},
	"fress": {"friss"},
	"frug": {"fragte"},
	"frägst": {"fragst"},
	"funktionierts": {"funktioniert es"},
	"fäschungen": {"Fälschungen"},
	"fürn": {"für ein", "für den", "für", "fürs", "fern"},
	"ganichts": {"gar nichts"},
	"gans": {"ganz"},
	"garnichtmehr": {"gar nicht mehr"},
	"gaz": {"ganz", "gab"},
	"geauessert": {"geäußert"},
	"geb": {"gebe"},
	"gebittet": {"gebeten"},
	"gebs": {"gebe es"},
	"gebten": {"gebeten", "gaben", "geboten", "gelten"},
	"gechickt": {"geschickt", "gecheckt"},
	"geduld": {"Geduld", "gedulde"},
	"geeehrte": {"geehrte"},
	"geeehrter": {"geehrter"},
	"geerhte": {"geehrte"},
	"geerte": {"geehrte"},
	"geerthe": {"geehrte"},
	"gefahl": {"gefiel"},
	"gefaked": {"gefakt"},
	"gefiels": {"gefielt es"},
	"gefielts": {"gefielt es"},
	"gefäh?te": {"Gefährte"},
	"gefäh?ten": {"Gefährten"},
	"gefällts": {"gefällt es"},
	"gegehen": {"gegangen"},
	"gehn": {"gehen"},
	"gehör": {"gehört", "Gehör", "gehöre"},
	"geklabt": {"geklappt"},
	"geknappst": {"geknapst"},
	"gekommt": {"gekommen"},
	"gekricht": {"gekriegt"},
	"gekukt": {"geguckt"},
	"gekänzelt": {"gecancelt"},
	"geleased": {"geleast"},
	"gelessen": {"gelesen"},
	"geliegt": {"gelegen"},
	"geläscht": {"gelöscht"},
	"genißen": {"genießen"},
	"genzut": {"genutzt"},
	"gepart": {"gespart", "gepaart"},
	"gerelaunch(ed|t)": {"relauncht"},
	"geren": {"gegen", "gerne", "gären"},
	"gerner": {"gern", "gern er", "ferner"},
	"geschied": {"geschieht"},
	"geschlaffen": {"geschlafen", "geschaffen", "geschliffen"},
	"geschmelt?zt": {"geschmolzen"},
	"geschriehen": {"geschrien"},
	"geschumpfen": {"geschimpft"},
	"gesen": {"gesehen"},
	"gesich": {"Gesicht"},
	"gester": {"gestern"},
	"gestigen": {"gestiegen"},
	"gestrest": {"gestresst"},
	"gestyled": {"gestylt"},
	"gesynced": {"synchronisiert"},
	"gesyncht": {"synchronisiert"},
	"gesynct": {"synchronisiert"},
	"gesyngt": {"synchronisiert"},
	"gesäht": {"gesät"},
	"getrunkt": {"getrunken"},
	"getäucht": {"getäuscht"},
	"geupdate[dt]$": {"upgedatet"},
	"gewertschätzt": {"wertgeschätzt"},
	"gewunschen": {"gewünscht"},
	"gibs": {"gib es", "gibst"},
	"gie?bts": {"gibt's"},
	"giept": {"gibt"},
	"gildet": {"gilt"},
	"git": {"gut", "gibt", "gilt", "mit"},
	"glass": {"Glas"},
	"gleitete": {"glitt"},
	"gleiteten": {"glitten"},
	"glückigerweise": {"glücklicherweise"},
	"grad": {"grade", "Grad", "gerade"},
	"guterletzt": {"guter Letzt"},
	"gutn": {"guten"},
	"gäng": {"ging", "gang"},
	"handzuhaben": {"zu handhaben"},
	"hats": {"hat es", "hast", "hat"},
	"hbat": {"habt"},
	"heilwegs": {"halbwegs"},
	"helfte": {"half"},
	"helften": {"halfen"},
	"helllilane[mnrs]?": {"helllila"},
	"hendis": {"Handys"},
	"herlich": {"ehrlich", "herrlich"},
	"herliche": {"herzliche", "ehrliche", "herrliche"},
	"herlichen": {"herzlichen", "ehrlichen", "herrlichen"},
	"herrunterladen": {"herunterladen"},
	"hilt": {"gilt", "hilft", "hielt", "hält"},
	"hinund?her": {"hin und her"},
	"hinweißen": {"hinweisen"},
	"hobb?ies": {"Hobbys"},
	"hst": {"hast", "ist", "hat"},
	"höstwah?rsch[ea]inlich": {"höchstwahrscheinlich"},
	"ic": {"ich"},
	"ichs": {"ich es"},
	"ih": {"ich", "in", "im", "ah"},
	"ihc": {"ich", "ihr", "ihm"},
	"ihne": {"ihn", "ihnen"},
	"iht": {"ihr"},
	"immenoch": {"immer noch"},
	"inbetracht": {"in Betracht"},
	"ind": {"und", "ins", "in", "sind"},
	"instande?zusetzen": {"instand zu setzen"},
	"intere": {"interne", "innere", "hintere", "untere"},
	"interen": {"interne"},
	"interrese": {"Interesse"},
	"ioch": {"ich"},
	"isser": {"ist er"},
	"isses": {"ist es", "Risses"},
	"it": {"ist", "IT", "in", "im"},
	"jez": {"jetzt"},
	"jeztz": {"jetzt"},
	"kaffe": {"Kaffee"},
	"kaltweis": {"kaltweiß"},
	"kanns": {"kann es", "kannst"},
	"kanst": {"kannst"},
	"kapput": {"kaputt"},
	"keinsten": {"keinen", "kleinsten"},
	"klappts": {"klappt’s", "klappt es", "klappst"},
	"klapt": {"klappt", "klagt"},
	"kniehen": {"knien"},
	"komen": {"kommen"},
	"kontest": {"konntest"},
	"korekkt": {"korrekt"},
	"krahn": {"Kran"},
	"kreigt": {"kriegt"},
	"krige": {"kriege", "krieg"},
	"kundne": {"Kunden"},
	"lad": {"lade"},
	"lage": {"lange", "Lage", "läge", "lache"},
	"lase": {"las", "lasse", "Nase"},
	"laufte": {"lief"},
	"lauften": {"liefen"},
	"legen[td]lich": {"lediglich"},
	"lehr": {"mehr", "lehrt", "sehr", "leer"},
	"leiben": {"lieben", "bleiben", "leben"},
	"leidete": {"litt"},
	"leideten": {"litten"},
	"leidetest": {"littest"},
	"leier": {"leider"},
	"leiwagen": {"Leihwagen"},
	"les": {"lese"},
	"letzdenendes": {"letzten Endes"},
	"letzens": {"letztens"},
	"letzt": {"letzte", "jetzt"},
	"liebs": {"liebe es", "liebes", "liebe"},
	"lieder": {"leider", "Lieder"},
	"liegts": {"liegt es"},
	"ligt": {"liegt"},
	"lädest": {"lädst"},
	"löchen": {"löschen", "löchern", "Köchen"},
	"lügte": {"log"},
	"lügten": {"logen"},
	"ma": {"mal"},
	"mags": {"mag es"},
	"mahte": {"Mathe"},
	"mak": {"mag", "mak", "lag"},
	"maletriert": {"malträtiert"},
	"malzeit": {"Mahlzeit"},
	"mch": {"mich", "ich", "ach"},
	"meien": {"meine", "mein", "meinen"},
	"meinste": {"meiste", "feinste", "meinte", "meinst du"},
	"mi": {"im", "mit", "mir"},
	"mirgen": {"morgen"},
	"misverstaendnis": {"Missverständnis"},
	"misverständniss": {"Missverständnis"},
	"mitgetielt": {"mitgeteilt"},
	"mn": {"man", "in", "an"},
	"mogen": {"morgen"},
	"momentmal": {"Moment mal"},
	"much": {"mich", "auch", "Buch"},
	"mur": {"mir", "zur", "nur", "für"},
	"must": {"musst"},
	"muter": {"Mutter"},
	"mächte": {"möchte", "Mächte"},
	"mächten": {"möchten"},
	"mägt": {"mögt"},
	"möchst": {"möchtest"},
	"nacher": {"nachher"},
	"nachichten": {"Nachrichten"},
	"nachvollzuziehe?n": {"nachzuvollziehen"},
	"ne": {"'ne", "eine", "nein", "oder"},
	"nehm": {"nimm"},
	"nei": {"bei", "nie", "ein", "neu"},
	"nem": {"'nem", "einem"},
	"nen": {"'nen", "einen"},
	"ner": {"einer"},
	"neune": {"neuen", "neue", "Neune"},
	"neunen": {"neuen", "neunten"},
	"neus": {"neues", "neue", "neu"},
	"neuse": {"neues", "neue"},
	"nich": {"nicht", "noch"},
	"nichtmals": {"nicht mal", "nicht einmal"},
	"nocheinmall": {"noch einmal"},
	"nocheinmals": {"noch einmal"},
	"nochnichtmals?": {"noch nicht einmal"},
	"nummer": {"Nummer"},
	"och": {"ich", "noch", "doch"},
	"of": {"oft"},
	"onlein": {"online"},
	"os": {"so", "es", "OS"},
	"packet": {"Paket"},
	"packs": {"pack es"},
	"passee": {"passé"},
	"past": {"passt"},
	"patien": {"Partien", "Patient"},
	"perse": {"per se"},
	"pitza": {"Pizza"},
	"popup": {"Pop-up"},
	"pr[eä]ventieren": {"verhindern"},
	"pr[eä]ventiert": {"verhindert"},
	"prozes": {"Prozess"},
	"rauch": {"Rauch", "rauche"},
	"rauschicken": {"rausschicken"},
	"released": {"releast"},
	"richen": {"riechen", "reichen", "richten"},
	"riesen": {"riesigen", "diesen", "Riesen", "reisen"},
	"rosane[mnrs]?$": {"rosa", "^rosan", "rosafarben"},
	"routiene": {"Routine"},
	"rückg[äe]nglich": {"rückgängig"},
	"satzt": {"Satz"},
	"schalfen": {"schlafen", "schaffen", "scharfen"},
	"scheibe": {"Scheibe", "schreibe"},
	"schein": {"scheine"},
	"schicks": {"schick’s", "schick es", "schickst"},
	"schlagte": {"schlug"},
	"schlagten": {"schlugen"},
	"schlie[sß]te": {"schloss"},
	"schlie[sß]ten": {"schlossen"},
	"schnells": {"schnell", "schnellst"},
	"schnäpchen": {"Schnäppchen"},
	"schuen": {"schauen"},
	"schöen": {"schönen", "schön"},
	"sehn": {"sehen"},
	"selblosigkeit": {"Selbstlosigkeit"},
	"senora": {"Señora"},
	"ser": {"der", "sehr", "er", "sei"},
	"serh": {"sehr"},
	"sevice": {"Service"},
	"sin": {"ein", "sind", "sie", "in"},
	"sm": {"am", "im", "am", "SM"},
	"sn": {"an", "in"},
	"soch": {"doch", "sich", "noch"},
	"soche": {"solche"},
	"solltes": {"solltest"},
	"sreiben": {"schreiben"},
	"staats?angehoe?rigkeit": {"Staatsangehörigkeit"},
	"stantepede": {"stante pede"},
	"start": {"Start", "stark", "statt", "stand"},
	"startup": {"Start-up"},
	"startups": {"Start-ups"},
	"stoniren": {"stornieren"},
	"strang": {"Strang", "strengte"},
	"sumarum": {"summarum"},
	"synce": {"synchronisiere"},
	"syncen": {"synchronisieren"},
	"synche": {"synchronisiere"},
	"synchen": {"synchronisieren"},
	"sähend": {"säend"},
	"säht": {"sät"},
	"sähte": {"säte"},
	"sähten": {"säten"},
	"sähtest": {"sätest"},
	"sähtet": {"sätet"},
	"tieger": {"Tiger"},
	"tip": {"Tipp"},
	"tiptop": {"tiptopp"},
	"todtkrank": {"todkrank"},
	"tole": {"tolle", "tote"},
	"tolen": {"tollen", "toten"},
	"totkrank": {"todkrank"},
	"tuh": {"tun", "tut", "tue", "Kuh"},
	"tuhe": {"tue"},
	"tuhen": {"tun"},
	"ud": {"und"},
	"umbennen": {"umbenennen"},
	"umstimigkeiten": {"Unstimmigkeiten"},
	"unann?äh?ml?ichkeiten": {"Unannehmlichkeiten"},
	"unauslässlich": {"unerlässlich", "unablässig", "unauslöschlich"},
	"under": {"unser", "unter"},
	"undsoweiter": {"und so weiter"},
	"unerkennlich": {"unkenntlich"},
	"unn?ann?ehmichkeiten": {"Unannehmlichkeiten"},
	"unsen": {"unseren"},
	"untergangen": {"untergegangen"},
	"unterscheid": {"Unterschied"},
	"unterschiede": {"Unterschiede", "unterscheide", "unterschiebe", "unterschieden"},
	"unterschiedet": {"unterscheidet"},
	"us": {"US", "aus"},
	"veil": {"viel", "weil", "teil"},
	"verate": {"verrate"},
	"veraten": {"verraten"},
	"verennt": {"verrennt"},
	"verhing": {"verhängte"},
	"verhingen": {"verhängten"},
	"verhälst": {"verhältst"},
	"verklinken": {"verklinkern", "verlinken", "verklingen"},
	"versand": {"versandt", "Versand"},
	"versichen": {"versichern"},
	"vertag": {"Vertrag"},
	"vertaggt": {"vertagt", "getaggt"},
	"verzweifel": {"verzweifle"},
	"veräht": {"verrät"},
	"verückt": {"verrückt"},
	"vie?d(er|a)sehen": {"wiedersehen"},
	"viedeo": {"Video"},
	"vielmal": {"Vielmal", "vielmals", "viermal", "viel mal"},
	"vieviel": {"wie viel"},
	"vileich": {"vielleicht"},
	"vll?t": {"vielleicht"},
	"vllt": {"vielleicht", "vllt."},
	"vn": {"von", "an", "in"},
	"voher": {"vorher", "woher", "hoher"},
	"vol": {"von", "vom", "voll", "vor"},
	"voralem": {"vor allem"},
	"vorbreiten": {"vorbereiten", "verbreiten"},
	"vorort": {"vor Ort"},
	"vorr?auss?etzlich": {"voraussichtlich", "vorausgesetzt"},
	"vs": {"vs."},
	"w[eä]hret": {"wäret"},
	"wanderen": {"wandern", "Wanderern"},
	"warheit": {"Wahrheit"},
	"warmweis": {"warmweiß"},
	"wars": {"war es", "warst"},
	"waser": {"Wasser"},
	"wat": {"was"},
	"weibt": {"weißt"},
	"weicheinlich": {"wahrscheinlich"},
	"weils": {"weil es"},
	"weiso": {"wieso"},
	"wergen": {"werfen", "werben", "werten"},
	"wertgelegt": {"Wert gelegt"},
	"widerholen": {"wiederholen"},
	"widerrum": {"wiederum"},
	"wie?daholung": {"Wiederholung"},
	"wie?derwarten": {"wider Erwarten"},
	"wiedererwarten": {"wider Erwarten"},
	"wiederfahren": {"widerfahren"},
	"wiederhohlen": {"wiederholen"},
	"wiederrum": {"wiederum"},
	"wiederspiegelt": {"widerspiegelt"},
	"wiederspiegelten": {"widerspiegelten"},
	"wiel": {"weil", "wie", "viel"},
	"wier": {"wie", "wir", "vier", "hier", "wer"},
	"wiessen": {"wissen", "weisen", "wiesen"},
	"wiet": {"weit", "wie"},
	"wil": {"will", "wie", "weil", "wir"},
	"woltest": {"wolltest"},
	"woltet": {"wolltet"},
	"worter": {"Wörter"},
	"wr": {"wir"},
	"wuden": {"wurden", "würden"},
	"wuerde": {"würde", "wurde"},
	"wuerden": {"würden", "wurden"},
	"wur": {"wir", "zur", "war", "nur"},
	"wuste": {"wusste"},
	"wusten": {"wussten", "wüsten"},
	"zeren": {"zerren", "zehren"},
	"zetel": {"Zettel"},
	"zucc?h?inis?": {"Zucchini"},
	"zugegebenerweise": {"zugegebenermaßen"},
	"zugesand": {"zugesandt"},
	"zur?verfügung": {"zur Verfügung"},
	"zuschafen": {"zu schaffen"},
	"zutun": {"zu tun"},
	"zuviel": {"zu viel"},
	"zweifel": {"zweifle"},
	"zwie": {"zwei", "wie", "sie", "sowie"},
	"Ärcker": {"Erker", "Ärger"},
	"ändenr": {"ändern"},
	"änderen": {"ändern", "anderen"},
	"öffen": {"öffnen", "offen"},
	"übergoogle": {"über Google"},
	"überhaut": {"überhaupt"},
	"überlasstet": {"überlastet", "überließt"},
	"übernohmen": {"übernehmen", "übernommen"},
	"überrant": {"überrannt"},
	"übersäht": {"übersät"},
	"übertr[äa]gte": {"übertrug"},
	"übertr[äa]gten": {"übertrugen"},
	"überweißt": {"überweist"},
	"überwendet": {"überwindet"},
	"überwhatsapp": {"über WhatsApp"},
	"überwissen": {"überwiesen"},
	"überzoom": {"über Zoom"},
	"übetragen": {"übertragen"},
	"übrings": {"übrigens"},
}

