package de

import (
	"regexp"
	"strings"

	"github.com/lucasew/lang/internal/languagetool/org/languagetool"
	"github.com/lucasew/lang/internal/languagetool/org/languagetool/rules"
)

// Ports getOnlySuggestions, filterNoSuggestWords, removeGenderCompoundMatches.

var lcDoNotSuggestWords = map[string]struct{}{
	"auschwitzmythos":   {},
	"entjuden":          {},
	"entjudet":          {},
	"entjudete":         {},
	"entjudetem":        {},
	"entjudeten":        {},
	"entjudeter":        {},
	"entjudetes":        {},
	"fotze":             {},
	"fotzen":            {},
	"judenfrei":         {},
	"judenfreie":        {},
	"judenfreiem":       {},
	"judenfreien":       {},
	"judenfreier":       {},
	"judenfreies":       {},
	"judenmord":         {},
	"judenmorden":       {},
	"judenmörder":       {},
	"judenrein":         {},
	"judenreine":        {},
	"judenreinem":       {},
	"judenreinen":       {},
	"judenreiner":       {},
	"judenreines":       {},
	"judensippe":        {},
	"judensippen":       {},
	"judensippschaft":   {},
	"judensippschaften": {},
	"möse":              {},
	"mösen":             {},
	"neger":             {},
	"negern":            {},
	"negers":            {},
	"nigger":            {},
	"niggern":           {},
	"niggers":           {},
	"rassejude":         {},
	"rassejuden":        {},
	"rassejüdin":        {},
	"rassejüdinnen":     {},
	"verjuden":          {},
	"verjudet":          {},
	"verjudetem":        {},
	"verjudeten":        {},
	"verjudeter":        {},
	"verjudetes":        {},
}

var onlySuggestionsExact = map[string]string{
	"Abschliessend":         "Abschließend",
	"Achso":                 "Ach so",
	"AirFrance":             "Air France",
	"Akkupressur":           "Akupressur",
	"Annektion":             "Annexion",
	"Annektionen":           "Annexionen",
	"Anschliessend":         "Anschließend",
	"Anstossbreite":         "Anstoßbreite",
	"AppStore":              "App Store",
	"AppStores":             "App Stores",
	"AppleStore":            "Apple Store",
	"AppleStores":           "Apple Stores",
	"Art-Nr":                "Art.-Nr.",
	"Au-Pair":               "Au-pair",
	"Au-Pairs":              "Au-pairs",
	"Ausser":                "Außer",
	"Ausserdem":             "Außerdem",
	"Außländer":             "Ausländer",
	"Außländerin":           "Ausländerin",
	"Außländerinnen":        "Ausländerinnen",
	"Außländern":            "Ausländern",
	"Außländers":            "Ausländers",
	"Baby-Phone":            "Babyfon",
	"Babyphone":             "Babyfon",
	"Besenstil":             "Besenstiel",
	"Bestwater":             "BestWater",
	"Bestwaters":            "BestWaters",
	"Billiard":              "Billard",
	"Blackfriday":           "Black Friday",
	"Blackfridays":          "Black Fridays",
	"Blackweek":             "Black Week",
	"Blackweeks":            "Black Weeks",
	"Bzgl":                  "Bzgl.",
	"Carplay":               "CarPlay",
	"Click":                 "Klick",
	"Clicks":                "Klicks",
	"Daß":                   "Dass",
	"Deluxe":                "de luxe",
	"Design-Op":             "Design-OP",
	"Di-Do":                 "Di.–Do.",
	"Di-Fr":                 "Di.–Fr.",
	"Di-Mi":                 "Di.–Mi.",
	"Di-Sa":                 "Di.–Sa.",
	"Di-So":                 "Di.–So.",
	"Dnake":                 "Danke",
	"Dnk":                   "Dank",
	"Do-Fr":                 "Do.–Fr.",
	"Do-Sa":                 "Do.–Sa.",
	"Do-So":                 "Do.–So.",
	"Eigtl":                 "Eigtl.",
	"Elfmeterschiessen":     "Elfmeterschießen",
	"EmailleOfen":           "Emailleofen",
	"Endgeld":               "Entgeld",
	"Entäuschung":           "Enttäuschung",
	"Entäuschungen":         "Enttäuschungen",
	"Facetime":              "FaceTime",
	"Facetimes":             "FaceTimes",
	"Feldschiessen":         "Feldschießen",
	"Flössgräben":           "Flößgräben",
	"Fr-Sa":                 "Fr.–Sa.",
	"Fr-So":                 "Fr.–So.",
	"Frauenhofer":           "Fraunhofer",
	"Gasterra":              "GasTerra",
	"Gasterras":             "GasTerras",
	"Gepaeck":               "Gepäck",
	"Ggf":                   "Ggf.",
	"Grüsse":                "Grüße",
	"Grüssen":               "Grüßen",
	"HAllo":                 "Hallo",
	"Heisst":                "Heißt",
	"Hobbies":               "Hobbys",
	"Huskies":               "Huskys",
	"Interresse":            "Interesse",
	"Interressen":           "Interessen",
	"Jedesmal":              "Jedes Mal",
	"Johannesbeere":         "Johannisbeere",
	"Johannesbeeren":        "Johannisbeeren",
	"Kuhdamm":               "Ku’damm",
	"Ladies":                "Ladys",
	"Languagetool":          "LanguageTool",
	"Languagetools":         "LanguageTools",
	"Lichtenstein":          "Liechtenstein",
	"Lichtensteins":         "Liechtensteins",
	"Lobbies":               "Lobbys",
	"Luxenburg":             "Luxemburg",
	"Luxenburgs":            "Luxemburgs",
	"Lybien":                "Libyen",
	"Lybiens":               "Libyens",
	"MWST":                  "MwSt.",
	"Mazel tov":             "Masel tov",
	"Mazeltov":              "Masel tov",
	"Mi-Do":                 "Mi.–Do.",
	"Mi-Fr":                 "Mi.–Fr.",
	"Mi-Sa":                 "Mi.–Sa.",
	"Mi-So":                 "Mi.–So.",
	"Mo-Di":                 "Mo.–Di.",
	"Mo-Do":                 "Mo.–Do.",
	"Mo-Fr":                 "Mo.–Fr.",
	"Mo-Mi":                 "Mo.–Mi.",
	"Mo-Sa":                 "Mo.–Sa.",
	"Mo-So":                 "Mo.–So.",
	"Muehe":                 "Mühe",
	"Muehen":                "Mühen",
	"Mußt":                  "Musst",
	"MwSt":                  "MwSt.",
	"Mwst":                  "MwSt",
	"Müßt":                  "Müsst",
	"Nagut":                 "Na gut",
	"Nestle":                "Nestlé",
	"Nestles":               "Nestlés",
	"Offensichtlicherweise": "Offensichtlich",
	"Parties":               "Partys",
	"Rechtshcreibfehler":    "Rechtschreibfehler",
	"Reflektion":            "Reflexion",
	"Reflektionen":          "Reflexionen",
	"Reisverschluss":        "Reißverschluss",
	"Reisverschlusses":      "Reißverschlusses",
	"Reperatur":             "Reparatur",
	"Reperaturen":           "Reparaturen",
	"Rhytmen":               "Rhythmen",
	"Rhytmus":               "Rhythmus",
	"Ruckmeldung":           "Rückmeldung",
	"Rythmus":               "Rhythmus",
	"Sa-So":                 "Sa.–So.",
	"Schiessen":             "Schießen",
	"Schliesslich":          "Schließlich",
	"Stahlkraft":            "Strahlkraft",
	"Stehgreif":             "Stegreif",
	"Storie":                "Story",
	"Stories":               "Storys",
	"Stückweit":             "Stück weit",
	"SuperGAU":              "Super-GAU",
	"SuperGau":              "Super-Gau",
	"Terasse":               "Terrasse",
	"Terassen":              "Terrassen",
	"Tiktok":                "TikTok",
	"Tiktoker":              "TikToker",
	"Tiktokerin":            "TikTokerin",
	"Tiktokerinnen":         "TikTokerinnen",
	"Tiktokern":             "TikTokern",
	"Tiktokers":             "TikTokers",
	"Tiktoks":               "TikToks",
	"Torschusspanik":        "Torschlusspanik",
	"Tschibo":               "Tchibo",
	"Tschibos":              "Tchibos",
	"Türahmen":              "Türrahmen",
	"Unglückzahl":           "Unglückszahl",
	"Unglückzahlen":         "Unglückszahlen",
	"Uranium":               "Uran",
	"Uraniums":              "Urans",
	"Verwandschaft":         "Verwandtschaft",
	"Vorbescheidverfahren":  "Vorbescheidsverfahren",
	"Vorraus":               "Voraus",
	"Vorraussetzung":        "Voraussetzung",
	"Vorraussetzungen":      "Voraussetzungen",
	"Wehrwolf":              "Werwolf",
	"Wehrwolfs":             "Werwolfs",
	"Wehrwölfe":             "Werwölfe",
	"Wehrwölfen":            "Werwölfen",
	"Weisglut":              "Weißglut",
	"Weissheitszahn":        "Weisheitszahn",
	"Weissheitszahns":       "Weisheitszahns",
	"Weissheitszähne":       "Weisheitszähne",
	"Weissheitszähnen":      "Weisheitszähnen",
	"Weißheitszahn":         "Weisheitszahn",
	"Weißheitszahns":        "Weisheitszahns",
	"Weißheitszähne":        "Weisheitszähne",
	"Weißheitszähnen":       "Weisheitszähnen",
	"Whatsapp":              "WhatsApp",
	"Wiederspruch":          "Widerspruch",
	"Wiederspruchs":         "Widerspruchs",
	"Wiedersprüche":         "Widersprüche",
	"Wiedersprüchen":        "Widersprüchen",
	"Youtube":               "YouTube",
	"Youtuber":              "YouTuber",
	"Youtuberin":            "YouTuberin",
	"Youtuberinnen":         "YouTuberinnen",
	"Youtubers":             "YouTubers",
	"Zzgl":                  "Zzgl.",
	"abgeschalten":          "abgeschaltet",
	"abschliessend":         "abschließend",
	"achso":                 "ach so",
	"aelter":                "älter",
	"angeschalten":          "angeschaltet",
	"anschliessend":         "anschließend",
	"assozial":              "asozial",
	"assoziale":             "asoziale",
	"assozialem":            "asozialem",
	"assozialen":            "asozialen",
	"assozialer":            "asozialer",
	"assoziales":            "asoziales",
	"aufgehangen":           "aufgehängt",
	"ausser":                "außer",
	"ausserdem":             "außerdem",
	"ausversehen":           "aus Versehen",
	"beissen":               "beißen",
	"beisst":                "beißt",
	"bescheid":              "Bescheid",
	"bischen":               "bisschen",
	"bißchen":               "bisschen",
	"brilliant":             "brillant",
	"brilliante":            "brillante",
	"brilliantem":           "brillantem",
	"brillianten":           "brillanten",
	"brillianter":           "brillanter",
	"brilliantes":           "brillantes",
	"bsp":                   "bspw",
	"bzgl":                  "bzgl.",
	"daß":                   "dass",
	"deluxe":                "de luxe",
	"desweiteren":           "des Weiteren",
	"desöfteren":            "des Öfteren",
	"do":                    "so",
	"draussen":              "draußen",
	"eigtl":                 "eigtl.",
	"entgültig":             "endgültig",
	"entgültige":            "endgültige",
	"entgültigen":           "endgültigen",
	"entgültiger":           "endgültiger",
	"entgültiges":           "endgültiges",
	"erkäre":                "erkläre",
	"exkl":                  "exkl.",
	"falscherweise":         "fälschlicherweise",
	"garnich":               "gar nicht",
	"garnicht":              "gar nicht",
	"garnichts":             "gar nichts",
	"gedownloaded":          "downgeloadet",
	"gedownloadet":          "downgeloadet",
	"gedownloadete":         "downgeloadete",
	"gedownloadetem":        "downgeloadetem",
	"gedownloadeten":        "downgeloadeten",
	"gedownloadeter":        "downgeloadeter",
	"gedownloadetes":        "downgeloadetes",
	"geschalten":            "geschaltet",
	"gescheint":             "geschienen",
	"geupdated":             "upgedatet",
	"geupdatet":             "upgedatet",
	"geuploaded":            "upgeloadet",
	"geuploadet":            "upgeloadet",
	"geuploadete":           "upgeloadete",
	"geuploadetem":          "upgeloadetem",
	"geuploadeten":          "upgeloadeten",
	"geuploadeter":          "upgeloadeter",
	"geuploadetes":          "upgeloadetes",
	"geäussert":             "geäußert",
	"ggf":                   "ggf.",
	"gradeaus":              "geradeaus",
	"heisse":                "heiße",
	"heissen":               "heißen",
	"heisst":                "heißt",
	"hiess":                 "hieß",
	"hälst":                 "hältst",
	"hörensagen":            "Hörensagen",
	"immernoch":             "immer noch",
	"inflagranti":           "in flagranti",
	"inkl":                  "inkl.",
	"jedesmal":              "jedes Mal",
	"jenachdem":             "je nachdem",
	"kucke":                 "gucke",
	"kucken":                "gucken",
	"kuckten":               "guckten",
	"languagetool":          "LanguageTool",
	"languagetools":         "LanguageTools",
	"liket":                 "likt",
	"markirt":               "markiert",
	"meißt":                 "meist",
	"meißten":               "meisten",
	"meißtens":              "meistens",
	"mußt":                  "musst",
	"mußte":                 "musste",
	"mußten":                "mussten",
	"mußtest":               "musstest",
	"müßen":                 "müssen",
	"müßt":                  "müsst",
	"müßte":                 "müsste",
	"müßten":                "müssten",
	"müßtest":               "müsstest",
	"nagut":                 "na gut",
	"offensichtlicherweise": "offensichtlich",
	"raufgeguckt":           "draufgeguckt",
	"raufgehaut":            "draufgehaut",
	"raufgeschaut":          "draufgeschaut",
	"raufgucke":             "draufgucke",
	"raufgucken":            "draufgucken",
	"raufguckst":            "draufguckst",
	"raufguckt":             "draufguckt",
	"raufguckte":            "draufguckte",
	"raufguckten":           "draufguckten",
	"raufhaue":              "draufhaue",
	"raufhauen":             "draufhauen",
	"raufhaust":             "draufhaust",
	"raufhaut":              "draufhaut",
	"raufhaute":             "draufhaute",
	"raufhauten":            "draufhauten",
	"raufschaue":            "draufschaue",
	"raufschauen":           "draufschauen",
	"raufschaust":           "draufschaust",
	"raufschaut":            "draufschaut",
	"raufschaute":           "draufschaute",
	"raufschauten":          "draufschauten",
	"raufzugucken":          "draufzugucken",
	"raufzuhauen":           "draufzuhauen",
	"raufzuschauen":         "draufzuschauen",
	"regelmässig":           "regelmäßig",
	"schleswig-holstein":    "Schleswig-Holstein",
	"schliesslich":          "schließlich",
	"sodaß":                 "sodass",
	"staubgesaugt":          "gestaubsaugt",
	"teilzeit":              "Teilzeit",
	"trümmern":              "Trümmern",
	"unkonsistent":          "inkonsistent",
	"unrelevant":            "irrelevant",
	"up-to-date":            "up to date",
	"vollzeit":              "Vollzeit",
	"vorallem":              "vor allem",
	"vorraus":               "voraus",
	"weitesgehend":          "weitestgehend",
	"werrden":               "werden",
	"wohlmöglich":           "womöglich",
	"wohlwissend":           "wohl wissend",
	"wußte":                 "wusste",
	"wußten":                "wussten",
	"wüßte":                 "wüsste",
	"wüßten":                "wüssten",
	"zzgl":                  "zzgl.",
	"Äusserst":              "Äußerst",
	"äussern":               "äußern",
	"äusserst":              "äußerst",
	"ürbigens":              "übrigens",

	// --- remaining Java getOnlySuggestions switch topMatch cases ---
	"Add-On":                      "Add-on",
	"Add-Ons":                     "Add-ons",
	"Anschrifft":                  "Anschrift",
	"Anteilname":                  "Anteilnahme",
	"Apr":                         "Apr.",
	"Aquaplanning":                "Aquaplaning",
	"Aquaplannings":               "Aquaplanings",
	"Aussenbereich":               "Außenbereich",
	"Aussenbereichs":              "Außenbereichs",
	"Ausserhalb":                  "Außerhalb",
	"Außenriss":                   "Außenrist",
	"Außerden":                    "Außerdem",
	"Babies":                      "Babys",
	"Bautenzug":                   "Bowdenzug",
	"Bautenzuges":                 "Bowdenzuges",
	"Bautenzugs":                  "Bowdenzugs",
	"Bautenzüge":                  "Bowdenzüge",
	"Bautenzügen":                 "Bowdenzügen",
	"BayArea":                     "Bay Area",
	"Brandwein":                   "Branntwein",
	"Brandweine":                  "Branntweine",
	"Brandweinen":                 "Branntweinen",
	"Brandweines":                 "Branntweines",
	"Brandweins":                  "Branntweins",
	"Brics-Staat":                 "BRICS-Staat",
	"Brics-Staaten":               "BRICS-Staaten",
	"Brics-Staats":                "BRICS-Staats",
	"Carlsen-Verlag":              "Carlsen Verlag",
	"Carlsen-Verlags":             "Carlsen Verlags",
	"Communities":                 "Communitys",
	"DAnke":                       "Danke",
	"Davidswache":                 "Davidwache",
	"E-Mai":                       "E-Mail",
	"E-Mais":                      "E-Mails",
	"E.On":                        "E.ON",
	"E.on":                        "E.ON",
	"Ebensogut":                   "Ebenso gut",
	"Ebensoleicht":                "Ebenso leicht",
	"Ebensooft":                   "Ebenso oft",
	"Ebensowenig":                 "Ebenso wenig",
	"Eifelturm":                   "Eiffelturm",
	"Eifelturmes":                 "Eiffelturmes",
	"Eifelturms":                  "Eiffelturms",
	"Einfallspinsel":              "Einfaltspinsel",
	"Einfallspinseln":             "Einfaltspinseln",
	"Einzigst":                    "Einzig",
	"Enschuldigen":                "Entschuldigen",
	"Eurocup":                     "EuroCup",
	"Eurocups":                    "EuroCups",
	"Feb":                         "Feb.",
	"Fidji":                       "Fidschi",
	"Fuer":                        "Für",
	"Gefahrenstoffe":              "Gefahrstoffe",
	"Gefahrenstoffen":             "Gefahrstoffen",
	"Gegebenfalls":                "Gegebenenfalls",
	"Gelantine":                   "Gelatine",
	"Geruchsinn":                  "Geruchssinn",
	"Geruchsinns":                 "Geruchssinns",
	"Gespraech":                   "Gespräch",
	"Gespraechs":                  "Gesprächs",
	"Gluckwunsch":                 "Glückwunsch",
	"Gluckwunsche":                "Glückwünsche",
	"Glückwunsche":                "Glückwünsche",
	"Gruss":                       "Gruß",
	"Grüzi":                       "Grüezi",
	"Gummies":                     "Gummis",
	"HEy":                         "Hey",
	"Hauptstrasse":                "Hauptstraße",
	"HeyLogin":                    "heylogin",
	"Hinterweltler":               "Hinterwäldler",
	"Hinterweltlerin":             "Hinterwäldlerin",
	"Hinterweltlerinnen":          "Hinterwäldlerinnen",
	"Hinterweltlern":              "Hinterwäldlern",
	"Hinterweltlers":              "Hinterwäldlers",
	"Ifo-Institut":                "ifo Institut",
	"Ifo-Instituts":               "ifo Instituts",
	"IfoInstitut":                 "ifo Institut",
	"IfoInstituts":                "ifo Instituts",
	"Innenriss":                   "Innenrist",
	"Interior":                    "Interieur",
	"Interiors":                   "Interieurs",
	"Ipad":                        "iPad",
	"Ipads":                       "iPads",
	"Iphone":                      "iPhone",
	"Iphones":                     "iPhones",
	"Irish-Pub":                   "Irish Pub",
	"Irish-Pubs":                  "Irish Pubs",
	"Jojo-Effekt":                 "Jo-Jo-Effekt",
	"Jojo-Effekts":                "Jo-Jo-Effekts",
	"Juergen":                     "Jürgen",
	"Kibbutz":                     "Kibbuz",
	"Kleidungstück":               "Kleidungsstück",
	"Kleidungstücke":              "Kleidungsstücke",
	"Kleidungstücken":             "Kleidungsstücken",
	"Kleidungstückes":             "Kleidungsstückes",
	"Kleidungstücks":              "Kleidungsstücks",
	"Kosten-Nutzenanalyse":        "Kosten-Nutzen-Analyse",
	"Kosten-Nutzenanalysen":       "Kosten-Nutzen-Analysen",
	"Kosten-Nutzenrechnung":       "Kosten-Nutzen-Rechnung",
	"Kosten-Nutzenrechnungen":     "Kosten-Nutzen-Rechnungen",
	"Kosten-Nutzenverhältnis":     "Kosten-Nutzen-Verhältnis",
	"Kosten-Nutzenverhältnisse":   "Kosten-Nutzen-Verhältnisse",
	"Kosten-Nutzenverhältnisses":  "Kosten-Nutzen-Verhältnisses",
	"Kreisaal":                    "Kreißsaal",
	"Kreisaals":                   "Kreißsaals",
	"Kreissaal":                   "Kreißsaal",
	"Kreissaals":                  "Kreißsaals",
	"Kreissäle":                   "Kreißsäle",
	"Kreissälen":                  "Kreißsälen",
	"Laola-Welle":                 "La-Ola-Welle",
	"Laola-Wellen":                "La-Ola-Wellen",
	"Letzlich":                    "Letztlich",
	"Linkedin":                    "LinkedIn",
	"Lollies":                     "Lollis",
	"Lolly":                       "Lolli",
	"Lollys":                      "Lollis",
	"MacMini":                     "Mac mini",
	"MacMinis":                    "Mac minis",
	"Macbook":                     "MacBook",
	"Macbooks":                    "MacBooks",
	"Mahnungswesen":               "Mahnwesen",
	"Mahnungswesens":              "Mahnwesens",
	"Massnahme":                   "Maßnahme",
	"Massnahmen":                  "Maßnahmen",
	"Mfg":                         "MfG",
	"Moet":                        "Moët",
	"Neisse-Verlag":               "Neisse Verlag",
	"Neisse-Verlags":              "Neisse Verlags",
	"Neiße-Verlag":                "Neisse Verlag",
	"Neiße-Verlags":               "Neisse Verlags",
	"Nirgendswo":                  "Nirgendwo",
	"Nov":                         "Nov.",
	"Nächstesmal":                 "Nächstes Mal",
	"Ohje":                        "Oje",
	"Okt":                         "Okt.",
	"Optin":                       "Opt-in",
	"Orginal":                     "Original",
	"Orginals":                    "Originals",
	"Parcour":                     "Parcours",
	"Pdf":                         "PDF",
	"Pdfs":                        "PDFs",
	"Pinwand":                     "Pinnwand",
	"Prigozhin":                   "Prigoschin",
	"Prigozhins":                  "Prigoschins",
	"Prozentteil":                 "Prozentanteil",
	"Quilbot":                     "QuillBot",
	"Quillbot":                    "QuillBot",
	"Regattas":                    "Regatten",
	"Rehgips":                     "Rigips",
	"Rehgips-Platte":              "Rigips-Platte",
	"Rehgips-Platten":             "Rigips-Platten",
	"Rehgipsplatte":               "Rigipsplatte",
	"Rehgipsplatten":              "Rigipsplatten",
	"Reiszwecke":                  "Reißzwecke",
	"Reiszwecken":                 "Reißzwecken",
	"Rene":                        "René",
	"Renes":                       "Renés",
	"Resource":                    "Ressource",
	"Resourcen":                   "Ressourcen",
	"Resources":                   "Ressourcen",
	"Ressorthotel":                "Resorthotel",
	"Ressorthotels":               "Resorthotels",
	"Rundumsorglospaket":          "Rundum-sorglos-Paket",
	"Rundumsorglospakets":         "Rundum-sorglos-Pakets",
	"SEhr":                        "Sehr",
	"Schalosie":                   "Jalousie",
	"Schalosien":                  "Jalousien",
	"Schuldigung":                 "Entschuldigung",
	"Schwupps":                    "Schwups",
	"Segelregattas":               "Segelregatten",
	"Selenski":                    "Selenskyj",
	"Sinnflut":                    "Sintflut",
	"Situp":                       "Sit-up",
	"Situps":                      "Sit-ups",
	"SnapChat":                    "Snapchat",
	"SnapChats":                   "Snapchats",
	"Sommeliere":                  "Sommelière",
	"Sommeliére":                  "Sommelière",
	"Sparringpartner":             "Sparringspartner",
	"Sparringpartnern":            "Sparringspartnern",
	"Sparringpartners":            "Sparringspartners",
	"Spass":                       "Spaß",
	"Stk":                         "Stk.",
	"Strebergarten":               "Schrebergarten",
	"Strebergartens":              "Schrebergartens",
	"Strebergärten":               "Schrebergärten",
	"Sylvester":                   "Silvester",
	"T-shirt":                     "T-Shirt",
	"T-shirts":                    "T-Shirts",
	"Triologie":                   "Trilogie",
	"Tschuldigung":                "Entschuldigung",
	"Typescript":                  "TypeScript",
	"Tzatziki":                    "Zaziki",
	"Visas":                       "Visa",
	"Walldorfschule":              "Waldorfschule",
	"Walldorfschulen":             "Waldorfschulen",
	"Websiten":                    "Webseiten",
	"Weinachten":                  "Weihnachten",
	"Weisst":                      "Weißt",
	"Wiederhall":                  "Widerhall",
	"Wiederhalls":                 "Widerhalls",
	"Wiedersehn":                  "Wiedersehen",
	"Wieviel":                     "Wie viel",
	"Wirtschaftsingenieurswesen":  "Wirtschaftsingenieurwesen",
	"Wirtschaftsingenieurswesens": "Wirtschaftsingenieurwesens",
	"Wordpress":                   "WordPress",
	"Youngstar":                   "Youngster",
	"Youngstars":                  "Youngsters",
	"Zweitenmal":                  "Zweiten Mal",
	"abhol":                       "abhole",
	"afro-amerikanisch":           "afroamerikanisch",
	"afro-amerikanische":          "afroamerikanische",
	"afro-amerikanischem":         "afroamerikanischem",
	"afro-amerikanischen":         "afroamerikanischen",
	"afro-amerikanischer":         "afroamerikanischer",
	"afro-amerikanisches":         "afroamerikanisches",
	"amazon":                      "Amazon",
	"angehangenen":                "angehängten",
	"ansich":                      "an sich",
	"armgerechnet":                "arm gerechnet",
	"armrechne":                   "arm rechne",
	"armrechnen":                  "arm rechnen",
	"armrechnest":                 "arm rechnest",
	"armrechnet":                  "arm rechnet",
	"armzurechnen":                "arm zu rechnen",
	"ausgemahlt":                  "ausgemalt",
	"ausmahlen":                   "ausmalen",
	"aussen":                      "außen",
	"aussergewöhnlich":            "außergewöhnlich",
	"aussergewöhnliche":           "außergewöhnliche",
	"aussergewöhnlichen":          "außergewöhnlichen",
	"aussergewöhnlicher":          "außergewöhnlicher",
	"aussergewöhnliches":          "außergewöhnliches",
	"ausserhalb":                  "außerhalb",
	"ausserordentlich":            "außerordentlich",
	"ausserordentliche":           "außerordentliche",
	"ausserordentlichem":          "außerordentlichem",
	"ausserordentlichen":          "außerordentlichen",
	"ausserordentlicher":          "außerordentlicher",
	"ausserordentliches":          "außerordentliches",
	"außerden":                    "außerdem",
	"barfuss":                     "barfuß",
	"beindruckend":                "beeindruckend",
	"beindruckende":               "beeindruckende",
	"beindruckendem":              "beeindruckendem",
	"beindruckenden":              "beeindruckenden",
	"beindruckender":              "beeindruckender",
	"beindruckendes":              "beeindruckendes",
	"beindruckt":                  "beeindruckt",
	"beindruckte":                 "beeindruckte",
	"beispielweise":               "beispielsweise",
	"bestmöglichst":               "bestmöglich",
	"deligieren":                  "delegieren",
	"deligiert":                   "delegiert",
	"dererseits":                  "ihrerseits",
	"durchfuehren":                "durchführen",
	"durchgefuehrt":               "durchgeführt",
	"ebensogut":                   "ebenso gut",
	"ebensoleicht":                "ebenso leicht",
	"ebensooft":                   "ebenso oft",
	"ebensowenig":                 "ebenso wenig",
	"eigendlich":                  "eigentlich",
	"eigendliche":                 "eigentliche",
	"eigendlichem":                "eigentlichem",
	"eigendlichen":                "eigentlichen",
	"eigendlicher":                "eigentlicher",
	"eigendliches":                "eigentliches",
	"einigermassen":               "einigermaßen",
	"einzigst":                    "einzig",
	"einzigste":                   "einzige",
	"einzigstem":                  "einzigem",
	"einzigsten":                  "einzigen",
	"einzigster":                  "einziger",
	"einzigstes":                  "einziges",
	"erhählst":                    "erhältst",
	"erhälst":                     "erhältst",
	"ernstgemeinet":               "ernst gemeint",
	"ernstgenommen":               "ernst genommen",
	"ernstmeine":                  "ernst meine",
	"ernstmeinen":                 "ernst meinen",
	"ernstmeinst":                 "ernst meinst",
	"ernstmeinte":                 "ernst meinte",
	"ernstnehme":                  "ernst nehme",
	"ernstnehmen":                 "ernst nehmen",
	"ernstnimmst":                 "ernst nimmst",
	"ernstnimmt":                  "ernst nimmt",
	"ernstzumeinen":               "ernst zu meinen",
	"ernstzunehmen":               "ernst zu nehmen",
	"erstrecht":                   "erst recht",
	"ertragsreich":                "ertragreich",
	"ertragsreiche":               "ertragreiche",
	"ertragsreichen":              "ertragreichen",
	"ertragsreiches":              "ertragreiches",
	"etc":                         "etc.",
	"ewiggleich":                  "ewig gleich",
	"ewiggleiche":                 "ewig gleiche",
	"ewiggleichem":                "ewig gleichem",
	"ewiggleichen":                "ewig gleichen",
	"ewiggleicher":                "ewig gleicher",
	"ewiggleiches":                "ewig gleiches",
	"fertiggeschrieben":           "fertig geschrieben",
	"fertigschreiben":             "fertig schreiben",
	"fertigschreibt":              "fertig schreibt",
	"fertigzuschreiben":           "fertig zu schreiben",
	"freidenken":                  "frei denken",
	"freigedacht":                 "frei gedacht",
	"freigeschlagen":              "frei geschlagen",
	"freigeschrieben":             "frei geschrieben",
	"freiliegen":                  "frei liegen",
	"freischlagen":                "frei schlagen",
	"freischreiben":               "frei schreiben",
	"freiverfügbar":               "frei verfügbar",
	"freiverfügbare":              "frei verfügbare",
	"freiverfügbarem":             "frei verfügbarem",
	"freiverfügbaren":             "frei verfügbaren",
	"freiverfügbarer":             "frei verfügbarer",
	"freiverfügbares":             "frei verfügbares",
	"freiverkäuflich":             "frei verkäuflich",
	"freiverkäufliche":            "frei verkäufliche",
	"freiverkäuflichem":           "frei verkäuflichem",
	"freiverkäuflichen":           "frei verkäuflichen",
	"freiverkäuflicher":           "frei verkäuflicher",
	"freiverkäufliches":           "frei verkäufliches",
	"freizudenken":                "frei zu denken",
	"freizuschlagen":              "frei zu schlagen",
	"freizuschreiben":             "frei zu schreiben",
	"fuer":                        "für",
	"garkein":                     "gar kein",
	"garkeine":                    "gar keine",
	"garkeinen":                   "gar keinen",
	"gefühlsdusselig":             "gefühlsduselig",
	"gefühlsdusselige":            "gefühlsduselige",
	"gefühlsdusseligen":           "gefühlsduseligen",
	"gefühlsdusseliger":           "gefühlsduseliger",
	"gefühlsdusseliges":           "gefühlsduseliges",
	"gegebenfalls":                "gegebenenfalls",
	"geheimgehalten":              "geheim gehalten",
	"geheimhalten":                "geheim halten",
	"geheimhaltet":                "geheim haltet",
	"geheimhältst":                "geheim hältst",
	"geheimzuhalten":              "geheim zu halten",
	"gehhrte":                     "geehrte",
	"gehhrten":                    "geehrten",
	"gehhrtes":                    "geehrtes",
	"gekriecht":                   "gekrochen",
	"gemäss":                      "gemäß",
	"genausogut":                  "genauso gut",
	"geniesse":                    "genieße",
	"geniessen":                   "genießen",
	"gestriffen":                  "gestreift",
	"gets":                        "gehts",
	"gleichermassen":              "gleichermaßen",
	"gleichlauten":                "gleich lauten",
	"gleichzeit":                  "gleichzeitig",
	"grossartig":                  "großartig",
	"grosse":                      "große",
	"grossen":                     "großen",
	"grosser":                     "großer",
	"grosses":                     "großes",
	"grosszügig":                  "großzügig",
	"gunsten":                     "Gunsten",
	"gutdünken":                   "Gutdünken",
	"heilsbringend":               "heilbringend",
	"heilsbringende":              "heilbringende",
	"heilsbringendem":             "heilbringendem",
	"heilsbringenden":             "heilbringenden",
	"heilsbringender":             "heilbringender",
	"heilsbringendes":             "heilbringendes",
	"heutejournal":                "heute journal",
	"homepage":                    "Homepage",
	"ifo-Institut":                "ifo Institut",
	"ifo-Instituts":               "ifo Instituts",
	"ifoInstitut":                 "ifo Institut",
	"ifoInstituts":                "ifo Instituts",
	"interesse":                   "Interesse",
	"ipad":                        "iPad",
	"ipads":                       "iPads",
	"iphone":                      "iPhone",
	"iphones":                     "iPhones",
	"irgendeins":                  "irgendeines",
	"jmd":                         "jmd.",
	"klangheimlich":               "klammheimlich",
	"klangheimliche":              "klammheimliche",
	"klangheimlichem":             "klammheimlichem",
	"klangheimlichen":             "klammheimlichen",
	"klangheimlicher":             "klammheimlicher",
	"klangheimliches":             "klammheimliches",
	"kontaktfreundlich":           "kontaktfreudig",
	"kontaktfreundliche":          "kontaktfreudige",
	"kontaktfreundlichem":         "kontaktfreudigem",
	"kontaktfreundlichen":         "kontaktfreudigen",
	"kontaktfreundlicher":         "kontaktfreudiger",
	"kontaktfreundliches":         "kontaktfreudiges",
	"kupferfarbende":              "kupferfarbene",
	"kupferfarbendem":             "kupferfarbenem",
	"kupferfarbenden":             "kupferfarbenen",
	"kupferfarbender":             "kupferfarbener",
	"kupferfarbendes":             "kupferfarbenes",
	"langfahre":                   "entlangfahre",
	"langfahren":                  "entlangfahren",
	"langfuhren":                  "entlangfuhren",
	"langfährst":                  "entlangfährst",
	"langgefahren":                "entlanggefahren",
	"langgegangen":                "entlanggegangen",
	"langgehe":                    "entlanggehe",
	"langgehen":                   "entlanggehen",
	"langgelaufen":                "entlanggelaufen",
	"langging":                    "entlangging",
	"langgingen":                  "entlanggingen",
	"langlaufe":                   "entlanglaufe",
	"langlaufen":                  "entlanglaufen",
	"langliefen":                  "entlangliefen",
	"langläufst":                  "entlangläufst",
	"langzufahren":                "entlangzufahren",
	"langzugehen":                 "entlangzugehen",
	"langzulaufen":                "entlangzulaufen",
	"letzlich":                    "letztlich",
	"lustiggemacht":               "lustig gemacht",
	"lustigmache":                 "lustig mache",
	"lustigmachen":                "lustig machen",
	"lustigmachst":                "lustig machst",
	"lustigmachten":               "lustig machten",
	"lustigzumachen":              "lustig zu machen",
	"markaber":                    "makaber",
	"massgeblich":                 "maßgeblich",
	"mehrjährlich":                "mehrjährig",
	"mehrjährliche":               "mehrjährige",
	"mehrjährlichen":              "mehrjährigen",
	"mehrjährlicher":              "mehrjähriger",
	"mehrjährliches":              "mehrjähriges",
	"miteinbegriffen":             "mit einbegriffen",
	"mitinbegriffen":              "mit inbegriffen",
	"moeglich":                    "möglich",
	"moglich":                     "möglich",
	"nachgeharckt":                "nachgehackt",
	"nachgeharkt":                 "nachgehakt",
	"nachhacken":                  "nachhaken",
	"nachharken":                  "nachhaken",
	"natuerlich":                  "natürlich",
	"naturlich":                   "natürlich",
	"nciht":                       "nicht",
	"nichtsagend":                 "nichtssagend",
	"nichtsagende":                "nichtssagende",
	"nichtsagendem":               "nichtssagendem",
	"nichtsagenden":               "nichtssagenden",
	"nichtsagender":               "nichtssagender",
	"nichtsagendes":               "nichtssagendes",
	"niederschlagreich":           "niederschlagsreich",
	"niederschlagreiche":          "niederschlagsreiche",
	"niederschlagreichem":         "niederschlagsreichem",
	"niederschlagreichen":         "niederschlagsreichen",
	"niederschlagreicher":         "niederschlagsreicher",
	"niederschlagreiches":         "niederschlagsreiches",
	"nirgendswo":                  "nirgendwo",
	"nord-südlich":                "nordsüdlich",
	"nord-südliche":               "nordsüdliche",
	"nord-südlichem":              "nordsüdlichem",
	"nord-südlichen":              "nordsüdlichen",
	"nord-südlicher":              "nordsüdlicher",
	"nord-südliches":              "nordsüdliches",
	"nord-westlich":               "nordwestlich",
	"nord-westliche":              "nordwestliche",
	"nord-westlichem":             "nordwestlichem",
	"nord-westlichen":             "nordwestlichen",
	"nord-westlicher":             "nordwestlicher",
	"nord-westliches":             "nordwestliches",
	"nord-östlich":                "nordöstlich",
	"nord-östliche":               "nordöstliche",
	"nord-östlichem":              "nordöstlichem",
	"nord-östlichen":              "nordöstlichen",
	"nord-östlicher":              "nordöstlicher",
	"nord-östliches":              "nordöstliches",
	"nächstmöglichst":             "nächstmöglich",
	"ohje":                        "oje",
	"orginal":                     "original",
	"orginale":                    "originale",
	"orginalen":                   "originalen",
	"orginales":                   "originales",
	"ost-westlich":                "ostwestlich",
	"ost-westliche":               "ostwestliche",
	"ost-westlichem":              "ostwestlichem",
	"ost-westlichen":              "ostwestlichen",
	"ost-westlicher":              "ostwestlicher",
	"ost-westliches":              "ostwestliches",
	"pdf":                         "PDF",
	"pdfs":                        "PDFs",
	"quilbot":                     "QuillBot",
	"quillbot":                    "QuillBot",
	"raufgeklickt":                "draufgeklickt",
	"raufklicke":                  "draufklicke",
	"raufklicken":                 "draufklicken",
	"raufklickst":                 "draufklickst",
	"raufzuklicken":               "draufzuklicken",
	"rechtgab":                    "recht gab",
	"rechtgeben":                  "recht geben",
	"rechtgegeben":                "recht gegeben",
	"rechtgehabt":                 "recht gehabt",
	"rechtgemacht":                "recht gemacht",
	"rechtgibst":                  "recht gibst",
	"rechtgibt":                   "recht gibt",
	"rechthabe":                   "recht habe",
	"rechthaben":                  "recht haben",
	"rechthabt":                   "recht habt",
	"rechthast":                   "recht hast",
	"rechthatte":                  "recht hatte",
	"rechtmache":                  "recht mache",
	"rechtmachen":                 "recht machen",
	"rechtmachst":                 "recht machst",
	"rechtmacht":                  "recht macht",
	"rechtmachte":                 "recht machte",
	"rechtmachten":                "recht machten",
	"rechtstaatlich":              "rechtsstaatlich",
	"rechtzugeben":                "recht zu geben",
	"rechtzuhaben":                "recht zu haben",
	"rechtzumachen":               "recht zu machen",
	"rundumerneuert":              "runderneuert",
	"rundumerneuerte":             "runderneuerte",
	"rundumerneuertem":            "runderneuertem",
	"rundumerneuerten":            "runderneuerten",
	"rundumerneuerter":            "runderneuerter",
	"rundumerneuertes":            "runderneuertes",
	"rübergestülpt":               "übergestülpt",
	"rüberstülpe":                 "überstülpe",
	"rüberstülpen":                "überstülpen",
	"sattessen":                   "satt essen",
	"schwarzfarbende":             "schwarzfarbene",
	"schwarzfarbendem":            "schwarzfarbenem",
	"schwarzfarbenden":            "schwarzfarbenen",
	"schwarzfarbender":            "schwarzfarbener",
	"schwarzfarbendes":            "schwarzfarbenes",
	"schwupps":                    "schwups",
	"sontag":                      "Sonntag",
	"steinfarbende":               "steinfarbene",
	"steinfarbendem":              "steinfarbenem",
	"steinfarbenden":              "steinfarbenen",
	"steinfarbender":              "steinfarbener",
	"steinfarbendes":              "steinfarbenes",
	"süd-westlich":                "südwestlich",
	"süd-westliche":               "südwestliche",
	"süd-westlichem":              "südwestlichem",
	"süd-westlichen":              "südwestlichen",
	"süd-westlicher":              "südwestlicher",
	"süd-westliches":              "südwestliches",
	"süd-östlich":                 "südöstlich",
	"süd-östliche":                "südöstliche",
	"süd-östlichem":               "südöstlichem",
	"süd-östlichen":               "südöstlichen",
	"süd-östlicher":               "südöstlicher",
	"süd-östliches":               "südöstliches",
	"t-shirt":                     "T-Shirt",
	"t-shirts":                    "T-Shirts",
	"tatsachlich":                 "tatsächlich",
	"tatsachliche":                "tatsächliche",
	"tatsachlichem":               "tatsächlichem",
	"tatsachlichen":               "tatsächlichen",
	"tatsachlicher":               "tatsächlicher",
	"tatsachliches":               "tatsächliches",
	"taubgestellt":                "taub gestellt",
	"taubstelle":                  "taub stelle",
	"taubstellen":                 "taub stellen",
	"taubstellst":                 "taub stellst",
	"taubstellt":                  "taub stellt",
	"taubzustellen":               "taub zu stellen",
	"telephonisch":                "telefonisch",
	"telephonische":               "telefonische",
	"telephonischem":              "telefonischem",
	"telephonischen":              "telefonischen",
	"telephonischer":              "telefonischer",
	"telephonisches":              "telefonisches",
	"totkrank":                    "todkrank",
	"totkranke":                   "todkranke",
	"totkrankem":                  "todkrankem",
	"totkranken":                  "todkranken",
	"totkranker":                  "todkranker",
	"totkrankes":                  "todkrankes",
	"trifftige":                   "triftige",
	"trifftigem":                  "triftigem",
	"trifftigen":                  "triftigen",
	"trifftiger":                  "triftiger",
	"trifftiges":                  "triftiges",
	"tschuldige":                  "entschuldige",
	"tschüß":                      "tschüss",
	"umgangsprachlich":            "umgangssprachlich",
	"unaktiv":                     "inaktiv",
	"unaktive":                    "inaktive",
	"unaktiven":                   "inaktiven",
	"unaktiver":                   "inaktiver",
	"unaktives":                   "inaktives",
	"uneffektiv":                  "ineffektiv",
	"uneffezient":                 "ineffizient",
	"ungelungen":                  "misslungen",
	"ungelungene":                 "misslungene",
	"ungelungenem":                "misslungenem",
	"ungelungenen":                "misslungenen",
	"ungelungener":                "misslungener",
	"ungelungenes":                "misslungenes",
	"ungunsten":                   "Ungunsten",
	"unhilfreich":                 "unbehilflich",
	"unregelmässig":               "unregelmäßig",
	"unregelmässige":              "unregelmäßige",
	"unrentierlich":               "unrentabel",
	"unrentierliche":              "unrentable",
	"unrentierlichem":             "unrentablem",
	"unrentierlichen":             "unrentablen",
	"unrentierlicher":             "unrentabler",
	"unrentierliches":             "unrentables",
	"unterjährlich":               "unterjährig",
	"unterstüzt":                  "unterstützt",
	"untersützt":                  "unterstützt",
	"unverhältnismässig":          "unverhältnismäßig",
	"unzippe":                     "entzippe",
	"unzippen":                    "entzippen",
	"unzippst":                    "entzippst",
	"unzippt":                     "entzippt",
	"upgedated":                   "upgedatet",
	"verhältnismässig":            "verhältnismäßig",
	"vertrauenserweckend":         "vertrauenerweckend",
	"vielfaltig":                  "vielfältig",
	"vielfaltige":                 "vielfältige",
	"vielfaltigem":                "vielfältigem",
	"vielfaltigen":                "vielfältigen",
	"vielfaltiger":                "vielfältiger",
	"vielfaltiges":                "vielfältiges",
	"wachbleibe":                  "wach bleibe",
	"wachbleiben":                 "wach bleiben",
	"wachbleibst":                 "wach bleibst",
	"wachblieb":                   "wach blieb",
	"wachblieben":                 "wach blieben",
	"wachgeblieben":               "wach geblieben",
	"wachzubleiben":               "wach zu bleiben",
	"weihnachten":                 "Weihnachten",
	"weinachten":                  "Weihnachten",
	"weisst":                      "weißt",
	"wiedergespiegelt":            "widergespiegelt",
	"wiedersehn":                  "wiedersehen",
	"wiederspiegeln":              "widerspiegeln",
	"wiederspiegelst":             "widerspiegelst",
	"wiederspiegelt":              "widerspiegelt",
	"wieviel":                     "wie viel",
	"wikipedia":                   "Wikipedia",
	"zugebenermaßen":              "zugegebenermaßen",
	"zusammenfässt":               "zusammenfasst",
	"zweitenmal":                  "zweiten Mal",
}

var (
	reOnlySymphatisch  = regexp.MustCompile(`^symphatisch(?:e[nmsr]?|ste[nmsr]?|ere[nmsr]?)?$`)
	reOnlyAutentisch   = regexp.MustCompile(`^[Aa]utentisch(?:e[nmsr]?|ste[nmsr]?|ere[nmsr]?)?$`)
	reOnlyBrilliant    = regexp.MustCompile(`^brilliant(?:e[nmsr]?|ere[nmsr]?|este[nmsr]?)?$`)
	reOnlyRechtmasig   = regexp.MustCompile(`^rechtmässig(?:e[nmsr]?|ere[nmsr]?|ste[nmsr]?)?$`)
	reOnlyMaszname     = regexp.MustCompile(`(?i).*ma(?:ss|ß)namen?.*`)
	reOnlyPanel        = regexp.MustCompile(`^(?:Holz|Spiegel)panel(?:s|en?)?$`)
	reOnlySBahn        = regexp.MustCompile(`^SBahn(?:en|hofs?|zug(?:e?s)?|zügen?|höfen?|netz(?:e[ns]?)?|tunnel[sn]?|linien?)?$`)
	reOnlyUBahn        = regexp.MustCompile(`^UBahn(?:en|hofs?|zug(?:e?s)?|zügen?|höfen?|netz(?:e[ns]?)?|tunnel[sn]?|linien?)?$`)
	reStartNeger       = regexp.MustCompile(`(?i)^neger`)
	reContainsNeger    = regexp.MustCompile(`(?i).+neger(?:s|n|in|innen)?.+`)
	reContainsNeger2   = regexp.MustCompile(`(?i).+-neger(?:s|n|in|innen)?-.+`)
	reUncommonNounEnd  = regexp.MustCompile(`.+\s(?:hunger|zeit|käse|zwiebel|kommoden?|lager|angst|freund|feind)$`)
	reUncommonNounBeg  = regexp.MustCompile(`^(?:hunger|zeit|käse|zwiebel|kommoden?|lager|angst|freund|feind)\s.+`)
	reGenderStarMatch  = regexp.MustCompile(`(?:[A-ZÖÄÜ][a-zöäüß]{1,25}|[A-ZÖÄÜ]{1,10}-[A-ZÖÄÜ][a-zöäüß]{1,25})[*:_][a-zöäüß]{1,25}`)
	reFileUnderline    = regexp.MustCompile(`[a-zA-Z0-9-]{1,25}_[a-zA-Z0-9-]{1,25}\.[a-zA-Z]{1,5}`)
	reMentionUnderline = regexp.MustCompile(`@[a-zA-Z0-9-]{1,25}_[a-zA-Z0-9_-]{1,25}`)
	reStripGenderMark  = regexp.MustCompile(`[*:_]`)
)

// OnlySuggestions ports GermanSpellerRule.getOnlySuggestions — exclusive curated list.
func (r *GermanSpellerRule) OnlySuggestions(word string) []string {
	if word == "" {
		return nil
	}
	if reOnlySymphatisch.MatchString(word) {
		return []string{strings.Replace(word, "symphatisch", "sympathisch", 1)}
	}
	if reOnlyAutentisch.MatchString(word) {
		return []string{strings.Replace(word, "utent", "uthent", 1)}
	}
	if reOnlyBrilliant.MatchString(word) {
		return []string{strings.Replace(word, "brilliant", "brillant", 1)}
	}
	if reOnlyRechtmasig.MatchString(word) {
		return []string{strings.Replace(word, "mässig", "mäßig", 1)}
	}
	if reOnlyMaszname.MatchString(word) {
		return []string{regexp.MustCompile(`a(?:ss|ß)name`).ReplaceAllString(word, "aßnahme")}
	}
	if reOnlyPanel.MatchString(word) {
		return []string{strings.Replace(word, "panel", "paneel", 1)}
	}
	if reOnlySBahn.MatchString(word) {
		return []string{strings.Replace(word, "SBahn", "S-Bahn", 1)}
	}
	if reOnlyUBahn.MatchString(word) {
		return []string{strings.Replace(word, "UBahn", "U-Bahn", 1)}
	}
	switch word {
	case "Büffet", "Buffett", "Bufett", "Büffett", "Bufet", "Büfet":
		if r != nil && (r.LanguageVariant == "CH" || r.LanguageVariant == "AT") {
			return []string{"Buffet"}
		}
		return []string{"Büfett"}
	}
	if s, ok := onlySuggestionsExact[word]; ok {
		return []string{s}
	}
	return nil
}

// FilterNoSuggestWords ports filterNoSuggestWords on string suggestions.
func (r *GermanSpellerRule) FilterNoSuggestWords(sugs []string) []string {
	if len(sugs) == 0 {
		return sugs
	}
	var out []string
	for _, s := range sugs {
		lc := strings.ToLower(s)
		if _, bad := lcDoNotSuggestWords[lc]; bad {
			continue
		}
		if reStartNeger.MatchString(lc) || reContainsNeger.MatchString(lc) || reContainsNeger2.MatchString(lc) {
			continue
		}
		if reUncommonNounEnd.MatchString(s) || reUncommonNounBeg.MatchString(s) {
			continue
		}
		out = append(out, s)
	}
	return out
}

// removeGenderCompoundMatches ports removeGenderCompoundMatches cleanup after Match.
func (r *GermanSpellerRule) removeGenderCompoundMatches(sentence *languagetool.AnalyzedSentence, ms []*rules.RuleMatch) []*rules.RuleMatch {
	if r == nil || sentence == nil || len(ms) == 0 {
		return ms
	}
	text := sentence.GetText()
	out := ms
	for _, loc := range reGenderStarMatch.FindAllStringIndex(text, -1) {
		g := text[loc[0]:loc[1]]
		stripped := reStripGenderMark.ReplaceAllString(g, "")
		if r.IsMisspelled(stripped) {
			continue
		}
		gs, ge := loc[0], loc[1]
		var filtered []*rules.RuleMatch
		for _, m := range out {
			if m == nil {
				continue
			}
			from, to := m.GetFromPos(), m.GetToPos()
			if gs < from && ge == to {
				continue
			}
			if gs == from && ge > to {
				continue
			}
			filtered = append(filtered, m)
		}
		out = filtered
	}
	for _, loc := range reFileUnderline.FindAllStringIndex(text, -1) {
		out = filterMatchesInsideSpan(out, loc[0], loc[1])
	}
	for _, loc := range reMentionUnderline.FindAllStringIndex(text, -1) {
		out = filterMatchesInsideSpan(out, loc[0], loc[1])
	}
	return out
}

func filterMatchesInsideSpan(ms []*rules.RuleMatch, start, end int) []*rules.RuleMatch {
	var out []*rules.RuleMatch
	for _, m := range ms {
		if m == nil {
			continue
		}
		if start <= m.GetFromPos() && end >= m.GetToPos() {
			continue
		}
		out = append(out, m)
	}
	return out
}
