package de

import (
	"github.com/lucasew/lang/internal/languagetool/org/languagetool"
	"github.com/lucasew/lang/internal/languagetool/org/languagetool/rules"
)

// GermanFillerWordsRule ports org.languagetool.rules.de.GermanFillerWordsRule
// in minPercent=0 mode (report all fillers; paragraph % filtering not modeled).
type GermanFillerWordsRule struct {
	*rules.AbstractFillerWordsRule
}

func NewGermanFillerWordsRule(messages map[string]string) *GermanFillerWordsRule {
	fillers := map[string]struct{}{}
	for _, w := range []string{
		"aber",
		"abermals",
		"allein",
		"allemal",
		"allenfalls",
		"allenthalben",
		"allerdings",
		"allesamt",
		"allzu",
		"also",
		"alt",
		"andauernd",
		"andererseits",
		"andernfalls",
		"anscheinend",
		"auch",
		"auffallend",
		"augenscheinlich",
		"ausdrücklich",
		"ausgerechnet",
		"ausnahmslos",
		"außerdem",
		"äußerst",
		"beinahe",
		"bekanntlich",
		"bereits",
		"besonders",
		"bestenfalls",
		"bestimmt",
		"bloß",
		"dabei",
		"dadurch",
		"dafür",
		"dagegen",
		"daher",
		"damals",
		"danach",
		"demgegenüber",
		"demgemäß",
		"demnach",
		"denkbar",
		"denn",
		"dennoch",
		"deshalb",
		"deswegen",
		"doch",
		"durchaus",
		"durchweg",
		"eben",
		"eigentlich",
		"einerseits",
		"einfach",
		"einige",
		"einigermaßen",
		"einmal",
		"ergo",
		"erheblich",
		"etliche",
		"etwa",
		"etwas",
		"fast",
		"folgendermaßen",
		"folglich",
		"förmlich",
		"fortwährend",
		"fraglos",
		"freilich",
		"ganz",
		"gänzlich",
		"gar",
		"gelegentlich",
		"gemeinhin",
		"genau",
		"geradezu",
		"gewiss",
		"gewissermaßen",
		"glatt",
		"gleichsam",
		"gleichwohl",
		"glücklicherweise",
		"gottseidank",
		"größtenteils",
		"häufig",
		"hingegen",
		"hinlänglich",
		"höchst",
		"höchstens",
		"immer",
		"immerhin",
		"immerzu",
		"indessen",
		"infolgedessen",
		"insbesondere",
		"inzwischen",
		"irgend",
		"irgendein",
		"irgendjemand",
		"irgendwann",
		"irgendwie",
		"irgendwo",
		"ja",
		"je",
		"jedenfalls",
		"jedoch",
		"jemals",
		"kaum",
		"keinesfalls",
		"keineswegs",
		"längst",
		"lediglich",
		"leider",
		"letztlich",
		"manchmal",
		"mehrfach",
		"meinetwegen",
		"meist",
		"meistens",
		"meistenteils",
		"mindestens",
		"mithin",
		"mitunter",
		"möglicherweise",
		"möglichst",
		"nämlich",
		"naturgemäß",
		"natürlich",
		"neuerdings",
		"neuerlich",
		"neulich",
		"nichtsdestoweniger",
		"nie",
		"niemals",
		"nun",
		"nur",
		"offenbar",
		"offenkundig",
		"offensichtlich",
		"oft",
		"ohnedies",
		"partout",
		"plötzlich",
		"praktisch",
		"quasi",
		"recht",
		"reichlich",
		"reiflich",
		"relativ",
		"restlos",
		"richtiggehend",
		"rundheraus",
		"rundum",
		"sattsam",
		"schlicht",
		"schlichtweg",
		"schließlich",
		"schlussendlich",
		"schon",
		"sehr",
		"selbst",
		"selbstredend",
		"selbstverständlich",
		"selten",
		"seltsamerweise",
		"sicher",
		"sicherlich",
		"so",
		"sogar",
		"sonst",
		"sowieso",
		"sozusagen",
		"stellenweise",
		"stets",
		"trotzdem",
		"überaus",
		"überdies",
		"überhaupt",
		"übrigens",
		"umständehalber",
		"unbedingt",
		"unerhört",
		"ungefähr",
		"ungemein",
		"ungewöhnlich",
		"ungleich",
		"unglücklicherweise",
		"unlängst",
		"unmaßgeblich",
		"unsagbar",
		"unsäglich",
		"unstreitig",
		"unzweifelhaft",
		"vergleichsweise",
		"vermutlich",
		"vielfach",
		"vielleicht",
		"voll",
		"vollends",
		"völlig",
		"vollkommen",
		"vollständig",
		"wahrscheinlich",
		"weidlich",
		"weitgehend",
		"wenigstens",
		"wieder",
		"wiederum",
		"wirklich",
		"wohl",
		"wohlgemerkt",
		"womöglich",
		"ziemlich",
		"zudem",
		"zugegeben",
		"zumeist",
		"zusehends",
		"zuweilen",
		"zweifellos",
		"zweifelsfrei",
		"zweifelsohne",
	} {
		fillers[w] = struct{}{}
	}
	base := &rules.AbstractFillerWordsRule{
		Messages:    messages,
		ID:          "FILLER_WORDS_DE",
		Description: "Füllwörter",
		ShortMsg:    "Füllwort",
		Message:     "Dieses Wort kann ein Füllwort sein.",
		FillerWords: fillers,
		MinPercent:  0,
	}
	return &GermanFillerWordsRule{AbstractFillerWordsRule: base}
}

func (r *GermanFillerWordsRule) Match(sentence *languagetool.AnalyzedSentence) []*rules.RuleMatch {
	return r.AbstractFillerWordsRule.Match(sentence)
}
