package de

import "regexp"

// Generated from GermanSpellerRule.ADDITIONAL_SUGGESTIONS putRepl() and
// put(pattern, replacement) where pattern has regexp metacharacters.
// Exact literal puts live in german_speller_additional_exact.go.
// Full-string match (Java Pattern.matches); RE2-incompatible patterns skipped at init.

const additionalSugMaxMatchLen = 250

type additionalSugRepl struct {
	word *regexp.Regexp
	find *regexp.Regexp
	repl string
}

type additionalSugFixedEntry struct {
	word *regexp.Regexp
	repl string
}

var (
	additionalSugRepls         []additionalSugRepl
	additionalSugPatternFixed  []additionalSugFixedEntry
)

func init() {
	registerAdditionalSugRepl(`.+telefones`, `telefones`, `telefons`)
	registerAdditionalSugRepl(`.+tips`, `tip`, `tipp`)
	registerAdditionalSugRepl(`Hifi-.+`, `Hifi`, `HiFi`)
	registerAdditionalSugRepl(`Analgen.*`, `Analgen`, `Anlagen`)
	registerAdditionalSugRepl(`wiedersteh(en|st|t)`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiederstan(d|den|dest)`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiedersprech(e|t|en)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiedersprich(st|t)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiedersprach(st|t|en)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiederruf(e|st|t|en)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiederrief(st|t|en)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiederleg(e|st|t|en|te|ten)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiederhall(e|st|t|en|te|ten)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiedersetz(e|t|en|te|ten)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`wiederstreb(e|st|t|en|te|ten)?`, `wieder`, `wider`)
	registerAdditionalSugRepl(`zurück(ge|zu)?koppe?l(e|n|t(e(st|n)?)?|nd(e(r|s|m|n)?)?|st|)?`, `zurück`, `rück`)
	registerAdditionalSugRepl(`(an|auf|ein|zu)gehangen(e[mnrs]?)?$`, `hangen`, `hängt`)
	registerAdditionalSugRepl(`[oO]key`, `ey$`, `ay`)
	registerAdditionalSugRepl(`[Ww]ar ne`, `ne`, `eine`)
	registerAdditionalSugRepl(`[Ää]nliche[rnms]?`, `nlich`, `hnlich`)
	registerAdditionalSugRepl(`[Gg]arnix`, `nix`, `nichts`)
	registerAdditionalSugRepl(`[Ww]i`, `i`, `ie`)
	registerAdditionalSugRepl(`[uU]nauslässlich(e[mnrs]?)?`, `aus`, `er`)
	registerAdditionalSugRepl(`[vV]erewiglicht(e[mnrs]?)?`, `lich`, ``)
	registerAdditionalSugRepl(`[zZ]eritifiert(e[mnrs]?)?`, `eritifiert`, `ertifiziert`)
	registerAdditionalSugRepl(`gerähten?`, `geräht`, `Gerät`)
	registerAdditionalSugRepl(`leptops?`, `lep`, `Lap`)
	registerAdditionalSugRepl(`[pP]ie?rsings?`, `[pP]ie?rsing`, `Piercing`)
	registerAdditionalSugRepl(`for?melar(en?)?`, `for?me`, `Formu`)
	registerAdditionalSugRepl(`näste[mnrs]?$`, `^näs`, `nächs`)
	registerAdditionalSugRepl(`Erdogans?$`, `^Erdogan`, `Erdoğan`)
	registerAdditionalSugRepl(`Germanistikerin(nen)?`, `Germanistiker`, `Germanist`)
	registerAdditionalSugRepl(`[iI]ns?z[ie]nie?rung(en)?`, `[iI]ns?z[ie]nie?`, `Inszenie`)
	registerAdditionalSugRepl(`[eE]rhöherung(en)?`, `[eE]rhöherung`, `Erhöhung`)
	registerAdditionalSugRepl(`[vV]erspäterung(en)?`, `später`, `spät`)
	registerAdditionalSugRepl(`[vV]orallendingen`, `orallendingen`, `or allen Dingen`)
	registerAdditionalSugRepl(`[aA]ufjede[nm]fall`, `jede[nm]fall$`, ` jeden Fall`)
	registerAdditionalSugRepl(`[aA]us[vf]ersehen[dt]lich`, `[vf]ersehen[dt]lich`, ` Versehen`)
	registerAdditionalSugRepl(`^funk?z[ou]nier.+`, `funk?z[ou]nier`, `funktionier`)
	registerAdditionalSugRepl(`[wW]öruber`, `öru`, `orü`)
	registerAdditionalSugRepl(`[lL]einensamens?`, `[lL]einen`, `Lein`)
	registerAdditionalSugRepl(`Feinleiner[ns]?`, `Feinlei`, `Fineli`)
	registerAdditionalSugRepl(`[hH]eilei[td]s?`, `[hH]eilei[td]`, `Highlight`)
	registerAdditionalSugRepl(`Oldheimer[ns]?`, `he`, `t`)
	registerAdditionalSugRepl(`[tT]räner[ns]?`, `[tT]rä`, `Trai`)
	registerAdditionalSugRepl(`[tT]eimings?`, `[tT]e`, `T`)
	registerAdditionalSugRepl(`unternehmensl[uü]stig(e[mnrs]?)?`, `mensl[uü]st`, `mungslust`)
	registerAdditionalSugRepl(`proff?ess?ional(e[mnrs]?)?`, `ff?ess?ional`, `fessionell`)
	registerAdditionalSugRepl(`zuverlässlich(e[mnrs]?)?`, `lich`, `ig`)
	registerAdditionalSugRepl(`fluoreszenzierend(e[mnrs]?)?`, `zen`, ``)
	registerAdditionalSugRepl(`revalierend(e[mnrs]?)?`, `^reval`, `rivalis`)
	registerAdditionalSugRepl(`verhäuft(e[mnrs]?)?`, `^ver`, `ge`)
	registerAdditionalSugRepl(`stürmig(e[mnrs]?)?`, `mig`, `misch`)
	registerAdditionalSugRepl(`größeste[mnrs]?`, `ßes`, `ß`)
	registerAdditionalSugRepl(`n[aä]heste[mnrs]?`, `n[aä]he`, `näch`)
	registerAdditionalSugRepl(`gesundlich(e[mnrs]?)?`, `lich`, `heitlich`)
	registerAdditionalSugRepl(`eckel(e|t(en?)?|st)?`, `^eck`, `ek`)
	registerAdditionalSugRepl(`unhervorgesehen(e[mnrs]?)?`, `hervor`, `vorher`)
	registerAdditionalSugRepl(`entt?euscht(e[mnrs]?)?`, `entt?eusch`, `enttäusch`)
	registerAdditionalSugRepl(`Phählen?`, `^Ph`, `Pf`)
	registerAdditionalSugRepl(`Kattermesser[ns]?`, `Ka`, `Cu`)
	registerAdditionalSugRepl(`gehe?rr?t(e[mnrs]?)?`, `he?rr?`, `ehr`)
	registerAdditionalSugRepl(`gehrter?`, `^ge`, `gee`)
	registerAdditionalSugRepl(`[nN]amenhaft(e[mnrs]?)?`, `amen`, `am`)
	registerAdditionalSugRepl(`hom(o?e|ö)ophatisch(e[mnrs]?)?`, `hom(o?e|ö)ophat`, `homöopath`)
	registerAdditionalSugRepl(`Geschwindlichkeit(en)?`, `lich`, `ig`)
	registerAdditionalSugRepl(`Jänners?`, `Jänner`, `Januar`)
	registerAdditionalSugRepl(`[äÄ]hlich(e[mnrs]?)?`, `lich`, `nlich`)
	registerAdditionalSugRepl(`entf[ai]ngen?`, `ent`, `emp`)
	registerAdditionalSugRepl(`entf[äi]ngs?t`, `ent`, `emp`)
	registerAdditionalSugRepl(`[Bb]ehilfreich(e[rnms]?)`, `reich`, `lich`)
	registerAdditionalSugRepl(`[Bb]zgl`, `zgl`, `zgl.`)
	registerAdditionalSugRepl(`kaltnass(e[rnms]?)`, `kaltnass`, `nasskalt`)
	registerAdditionalSugRepl(`Kaltnass(e[rnms]?)`, `Kaltnass`, `Nasskalt`)
	registerAdditionalSugRepl(`[eE]rhaltbar(e[mnrs]?)?`, `haltbar`, `hältlich`)
	registerAdditionalSugRepl(`[aA]ufkeinenfall?`, `keinenfall?`, ` keinen Fall`)
	registerAdditionalSugRepl(`[Dd]rumrum`, `rum$`, `herum`)
	registerAdditionalSugRepl(`([uU]n)?proff?esionn?ell?(e[mnrs]?)?`, `proff?esionn?ell?`, `professionell`)
	registerAdditionalSugRepl(`[kK]inderlich(e[mnrs]?)?`, `inder`, `ind`)
	registerAdditionalSugRepl(`[wW]iedersprichs?t`, `ieder`, `ider`)
	registerAdditionalSugRepl(`[wW]hite-?[Ll]abels`, `[wW]hite-?[Ll]abel`, `White Label`)
	registerAdditionalSugRepl(`[wW]iederstand`, `ieder`, `ider`)
	registerAdditionalSugRepl(`[kK]önntes`, `es$`, `est`)
	registerAdditionalSugRepl(`[aA]ssess?oare?s?`, `[aA]ssess?oare?`, `Accessoire`)
	registerAdditionalSugRepl(`indifiziert(e[mnrs]?)?`, `ind`, `ident`)
	registerAdditionalSugRepl(`dreite[mnrs]?`, `dreit`, `dritt`)
	registerAdditionalSugRepl(`verblüte[mnrs]?`, `blü`, `blüh`)
	registerAdditionalSugRepl(`Einzigste[mnrs]?`, `zigst`, `zig`)
	registerAdditionalSugRepl(`Invests?`, `Invest`, `Investment`)
	registerAdditionalSugRepl(`(aller)?einzie?gste[mnrs]?`, `(aller)?einzie?gst`, `einzig`)
	registerAdditionalSugRepl(`[iI]nterkurell(e[nmrs]?)?`, `ku`, `kultu`)
	registerAdditionalSugRepl(`[iI]ntersannt(e[mnrs]?)?`, `sannt`, `essant`)
	registerAdditionalSugRepl(`ubera(g|sch)end(e[nmrs]?)?`, `uber`, `überr`)
	registerAdditionalSugRepl(`[Hh]ello`, `ello`, `allo`)
	registerAdditionalSugRepl(`[Gg]etagged`, `gged`, `ggt`)
	registerAdditionalSugRepl(`[wW]olt$`, `lt`, `llt`)
	registerAdditionalSugRepl(`[zZ]uende`, `ue`, `u E`)
	registerAdditionalSugRepl(`[iI]nbälde`, `nb`, `n B`)
	registerAdditionalSugRepl(`[lL]etztenendes`, `ene`, `en E`)
	registerAdditionalSugRepl(`[nN]achwievor`, `wievor`, ` wie vor`)
	registerAdditionalSugRepl(`[zZ]umbeispiel`, `beispiel`, ` Beispiel`)
	registerAdditionalSugRepl(`[gG]ottseidank`, `[gG]ottseidank`, `Gott sei Dank`)
	registerAdditionalSugRepl(`[gG]rundauf`, `[gG]rundauf`, `Grund auf`)
	registerAdditionalSugRepl(`[aA]nsichtnach`, `[aA]nsicht`, `Ansicht `)
	registerAdditionalSugRepl(`[uU]n[sz]war`, `[sz]war`, `d zwar`)
	registerAdditionalSugRepl(`[wW]aschte(s?t)?`, `aschte`, `usch`)
	registerAdditionalSugRepl(`[wW]aschten`, `ascht`, `usch`)
	registerAdditionalSugRepl(`Probiren?`, `ir`, `ier`)
	registerAdditionalSugRepl(`[gG]esetztreu(e[nmrs]?)?`, `tz`, `tzes`)
	registerAdditionalSugRepl(`[wW]ikich(e[nmrs]?)?`, `k`, `rkl`)
	registerAdditionalSugRepl(`[uU]naufbesichtigt(e[nmrs]?)?`, `aufbe`, `beauf`)
	registerAdditionalSugRepl(`[nN]utzvoll(e[nmrs]?)?`, `utzvoll`, `ützlich`)
	registerAdditionalSugRepl(`Lezte[mnrs]?`, `Lez`, `Letz`)
	registerAdditionalSugRepl(`Letze[mnrs]?`, `Letz`, `Letzt`)
	registerAdditionalSugRepl(`[nN]i[vw]os?`, `[nN]i[vw]o`, `Niveau`)
	registerAdditionalSugRepl(`[dD]illetant(en)?`, `[dD]ille`, `Dilet`)
	registerAdditionalSugRepl(`Frauenhofer-(Institut|Gesellschaft)`, `Frauen`, `Fraun`)
	registerAdditionalSugRepl(`Add-?Ons?`, `Add-?On`, `Add-on`)
	registerAdditionalSugRepl(`Addons?`, `on`, `-on`)
	registerAdditionalSugRepl(`Internetkaffees?`, `kaffee`, `café`)
	registerAdditionalSugRepl(`[gG]ehorsamkeitsverweigerung(en)?`, `[gG]ehorsamkeit`, `Gehorsam`)
	registerAdditionalSugRepl(`[wW]ochende[ns]?`, `[wW]ochend`, `Wochenend`)
	registerAdditionalSugRepl(`[kK]ongratulier(en?|t(en?)?|st)`, `[kK]on`, ``)
	registerAdditionalSugRepl(`[wWkKdD]an$`, `n$`, `nn`)
	registerAdditionalSugRepl(`geh?neh?m[ie]gung(en)?`, `geh?neh?m[ie]gung`, `Genehmigung`)
	registerAdditionalSugRepl(`Korrigierung(en)?`, `igierung`, `ektur`)
	registerAdditionalSugRepl(`[kK]orregierung(en)?`, `[kK]orregierung`, `Korrektur`)
	registerAdditionalSugRepl(`[kK]orrie?girung(en)?`, `[kK]orrie?girung`, `Korrektur`)
	registerAdditionalSugRepl(`[nN]ocheimal`, `eimal`, ` einmal`)
	registerAdditionalSugRepl(`[aA]benzu`, `enzu`, ` und zu`)
	registerAdditionalSugRepl(`[kK]onflikation(en)?`, `[kK]onfli`, `Kompli`)
	registerAdditionalSugRepl(`[mM]itanader`, `ana`, `einan`)
	registerAdditionalSugRepl(`[mM]itenand`, `enand`, `einander`)
	registerAdditionalSugRepl(`Gelangenheitsbestätigung(en)?`, `heit`, ``)
	registerAdditionalSugRepl(`[jJ]edwillige[mnrs]?`, `willig`, `wed`)
	registerAdditionalSugRepl(`[qQ]ualitäts?bewußt(e[mnrs]?)?`, `ts?bewußt`, `tsbewusst`)
	registerAdditionalSugRepl(`[vV]oraussichtig(e[nmrs]?)?`, `sichtig`, `sichtlich`)
	registerAdditionalSugRepl(`[gG]leichrechtig(e[nmrs]?)?`, `rechtig`, `berechtigt`)
	registerAdditionalSugRepl(`[uU]nnützlich(e[nmrs]?)?`, `nützlich`, `nütz`)
	registerAdditionalSugRepl(`[uU]nzerbrechbar(e[nmrs]?)?`, `bar`, `lich`)
	registerAdditionalSugRepl(`kolegen?`, `ko`, `Kol`)
	registerAdditionalSugRepl(`tableten?`, `tablet`, `Tablett`)
	registerAdditionalSugRepl(`verswinde(n|s?t)`, `^vers`, `versch`)
	registerAdditionalSugRepl(`unverantwortungsvoll(e[nmrs]?)?`, `unverantwortungsvoll`, `verantwortungslos`)
	registerAdditionalSugRepl(`[gG]erechtlichkeit`, `[gG]erechtlich`, `Gerechtig`)
	registerAdditionalSugRepl(`[zZ]uverlässlichkeit`, `lich`, `ig`)
	registerAdditionalSugRepl(`[uU]nverzeilig(e[mnrs]?)?`, `zeilig`, `zeihlich`)
	registerAdditionalSugRepl(`[zZ]uk(ue?|ü)nftlich(e[mnrs]?)?`, `uk(ue?|ü)nftlich`, `ukünftig`)
	registerAdditionalSugRepl(`[rR]eligiösisch(e[nmrs]?)?`, `isch`, ``)
	registerAdditionalSugRepl(`[fF]olklorisch(e[nmrs]?)?`, `isch`, `istisch`)
	registerAdditionalSugRepl(`[eE]infühlsvoll(e[nmrs]?)?`, `voll`, `am`)
	registerAdditionalSugRepl(`Unstimmlichkeit(en)?`, `lich`, `ig`)
	registerAdditionalSugRepl(`Strebergartens?`, `Stre`, `Schre`)
	registerAdditionalSugRepl(`[hH]ähern(e[mnrs]?)?`, `ähern`, `ären`)
	registerAdditionalSugRepl(`todesbedroh(end|lich)(e[nmrs]?)?`, `todes`, `lebens`)
	registerAdditionalSugRepl(`^[uU]nabsichtig(e[nmrs]?)?`, `ig`, `lich`)
	registerAdditionalSugRepl(`[aA]ntisemitistisch(e[mnrs]?)?`, `tist`, `t`)
	registerAdditionalSugRepl(`[uU]nvorsehbar(e[mnrs]?)?`, `vor`, `vorher`)
	registerAdditionalSugRepl(`([eE]r|[bB]e|unter|[aA]uf)?hälst`, `hälst`, `hältst`)
	registerAdditionalSugRepl(`[sS]chmett?e?rling(s|en?)?`, `[sS]chmett?e?rling`, `Schmetterling`)
	registerAdditionalSugRepl(`^[eE]inlamie?nie?r(st|en?|(t(e[nmrs]?)?))?`, `^einlamie?nie?r`, `laminier`)
	registerAdditionalSugRepl(`[bB]ravurös(e[nrms]?)?`, `vur`, `vour`)
	registerAdditionalSugRepl(`[aA]ss?ecoires?`, `[aA]ss?ec`, `Access`)
	registerAdditionalSugRepl(`[aA]ufwechse?lungsreich(er|st)?(e[nmrs]?)?`, `ufwechse?lung`, `bwechslung`)
	registerAdditionalSugRepl(`[iI]nordnung`, `ordnung`, ` Ordnung`)
	registerAdditionalSugRepl(`[iI]mmoment`, `moment`, ` Moment`)
	registerAdditionalSugRepl(`[hH]euteabend`, `abend`, ` Abend`)
	registerAdditionalSugRepl(`[wW]ienerschnitzel[ns]?`, `[wW]ieners`, `Wiener S`)
	registerAdditionalSugRepl(`[sS]chwarzwälderkirschtorten?`, `[sS]chwarzwälderk`, `Schwarzwälder K`)
	registerAdditionalSugRepl(`[kK]oxial(e[nmrs]?)?`, `x`, `ax`)
	registerAdditionalSugRepl(`([üÜ]ber|[uU]unter)?[dD]urs?chnitt?lich(e[nmrs]?)?`, `s?chnitt?`, `chschnitt`)
	registerAdditionalSugRepl(`[dD]urs?chnitts?`, `s?chnitt`, `chschnitt`)
	registerAdditionalSugRepl(`[sS]triktlich(e[mnrs]?)?`, `lich`, ``)
	registerAdditionalSugRepl(`[hH]öchstwahrlich(e[mnrs]?)?`, `wahr`, `wahrschein`)
	registerAdditionalSugRepl(`[oO]rganisativ(e[nmrs]?)?`, `tiv`, `torisch`)
	registerAdditionalSugRepl(`[kK]ontaktfreundlich(e[nmrs]?)?`, `ndlich`, `dig`)
	registerAdditionalSugRepl(`Helfer?s-Helfer[ns]?`, `Helfer?s-H`, `Helfersh`)
	registerAdditionalSugRepl(`[iI]ntell?igentsbestien?`, `[iI]ntell?igents`, `Intelligenz`)
	registerAdditionalSugRepl(`[aA]vantgardisch(e[mnrs]?)?`, `gard`, `gardist`)
	registerAdditionalSugRepl(`[gG]ewohnheitsbedürftig(e[mnrs]?)?`, `wohnheit`, `wöhnung`)
	registerAdditionalSugRepl(`[eE]infühlungsvoll(e[mnrs]?)?`, `fühlungsvoll`, `fühlsam`)
	registerAdditionalSugRepl(`[vV]erwant(e[mnrs]?)?`, `want`, `wandt`)
	registerAdditionalSugRepl(`[bB]eanstandigung(en)?`, `ig`, ``)
	registerAdditionalSugRepl(`[eE]inba(hn|nd)frei(e[mnrs]?)?`, `ba(hn|nd)`, `wand`)
	registerAdditionalSugRepl(`[äÄaAeE]rtzten?`, `[äÄaAeE]rt`, `Är`)
	registerAdditionalSugRepl(`pdf-Datei(en)?`, `pdf`, `PDF`)
	registerAdditionalSugRepl(`rumänern?`, `rumäner`, `Rumäne`)
	registerAdditionalSugRepl(`[cCKk]o?usengs?`, `[cCKk]o?useng`, `Cousin`)
	registerAdditionalSugRepl(`Influenzer(in(nen)?|[ns])?`, `zer`, `cer`)
	registerAdditionalSugRepl(`[vV]ersantdienstleister[ns]?`, `[vV]ersant`, `Versand`)
	registerAdditionalSugRepl(`[pP]atrolier(s?t|t?en?)`, `atrolier`, `atrouillier`)
	registerAdditionalSugRepl(`[pP]ropagandiert(e[mnrs]?)?`, `and`, ``)
	registerAdditionalSugRepl(`[pP]ropagandier(en|st)`, `and`, ``)
	registerAdditionalSugRepl(`[kK]app?erzität(en)?`, `^[kK]app?er`, `Kapa`)
	registerAdditionalSugRepl(`känzel(n|s?t)`, `känzel`, `cancel`)
	registerAdditionalSugRepl(`[üÜ]berstreitung(en)?`, `[üÜ]berst`, `Übersch`)
	registerAdditionalSugRepl(`anschliess?lich(e(mnrs)?)?`, `anschliess?lich`, `anschließend`)
	registerAdditionalSugRepl(`[rR]ethorisch(e(mnrs)?)?`, `eth`, `het`)
	registerAdditionalSugRepl(`änlich(e(mnrs)?)?`, `än`, `ähn`)
	registerAdditionalSugRepl(`spätmöglichste(mnrs)?`, `spätmöglichst`, `spätestmöglich`)
	registerAdditionalSugRepl(`[Ll]ilane[srm]?`, `ilane[srm]?`, `ila`)
	registerAdditionalSugRepl(`[zZ]uguterletzt`, `guterletzt`, ` guter Letzt`)
	registerAdditionalSugRepl(`Nootbooks?`, `Noot`, `Note`)
	registerAdditionalSugRepl(`[vV]ersendlich(e[mnrs]?)?`, `send`, `sehent`)
	registerAdditionalSugRepl(`[uU]nfäh?r(e[mnrs]?)?`, `fäh?r`, `fair`)
	registerAdditionalSugRepl(`[mM]edikatös(e[mnrs]?)?`, `ka`, `kamen`)
	registerAdditionalSugRepl(`(ein|zwei|drei|vier|fünf|sechs|sieben|acht|neun|zehn|elf|zwölf)undhalb`, `und`, `ein`)
	registerAdditionalSugRepl(`[gG]roßzüge[mnrs]?`, `züg`, `zügig`)
	registerAdditionalSugRepl(`[äÄ]rtlich(e[mnrs]?)?`, `rt`, `rzt`)
	registerAdditionalSugRepl(`[sS]chnelligkeitsfehler[ns]?`, `[sS]chnell`, `Flücht`)
	registerAdditionalSugRepl(`[sS]chweinerosane[mnrs]?`, `weinerosane[mnrs]?`, `weinchenrosa`)
	registerAdditionalSugRepl(`[aA]nstecklich(e[mnrs]?)?`, `lich`, `end`)
	registerAdditionalSugRepl(`[gG]eflechtet(e[mnrs]?)?`, `flechtet`, `flochten`)
	registerAdditionalSugRepl(`[gG]enrealistisch(e[mnrs]?)?`, `re`, `er`)
	registerAdditionalSugRepl(`überträgt(e[mnrs]?)?`, `^überträgt`, `übertragen`)
	registerAdditionalSugRepl(`[iI]nterresent(e[mnrs]?)?`, `rresent`, `ressant`)
	registerAdditionalSugRepl(`Simkartenleser[ns]?`, `^Simkartenl`, `SIM-Karten-L`)
	registerAdditionalSugRepl(`Hilfstmittel[ns]?`, `^Hilfst`, `Hilfs`)
	registerAdditionalSugRepl(`trationell(e[mnrs]?)?`, `^tra`, `tradi`)
	registerAdditionalSugRepl(`[bB]erreichs?`, `^[bB]er`, `Be`)
	registerAdditionalSugRepl(`[fF]uscher[ns]?`, `^[fF]u`, `Pfu`)
	registerAdditionalSugRepl(`[uU]nausweichbar(e[mnrs]?)?`, `bar`, `lich`)
	registerAdditionalSugRepl(`[uU]nabdinglich(e[mnrs]?)?`, `lich`, `bar`)
	registerAdditionalSugRepl(`[eE]ingänglich(e[mnrs]?)?`, `lich`, `ig`)
	registerAdditionalSugRepl(`ausgewöh?nlich(e[mnrs]?)?`, `^ausgewöh?n`, `außergewöhn`)
	registerAdditionalSugRepl(`achsial(e[mnrs]?)?`, `^achs`, `ax`)
	registerAdditionalSugRepl(`famielen?`, `^famiel`, `Famili`)
	registerAdditionalSugRepl(`miter[ns]?`, `^mi`, `Mie`)
	registerAdditionalSugRepl(`besig(t(e[mnrs]?)?|en?)`, `sig`, `sieg`)
	registerAdditionalSugRepl(`[vV]erziehr(t(e[mnrs]?)?|en?)`, `ieh`, `ie`)
	registerAdditionalSugRepl(`^[pP]iek(s?t|en?)`, `iek`, `ik`)
	registerAdditionalSugRepl(`[mM]atschscheiben?`, `[mM]atschsch`, `Mattsch`)
	registerAdditionalSugRepl(`[hH]ofen?`, `of`, `off`)
	registerAdditionalSugRepl(`[sS]ommerverien?`, `[sS]ommerverien?`, `Sommerferien`)
	registerAdditionalSugRepl(`[rR]ecourcen?`, `[rR]ec`, `Ress`)
	registerAdditionalSugRepl(`[fF]amm?ill?i?[aä]risch(e[mnrs]?)?`, `amm?ill?i?[aä]risch`, `amiliär`)
	registerAdditionalSugRepl(`Sim-Karten?`, `^Sim`, `SIM`)
	registerAdditionalSugRepl(`Spax-Schrauben?`, `^Spax`, `SPAX`)
	registerAdditionalSugRepl(`[aA]leine`, `l`, `ll`)
	registerAdditionalSugRepl(`Kaput`, `t`, `tt`)
	registerAdditionalSugRepl(`[fF]estell(s?t|en?)`, `est`, `estst`)
	registerAdditionalSugRepl(`[Ee]igtl`, `igtl`, `igtl.`)
	registerAdditionalSugRepl(`(Baden-)?Würtenbergs?`, `Würten`, `Württem`)
	registerAdditionalSugRepl(`Betriebsratzimmer[ns]?`, `rat`, `rats`)
	registerAdditionalSugRepl(`Rechts?schreibungsfehler[ns]?`, `Rechts?schreibungs`, `Rechtschreib`)
	registerAdditionalSugRepl(`Open[aA]ir-Konzert(en?)?`, `Open[aA]ir`, `Open-Air`)
	registerAdditionalSugRepl(`Jugenschuhen?`, `Jug`, `Jung`)
	registerAdditionalSugRepl(`TODO-Listen?`, `TODO`, `To-do`)
	registerAdditionalSugRepl(`ausiehs?t`, `aus`, `auss`)
	registerAdditionalSugRepl(`unterbemittel(nd|t)(e[nmrs]?)?`, `unterbemittel(nd|t)`, `minderbemittelt`)
	registerAdditionalSugRepl(`[xX]te[mnrs]?`, `te`, `-te`)
	registerAdditionalSugRepl(`verheielt(e[mnrs]?)?`, `heiel`, `heil`)
	registerAdditionalSugRepl(`[rR]evolutionie?sier(s?t|en?)`, `ie?s`, ``)
	registerAdditionalSugRepl(`Kohleaustiegs?`, `aus`, `auss`)
	registerAdditionalSugRepl(`[jJ]urististisch(e[mnrs]?)?`, `istist`, `ist`)
	registerAdditionalSugRepl(`gehäckelt(e[nmrs]?)?`, `ck`, `k`)
	registerAdditionalSugRepl(`deutsprachig(e[nmrs]?)?`, `deut`, `deutsch`)
	registerAdditionalSugRepl(`angesehend(st)?e[nmrs]?`, `end`, `en`)
	registerAdditionalSugRepl(`[iI]slamophobisch(e[mnrs]?)?`, `isch`, ``)
	registerAdditionalSugRepl(`[vV]erharkt(e[mnrs]?)?`, `ar`, `a`)
	registerAdditionalSugRepl(`[dD]esöfterer?[nm]`, `öfterer?[nm]`, ` Öfteren`)
	registerAdditionalSugRepl(`[dD]eswei[dt]ere?[mn]`, `wei[dt]ere?[mn]`, ` Weiteren`)
	registerAdditionalSugRepl(`Einkaufstachen?`, `ch`, `sch`)
	registerAdditionalSugRepl(`Bortmesser[ns]?`, `Bor`, `Bro`)
	registerAdditionalSugRepl(`Makeupstylist(in(nen)?|en)?`, `Makeups`, `Make-up-S`)
	registerAdditionalSugRepl(`Fee?dbäcks?`, `Fee?dbäck`, `Feedback`)
	registerAdditionalSugRepl(`weirete[nmrs]?`, `ret`, `ter`)
	registerAdditionalSugRepl(`Ni[vw]oschalter[ns]?`, `Ni[vw]o`, `Niveau`)
	registerAdditionalSugRepl(`[eE]xhibitionisch(e[nmrs]?)?`, `isch`, `istisch`)
	registerAdditionalSugRepl(`(ein|aus)?[gG]eschalten(e[nmrs]?)?`, `ten`, `tet`)
	registerAdditionalSugRepl(`[uU]nterschiebene[nmrs]?`, `sch`, `schr`)
	registerAdditionalSugRepl(`[uU]nbequemlich(st)?e[nmrs]?`, `lich`, ``)
	registerAdditionalSugRepl(`[uU][nm]bekweh?m(e[nmrs]?)?`, `[nm]bekweh?m`, `nbequem`)
	registerAdditionalSugRepl(`[dD]esatör(s|en?)?`, `satör`, `serteur`)
	registerAdditionalSugRepl(`(ge)?fr[uü]h?st[uü](c?k|g)t`, `fr[uü]h?st[uü](c?k|g)t`, `frühstückt`)
	registerAdditionalSugRepl(`Ballets?`, `llet`, `llett`)
	registerAdditionalSugRepl(`Saudiarabiens?`, `Saudiarabien`, `Saudi-Arabien`)
	registerAdditionalSugRepl(`eMail-Adressen?`, `eMail-`, `E-Mail-`)
	registerAdditionalSugRepl(`[Ww]ieviele?`, `ieviel`, `ie viel`)
	registerAdditionalSugRepl(`[Aa]dhoc`, `dhoc`, `d hoc`)
	registerAdditionalSugRepl(`Todos?`, `Todo`, `To-do`)
	registerAdditionalSugRepl(`blog(t?en?|t(es?t)?)$`, `g`, `gg`)
	registerAdditionalSugRepl(`gewertschätzte(([mnrs]|re[mnrs]?)?)$`, `gewertschätzt`, `wertgeschätzt`)
	registerAdditionalSugRepl(`knapps(t?en?|t(es?t)?)$`, `pp`, `p`)
	registerAdditionalSugRepl(`gepiekste[mnrs]?$`, `ie`, `i`)
	registerAdditionalSugRepl(`Yings?`, `ng`, `n`)
	registerAdditionalSugRepl(`veganisch(e?[mnrs]?)$`, `isch`, ``)
	registerAdditionalSugRepl(`totlangweiligste[mnrs]?$`, `tot`, `tod`)
	registerAdditionalSugRepl(`tottraurigste[mnrs]?$`, `tot`, `tod`)
	registerAdditionalSugRepl(`kreir(n|e?nd)(e[mnrs]?)?$`, `ire?n`, `ieren`)
	registerAdditionalSugRepl(`Pepps?`, `pp`, `p`)
	registerAdditionalSugRepl(`Pariahs?`, `h`, ``)
	registerAdditionalSugRepl(`Oeuvres?`, `Oe`, `Œ`)
	registerAdditionalSugRepl(`infisziertes?t$`, `fisz`, `fiz`)
	registerAdditionalSugRepl(`Imbusse(n|s)?$`, `m`, `n`)
	registerAdditionalSugRepl(`handgehabt(e?[mnrs]?)?$`, `handgehabt`, `gehandhabt`)
	registerAdditionalSugRepl(`fitzuhalten(de?[mnrs]?)?$`, `fitzuhalten`, `fit zu halten`)
	registerAdditionalSugRepl(`(essen|schlafen|schwimmen|spazieren)zugehen$`, `zugehen`, ` zu gehen`)
	registerAdditionalSugRepl(`dilettante[mnrs]?$`, `te`, `tische`)
	registerAdditionalSugRepl(`Brandwein(en?|s)$`, `d`, `nt`)
	registerAdditionalSugRepl(`Böhen?$`, `h`, ``)
	registerAdditionalSugRepl(`Aufständige[mnr]?$`, `ig`, `isch`)
	registerAdditionalSugRepl(`aufständig(e[mnrs]?)?$`, `ig`, `isch`)
	registerAdditionalSugRepl(`duzend(e[mnrs]?)?$`, `uzend`, `utzend`)
	registerAdditionalSugRepl(`unrelevant(e[mnrs]?)?$`, `un`, `ir`)
	registerAdditionalSugRepl(`Unrelevant(e[mnrs]?)?$`, `Un`, `Ir`)
	registerAdditionalSugRepl(`[oO]rdnungswiedrichkeit(en)?`, `[oO]rdnungswiedrich`, `Ordnungswidrig`)
	registerAdditionalSugRepl(`Mauntenbiker[ns]?`, `^Maunten`, `Mountain`)
	registerAdditionalSugRepl(`Mauntenbikes?`, `Maunten`, `Mountain`)
	registerAdditionalSugRepl(`[nN]euhichkeit(en)?`, `[nN]euhich`, `Neuig`)
	registerAdditionalSugRepl(`Prokopfverbrauchs?`, `Prokopfv`, `Pro-Kopf-V`)
	registerAdditionalSugRepl(`[Gg]ilst`, `ilst`, `iltst`)
	registerAdditionalSugRepl(`[vV]ollrichtung(en)?`, `[vV]oll`, `Ver`)
	registerAdditionalSugRepl(`[vV]ollrichtest`, `oll`, `er`)
	registerAdditionalSugRepl(`[vV]ollrichten?`, `oll`, `er`)
	registerAdditionalSugRepl(`[vV]ollrichtet(e([mnrs])?)?`, `oll`, `er`)
	registerAdditionalSugRepl(`[bB]edingslos(e([mnrs])?)?`, `ding`, `dingung`)
	registerAdditionalSugRepl(`[eE]insichtbar(e[mnrs]?)?`, `sicht`, `seh`)
	registerAdditionalSugRepl(`asymetrisch(ere|ste)[mnrs]?$`, `ym`, `ymm`)
	registerAdditionalSugRepl(`alterwürdig(ere|ste)[mnrs]?$`, `lter`, `ltehr`)
	registerAdditionalSugRepl(`aufständig(ere|ste)[mnrs]?$`, `ig`, `isch`)
	registerAdditionalSugRepl(`blutdurstig(ere|ste)[mnrs]?$`, `ur`, `ür`)
	registerAdditionalSugRepl(`dilettant(ere|este)[mnrs]?$`, `nt`, `ntisch`)
	registerAdditionalSugRepl(`eliptisch(ere|ste)[mnrs]?$`, `l`, `ll`)
	registerAdditionalSugRepl(`angegröhlt(e([mnrs])?)?$`, `öh`, `ö`)
	registerAdditionalSugRepl(`gothisch(ere|ste)[mnrs]?$`, `th`, `t`)
	registerAdditionalSugRepl(`kollossal(ere|ste)[mnrs]?$`, `ll`, `l`)
	registerAdditionalSugRepl(`paralel(lere|lste)[mnrs]?$`, `paralel`, `paralle`)
	registerAdditionalSugRepl(`symetrischste[mnrs]?$`, `ym`, `ymm`)
	registerAdditionalSugRepl(`rethorisch(ere|ste)[mnrs]?$`, `rethor`, `rhetor`)
	registerAdditionalSugRepl(`repetativ(ere|ste)[mnrs]?$`, `repetat`, `repetit`)
	registerAdditionalSugRepl(`voluptös(e|ere|este)?[mnrs]?$`, `tös`, `tuös`)
	registerAdditionalSugRepl(`[pP]flanzig(e[mnrs]?)?`, `ig`, `lich`)
	registerAdditionalSugRepl(`geblogt(e[mnrs]?)?$`, `gt`, `ggt`)
	registerAdditionalSugRepl(`herraus.*`, `herraus`, `heraus`)
	registerAdditionalSugRepl(`[aA]bbonier(en?|s?t|te[mnrst]?)`, `bbo`, `bon`)
	registerAdditionalSugRepl(`[aA]pelier(en?|s?t|te[nt]?)`, `pel`, `ppell`)
	registerAdditionalSugRepl(`[vV]oltie?schier(en?|s?t|te[nt]?)`, `ie?sch`, `ig`)
	registerAdditionalSugRepl(`[mM]eistverkaufteste[mnrs]?`, `teste`, `te`)
	registerAdditionalSugRepl(`[uU]nleshaft(e[mnrs]?)?`, `haft`, `erlich`)
	registerAdditionalSugRepl(`[gG]laubenswürdig(e[mnrs]?)?`, `ens`, ``)
	registerAdditionalSugRepl(`[nN]i[vw]ovoll(e[mnrs]?)?`, `[vw]ovoll`, `veauvoll`)
	registerAdditionalSugRepl(`[nN]otgezwungend?(e[mnrs]?)?`, `zwungend?`, `drungen`)
	registerAdditionalSugRepl(`[mM]isstraurig(e[mnrs]?)?`, `rig`, `isch`)
	registerAdditionalSugRepl(`[iI]nflagrantie?`, `flagrantie?`, ` flagranti`)
	registerAdditionalSugRepl(`Aux-Anschl(uss(es)?|üssen?)`, `Aux`, `AUX`)
	registerAdditionalSugRepl(`desinfektiert(e[mnrs]?)?`, `fekt`, `fiz`)
	registerAdditionalSugRepl(`desinfektierend(e[mnrs]?)?`, `fekt`, `fiz`)
	registerAdditionalSugRepl(`desinfektieren?`, `fekt`, `fiz`)
	registerAdditionalSugRepl(`[dD]esinfektionier(en?|t(e[mnrs]?)?|st)`, `fektionier`, `fizier`)
	registerAdditionalSugRepl(`[dD]esinfektionierend(e[mnrs]?)?`, `fektionier`, `fizier`)
	registerAdditionalSugRepl(`[kK]ompensionier(en?|t(e[mnrs]?)?|st)`, `ion`, ``)
	registerAdditionalSugRepl(`neuliche[mnrs]?`, `neu`, `neuer`)
	registerAdditionalSugRepl(`ausbüchsen?`, `chs`, `x`)
	registerAdditionalSugRepl(`aus(ge)?büchst(en?)?`, `chs`, `x`)
	registerAdditionalSugRepl(`innoff?iziell?(e[mnrs]?)?`, `innoff?iziell?`, `inoffiziell`)
	registerAdditionalSugRepl(`[gG]roesste[mnrs]?`, `oess`, `öß`)
	registerAdditionalSugRepl(`[tT]efonisch(e[mnrs]?)?`, `efon`, `elefon`)
	registerAdditionalSugRepl(`[oO]ptimalisiert`, `alis`, ``)
	registerAdditionalSugRepl(`[iI]ntrovertisch(e[mnrs]?)?`, `isch`, `iert`)
	registerAdditionalSugRepl(`[aA]miert(e[mnrs]?)?`, `mi`, `rmi`)
	registerAdditionalSugRepl(`[vV]ersiehrt(e[mnrs]?)?`, `h`, ``)
	registerAdditionalSugRepl(`[dD]urchsichtbar(e[mnrs]?)?`, `bar`, `ig`)
	registerAdditionalSugRepl(`[oO]ffensichtig(e[mnrs]?)?`, `ig`, `lich`)
	registerAdditionalSugRepl(`[zZ]urverfühgung`, `verfühgung`, ` Verfügung`)
	registerAdditionalSugRepl(`[sS]pendeangebot(e[ns]?)?`, `[sS]pende`, `Spenden`)
	registerAdditionalSugRepl(`gahrnichts?`, `gahr`, `gar `)
	registerAdditionalSugRepl(`[aA]ugensichtlich(e[mnrs]?)?`, `sicht`, `schein`)
	registerAdditionalSugRepl(`[lL]eidensvoll(e[mnrs]?)?`, `ens`, ``)
	registerAdditionalSugRepl(`[bB]ewusstlich(e[mnrs]?)?`, `lich`, ``)
	registerAdditionalSugRepl(`[vV]erschmerzlich(e[mnrs]?)?`, `lich`, `bar`)
	registerAdditionalSugRepl(`Krankenbruders?`, `bruder`, `pfleger`)
	registerAdditionalSugRepl(`Krankenbrüdern?`, `brüder`, `pfleger`)
	registerAdditionalSugRepl(`Lan-(Kabel[ns]?|Verbindung)`, `Lan`, `LAN`)
	registerAdditionalSugRepl(`[sS]epalastschriftmandat(s|en?)?`, `[sS]epal`, `SEPA-L`)
	registerAdditionalSugRepl(`Pinn?eingaben?`, `Pinn?e`, `PIN-E`)
	registerAdditionalSugRepl(`[sS]imkarten?`, `[sS]imk`, `SIM-K`)
	registerAdditionalSugRepl(`[vV]orsich(geht|gehen|ging(en)?|gegangen)`, `sich`, ` sich `)
	registerAdditionalSugRepl(`mitsich(bringt|bringen|brachten?|gebracht)`, `sich`, ` sich `)
	registerAdditionalSugRepl(`[ck]arnivorisch(e[mnrs]?)?`, `[ck]arnivorisch`, `karnivor`)
	registerAdditionalSugRepl(`[pP]erfektest(e[mnrs]?)?`, `est`, ``)
	registerAdditionalSugRepl(`[gG]leichtig(e[mnrs]?)?`, `tig`, `zeitig`)
	registerAdditionalSugRepl(`[uU]n(her)?vorgesehen(e[mnrs]?)?`, `(her)?vor`, `vorher`)
	registerAdditionalSugRepl(`([cC]orona|[gG]rippe)viruss?es`, `viruss?es`, `virus`)
	registerAdditionalSugRepl(`Zaubererin(nen)?`, `er`, ``)
	registerAdditionalSugRepl(`Second-Hand-L[äa]dens?`, `Second-Hand-L`, `Secondhandl`)
	registerAdditionalSugRepl(`Second-Hand-Shops?`, `Second-Hand-S`, `Secondhands`)
	registerAdditionalSugRepl(`[mM]editerranisch(e[mnrs]?)?`, `isch`, ``)
	registerAdditionalSugRepl(`interplementier(s?t|en?)`, `inter`, `im`)
	registerAdditionalSugRepl(`[hH]ochalterlich(e[mnrs]?)?`, `alter`, `mittelalter`)
	registerAdditionalSugRepl(`posiniert(e[mnrs]?)?`, `si`, `sitio`)
	registerAdditionalSugRepl(`[rR]ussophobisch(e[mnrs]?)?`, `isch`, ``)
	registerAdditionalSugRepl(`[uU]nsachmä(ß|ss?)ig(e[mnrs]?)?`, `mä(ß|ss?)ig`, `gemäß`)
	registerAdditionalSugRepl(`[mM]odernisch(e[mnrs]?)?`, `isch`, ``)
	registerAdditionalSugRepl(`intapretation(en)?`, `inta`, `Inter`)
	registerAdditionalSugRepl(`[rR]ethorikkurs(e[ns]?)?`, `eth`, `het`)
	registerAdditionalSugRepl(`[uU]nterschreibungsfähig(e[mnrs]?)?`, `schreibung`, `schrift`)
	registerAdditionalSugRepl(`[eE]rrorier(en?|t(e[mnrs]?)?|st)`, `ror`, `u`)
	registerAdditionalSugRepl(`malediert(e[mnrs]?)?`, `malediert`, `malträtiert`)
	registerAdditionalSugRepl(`maletriert(e[mnrs]?)?`, `maletriert`, `malträtiert`)
	registerAdditionalSugRepl(`Ausbildereignerprüfung(en)?`, `eigner`, `eignungs`)
	registerAdditionalSugRepl(`abtrakt(e[mnrs]?)?`, `ab`, `abs`)
	registerAdditionalSugRepl(`unerfolgreich(e[mnrs]?)?`, `unerfolgreich`, `erfolglos`)
	registerAdditionalSugRepl(`[bB]attalion(en?|s)?`, `[bB]attalion`, `Bataillon`)
	registerAdditionalSugRepl(`[bB]esuchungsverbot(e[ns]?)?`, `ung`, ``)
	registerAdditionalSugRepl(`spätrig(e[mnrs]?)?`, `rig`, `er`)
	registerAdditionalSugRepl(`angehangene[mnrs]?`, `hangen`, `hängt`)
	registerAdditionalSugRepl(`[ck]amel[ie]onhaft(e[mnrs]?)?`, `[ck]am[ie]lion`, `chamäleon`)
	registerAdditionalSugRepl(`[wW]idersprüchig(e[mnrs]?)?`, `ig`, `lich`)
	registerAdditionalSugRepl(`[fF]austig(e[mnrs]?)?`, `austig`, `austdick`)
	registerAdditionalSugRepl(`Belastungsekgs?`, `ekg`, `-EKG`)
	registerAdditionalSugRepl(`gehardcode[dt](e[mnrs]?)?`, `gehardcode`, `hartkodier`)
	registerAdditionalSugRepl(`hardgecode[dt](e[mnrs]?)?`, `gehardcode`, `hartkodier`)
	registerAdditionalSugRepl(`Flektion(en)?`, `Flektion`, `Flexion`)
	registerAdditionalSugRepl(`Off-[Ss]hore-[A-Z].+`, `Off-[Ss]hore-`, `Offshore`)
	registerAdditionalSugRepl(`[Vv]ermißt.*`, `ermißt`, `ermisst`)
	registerAdditionalSugRepl(`EUfeindlich.*`, `EUfeindlich`, `EU-feindlich`)
	registerAdditionalSugRepl(`[Üü]bergrifflich(e[mnrs]?)?`, `lich`, `ig`)
	registerAdditionalSugRepl(`schammig(e[mnrs]?)?`, `schamm`, `schwamm`)
	registerAdditionalSugFixed(`Ghanesen?`, `Ghanaer`)
	registerAdditionalSugFixed(`geupdate[dt]$`, `upgedatet`)
	registerAdditionalSugFixed(`[wW]ah?rscheindlichkeit`, `Wahrscheinlichkeit`)
	registerAdditionalSugFixed(`[lL]eerequiment`, `Leerequipment`)
	registerAdditionalSugFixed(`[Tt]uneup`, `TuneUp`)
	registerAdditionalSugFixed(`Germanistiker[ns]`, `Germanisten`)
	registerAdditionalSugFixed(`hinund?her`, `hin und her`)
	registerAdditionalSugFixed(`[lL]ymph?trie?nasche`, `Lymphdrainage`)
	registerAdditionalSugFixed(`[pP]okemon`, `Pokémon`)
	registerAdditionalSugFixed(`rückg[äe]nglich`, `rückgängig`)
	registerAdditionalSugFixed(`em?men[sz]`, `immens`)
	registerAdditionalSugFixed(`schlie[sß]te`, `schloss`)
	registerAdditionalSugFixed(`schlie[sß]ten`, `schlossen`)
	registerAdditionalSugFixed(`[aA]nwesenzeiten`, `Anwesenheitszeiten`)
	registerAdditionalSugFixed(`[gG]eizigkeit`, `Geiz`)
	registerAdditionalSugFixed(`[fF]leißigkeit`, `Fleiß`)
	registerAdditionalSugFixed(`[bB]equemheit`, `Bequemlichkeit`)
	registerAdditionalSugFixed(`[mM]issionarie?sie?rung`, `Missionierung`)
	registerAdditionalSugFixed(`[sS]chee?selonge?`, `Chaiselongue`)
	registerAdditionalSugFixed(`Re[kc]amiere`, `Récamière`)
	registerAdditionalSugFixed(`legen[td]lich`, `lediglich`)
	registerAdditionalSugFixed(`ein[ua]ndhalb`, `eineinhalb`)
	registerAdditionalSugFixed(`[pP][qQ]-Formel`, `p-q-Formel`)
	registerAdditionalSugFixed(`desweitere?m`, `des Weiteren`)
	registerAdditionalSugFixed(`nachvollzuziehe?n`, `nachzuvollziehen`)
	registerAdditionalSugFixed(`Porto?folien`, `Portfolios`)
	registerAdditionalSugFixed(`[sS]chwie?ri?chkeiten`, `Schwierigkeiten`)
	registerAdditionalSugFixed(`[üÜ]bergrifflichkeiten`, `Übergriffigkeiten`)
	registerAdditionalSugFixed(`[aA]r?th?rie?th?is`, `Arthritis`)
	registerAdditionalSugFixed(`instande?zusetzen`, `instand zu setzen`)
	registerAdditionalSugFixed(`Lia(si|is)onen`, `Liaisons`)
	registerAdditionalSugFixed(`[cC]asemana?ge?ment`, `Case Management`)
	registerAdditionalSugFixed(`[aA]nn?[ou]ll?ie?rung`, `Annullierung`)
	registerAdditionalSugFixed(`[sS]charm`, `Charme`)
	registerAdditionalSugFixed(`[eE]rledung`, `Erledigung`)
	registerAdditionalSugFixed(`[iI]ntranzparentheit`, `Intransparenz`)
	registerAdditionalSugFixed(`dunkellilane[mnrs]?`, `dunkellila`)
	registerAdditionalSugFixed(`helllilane[mnrs]?`, `helllila`)
	registerAdditionalSugFixed(`[eEäÄ]klerung`, `Erklärung`)
	registerAdditionalSugFixed(`[wW]eh?wechen`, `Wehwehchen`)
	registerAdditionalSugFixed(`[fF]uss?ill?ien`, `Fossilien`)
	registerAdditionalSugFixed(`[rR]evü`, `Revue`)
	registerAdditionalSugFixed(`[rR]eschärschen`, `Recherchen`)
	registerAdditionalSugFixed(`[rR]eschärsche`, `Recherche`)
	registerAdditionalSugFixed(`w[eä]hret`, `wäret`)
	registerAdditionalSugFixed(`[pP]appa`, `Papa`)
	registerAdditionalSugFixed(`Matrikelnr.`, `Matrikel-Nr.`)
	registerAdditionalSugFixed(`Rekrutings?prozess`, `Recruitingprozess`)
	registerAdditionalSugFixed(`gie?bts`, `gibt's`)
	registerAdditionalSugFixed(`[kK]affeeteria`, `Cafeteria`)
	registerAdditionalSugFixed(`[kK]affeeterien`, `Cafeterien`)
	registerAdditionalSugFixed(`wie?daholung`, `Wiederholung`)
	registerAdditionalSugFixed(`vie?d(er|a)sehen`, `wiedersehen`)
	registerAdditionalSugFixed(`pr[eä]ventiert`, `verhindert`)
	registerAdditionalSugFixed(`pr[eä]ventieren`, `verhindern`)
	registerAdditionalSugFixed(`zur?verfügung`, `zur Verfügung`)
	registerAdditionalSugFixed(`[oO]r?ganisazion`, `Organisation`)
	registerAdditionalSugFixed(`[oO]rganisative`, `Organisation`)
	registerAdditionalSugFixed(`Emall?iearbeit`, `Emaillearbeit`)
	registerAdditionalSugFixed(`[aA]petitt`, `Appetit`)
	registerAdditionalSugFixed(`[zZ]ulaufror`, `Zulaufrohr`)
	registerAdditionalSugFixed(`[gG]ebrauchss?puhren`, `Gebrauchsspuren`)
	registerAdditionalSugFixed(`[pP]reisnachlassung`, `Preisnachlass`)
	registerAdditionalSugFixed(`[mM]edikamentation`, `Medikation`)
	registerAdditionalSugFixed(`[nN][ei]gliche`, `Negligé`)
	registerAdditionalSugFixed(`[pP]allete`, `Palette`)
	registerAdditionalSugFixed(`[sS]chull?igung`, `Entschuldigung`)
	registerAdditionalSugFixed(`hobb?ies`, `Hobbys`)
	registerAdditionalSugFixed(`unann?äh?ml?ichkeiten`, `Unannehmlichkeiten`)
	registerAdditionalSugFixed(`unn?ann?ehmichkeiten`, `Unannehmlichkeiten`)
	registerAdditionalSugFixed(`übertr[äa]gte`, `übertrug`)
	registerAdditionalSugFixed(`übertr[äa]gten`, `übertrugen`)
	registerAdditionalSugFixed(`Pann?acott?a`, `Panna cotta`)
	registerAdditionalSugFixed(`Fußgängerunterwegs?`, `Fußgängerunterführung`)
	registerAdditionalSugFixed(`[eE]ngangment`, `Engagement`)
	registerAdditionalSugFixed(`[lL]eichtah?tleh?t`, `Leichtathlet`)
	registerAdditionalSugFixed(`[pP]fane`, `Pfanne`)
	registerAdditionalSugFixed(`[iI]ngini?eue?r`, `Ingenieur`)
	registerAdditionalSugFixed(`[aA]nligen`, `Anliegen`)
	registerAdditionalSugFixed(`[sS]itwazion`, `Situation`)
	registerAdditionalSugFixed(`[kK]aos`, `Chaos`)
	registerAdditionalSugFixed(`[pP]upatät`, `Pubertät`)
	registerAdditionalSugFixed(`[bB]esichtung`, `Besichtigung`)
	registerAdditionalSugFixed(`[hH]ell?owi[eh]?n`, `Halloween`)
	registerAdditionalSugFixed(`geschmelt?zt`, `geschmolzen`)
	registerAdditionalSugFixed(`anschein[dt]`, `anscheinend`)
	registerAdditionalSugFixed(`[jJ]ahundert`, `Jahrhundert`)
	registerAdditionalSugFixed(`[vV]orgensweise`, `Vorgehensweise`)
	registerAdditionalSugFixed(`[kK]autsch`, `Couch`)
	registerAdditionalSugFixed(`Wi[Ff]i-Router`, `Wi-Fi-Router`)
	registerAdditionalSugFixed(`D[eèé]ja-?[vV]o?ue?`, `Déjà-vu`)
	registerAdditionalSugFixed(`Cr[eèé]me-?fra[iî]che`, `Crème fraîche`)
	registerAdditionalSugFixed(`[aA]rr?an?gemont`, `Arrangement`)
	registerAdditionalSugFixed(`[aA]ngagemon`, `Engagement`)
	registerAdditionalSugFixed(`Phyrr?ussieg`, `Pyrrhussieg`)
	registerAdditionalSugFixed(`[pP]u(zz|ss)el`, `Puzzle`)
	registerAdditionalSugFixed(`[dD]iseing?`, `Design`)
	registerAdditionalSugFixed(`[lL]ieradd?ress?e`, `Lieferadresse`)
	registerAdditionalSugFixed(`[bB]o[yi]kutierung`, `Boykottierung`)
	registerAdditionalSugFixed(`[aA]ktuelli?esie?rung`, `Aktualisierung`)
	registerAdditionalSugFixed(`vll?t`, `vielleicht`)
	registerAdditionalSugFixed(`[rR]eflektion`, `Reflexion`)
	registerAdditionalSugFixed(`[fF]rühstücksb[uü]ff?(é|ee)`, `Frühstücksbuffet`)
	registerAdditionalSugFixed(`[aA]lterego`, `Alter Ego`)
	registerAdditionalSugFixed(`Cand(el|le)lightdinner`, `Candle-Light-Dinner`)
	registerAdditionalSugFixed(`[iIüÜuU]b[ea]w[ae]isung`, `Überweisung`)
	registerAdditionalSugFixed(`[bB]oxhorn`, `Bockshorn`)
	registerAdditionalSugFixed(`[zZ]oolophie`, `Zoophilie`)
	registerAdditionalSugFixed(`[kK]onn?ekt?schen`, `Connection`)
	registerAdditionalSugFixed(`[nN]ah?richt`, `Nachricht`)
	registerAdditionalSugFixed(`[nN]ah?richten`, `Nachrichten`)
	registerAdditionalSugFixed(`[hH]ifi`, `Hi-Fi`)
	registerAdditionalSugFixed(`eh?rgeit?z`, `Ehrgeiz`)
	registerAdditionalSugFixed(`staats?angehoe?rigkeit`, `Staatsangehörigkeit`)
	registerAdditionalSugFixed(`[uU]nangeneh?mheiten`, `Unannehmlichkeiten`)
	registerAdditionalSugFixed(`bescheid?t`, `Bescheid`)
	registerAdditionalSugFixed(`[mM]iteillung`, `Mitteilung`)
	registerAdditionalSugFixed(`[eE]infühlvermögen`, `Einfühlungsvermögen`)
	registerAdditionalSugFixed(`[sS]peziellisierung`, `Spezialisierung`)
	registerAdditionalSugFixed(`[cC]hangse`, `Chance`)
	registerAdditionalSugFixed(`Durfüh?rung`, `Durchführung`)
	registerAdditionalSugFixed(`Kilimand?jaro`, `Kilimandscharo`)
	registerAdditionalSugFixed(`[hH]erausfor?dung`, `Herausforderung`)
	registerAdditionalSugFixed(`[bB]erücksichtung`, `Berücksichtigung`)
	registerAdditionalSugFixed(`artzt?`, `Arzt`)
	registerAdditionalSugFixed(`[tT]h?elepath?ie`, `Telepathie`)
	registerAdditionalSugFixed(`Wi-?Fi-Dire[ck]t`, `Wi-Fi Direct`)
	registerAdditionalSugFixed(`Pearl-Harbou?r`, `Pearl Harbor`)
	registerAdditionalSugFixed(`[aA]utonomität`, `Autonomie`)
	registerAdditionalSugFixed(`[fF]r[uü]h?st[uü]c?k`, `Frühstück`)
	registerAdditionalSugFixed(`zucc?h?inis?`, `Zucchini`)
	registerAdditionalSugFixed(`[mM]itag`, `Mittag`)
	registerAdditionalSugFixed(`[mM]otorisation`, `Motorisierung`)
	registerAdditionalSugFixed(`[fF]ormalisation`, `Formalisierung`)
	registerAdditionalSugFixed(`[mM]enegment`, `Management`)
	registerAdditionalSugFixed(`[gG]ebrauspuren`, `Gebrauchsspuren`)
	registerAdditionalSugFixed(`[hH]erstammung`, `Abstammung`)
	registerAdditionalSugFixed(`[iI]nstall?atör`, `Installateur`)
	registerAdditionalSugFixed(`[bB]i[sß](s?[ij]|ch)en`, `bisschen`)
	registerAdditionalSugFixed(`[iI]dentifierung`, `Identifikation`)
	registerAdditionalSugFixed(`[eE]mphatie`, `Empathie`)
	registerAdditionalSugFixed(`[eE]iskrem`, `Eiscreme`)
	registerAdditionalSugFixed(`[fF]lüchtung`, `Flucht`)
	registerAdditionalSugFixed(`[eE]inbu(ss|ß)ung`, `Einbuße`)
	registerAdditionalSugFixed(`[eE]inbu(ss|ß)ungen`, `Einbußen`)
	registerAdditionalSugFixed(`[hH]udd[yi]`, `Hoodie`)
	registerAdditionalSugFixed(`Brotwürfelcro[uû]tons`, `Croûtons`)
	registerAdditionalSugFixed(`bess?tetigung`, `Bestätigung`)
	registerAdditionalSugFixed(`[mM]ayonaisse`, `Mayonnaise`)
	registerAdditionalSugFixed(`[vV]erlu(ss|ß)t`, `Verlust`)
	registerAdditionalSugFixed(`[sS]tandtart`, `Standard`)
	registerAdditionalSugFixed(`[iI]ntuion`, `Intuition`)
	registerAdditionalSugFixed(`[cCkK]ontener`, `Container`)
	registerAdditionalSugFixed(`[wW]ischmöppen?`, `Wischmopps`)
	registerAdditionalSugFixed(`[nN]or[dt]rh?einwest(f|ph)alen`, `Nordrhein-Westfalen`)
	registerAdditionalSugFixed(`gefäh?ten`, `Gefährten`)
	registerAdditionalSugFixed(`gefäh?te`, `Gefährte`)
	registerAdditionalSugFixed(`[sS]äusche`, `Seuche`)
	registerAdditionalSugFixed(`[dD]epp?risonen`, `Depressionen`)
	registerAdditionalSugFixed(`achtungslo[ßs]`, `achtlos`)
	registerAdditionalSugFixed(`[vV]ollkommnung`, `Vervollkommnung`)
	registerAdditionalSugFixed(`[kK]ostarika`, `Costa Rica`)
	registerAdditionalSugFixed(`[kK]ostarikas`, `Costa Ricas`)
	registerAdditionalSugFixed(`[aA]uthenzität`, `Authentizität`)
	registerAdditionalSugFixed(`[sS]tieft`, `Stift`)
	registerAdditionalSugFixed(`[Ii]nspruchnahme`, `Inanspruchnahme`)
	registerAdditionalSugFixed(`höstwah?rsch[ea]inlich`, `höchstwahrscheinlich`)
	registerAdditionalSugFixed(`[aA]lterschbeschränkung`, `Altersbeschränkung`)
	registerAdditionalSugFixed(`[kK]unstoff`, `Kunststoff`)
	registerAdditionalSugFixed(`[iI]nstergramm?`, `Instagram`)
	registerAdditionalSugFixed(`[eE]rartens`, `Erachtens`)
	registerAdditionalSugFixed(`[wW]ahts?app`, `WhatsApp`)
	registerAdditionalSugFixed(`[uU]nstimm?ichkeiten`, `Unstimmigkeiten`)
	registerAdditionalSugFixed(`[hH]irar?chie`, `Hierarchie`)
	registerAdditionalSugFixed(`[hH]ähme`, `Häme`)
	registerAdditionalSugFixed(`Studiumplatzt?`, `Studienplatz`)
	registerAdditionalSugFixed(`wie?derwarten`, `wider Erwarten`)
	registerAdditionalSugFixed(`[eE]ntercott?e`, `Entrecôte`)
	registerAdditionalSugFixed(`[eE]rwachtung`, `Erwartung`)
	registerAdditionalSugFixed(`[aA]nung`, `Ahnung`)
	registerAdditionalSugFixed(`[uU]nreimlichkeiten`, `Ungereimtheiten`)
	registerAdditionalSugFixed(`[uU]nangeneh?mlichkeiten`, `Unannehmlichkeiten`)
	registerAdditionalSugFixed(`Bonnerstra(ß|ss)e`, `Bonner Straße`)
	registerAdditionalSugFixed(`[bB]range`, `Branche`)
	registerAdditionalSugFixed(`[gG]eborgsamkeit`, `Geborgenheit`)
	registerAdditionalSugFixed(`nochnichtmals?`, `noch nicht einmal`)
	registerAdditionalSugFixed(`[sS]chanse`, `Chance`)
	registerAdditionalSugFixed(`[Ee][Ss]ports`, `E-Sports`)
	registerAdditionalSugFixed(`gerelaunch(ed|t)`, `relauncht`)
	registerAdditionalSugFixed(`Gerelaunch(ed|t)`, `Relauncht`)
	registerAdditionalSugFixed(`Dark[Ww]eb`, `Darknet`)
	registerAdditionalSugFixed(`Sachs?en-Anhal?t`, `Sachsen-Anhalt`)
	registerAdditionalSugFixed(`[Ss]chalgen`, `schlagen`)
	registerAdditionalSugFixed(`[Ss]chalge`, `schlage`)
	registerAdditionalSugFixed(`[dD]eutsche?sprache`, `deutsche Sprache`)
	registerAdditionalSugFixed(`[Rr]eviewing`, `Review`)
	registerAdditionalSugFixed(`[Bb]aldmöglich`, `baldmöglichst`)
	registerAdditionalSugFixed(`[Bb]rudi`, `Bruder`)
	registerAdditionalSugFixed(`[qQ]uicky`, `Quickie`)
	registerAdditionalSugFixed(`[qQ]uickys`, `Quickies`)
	registerAdditionalSugFixed(`[Nn]umber`, `Nummer`)
}


func registerAdditionalSugRepl(wordPat, findPat, repl string) {
	w, err1 := regexp.Compile("^(?:" + wordPat + ")$")
	f, err2 := regexp.Compile(findPat)
	if err1 != nil || err2 != nil {
		return
	}
	additionalSugRepls = append(additionalSugRepls, additionalSugRepl{word: w, find: f, repl: repl})
}

func registerAdditionalSugFixed(wordPat, repl string) {
	w, err := regexp.Compile("^(?:" + wordPat + ")$")
	if err != nil {
		return
	}
	additionalSugPatternFixed = append(additionalSugPatternFixed, additionalSugFixedEntry{word: w, repl: repl})
}

// replaceFirst expands repl with $1-style groups like Java Matcher.replaceFirst.
func replaceFirst(re *regexp.Regexp, s, repl string) string {
	loc := re.FindStringSubmatchIndex(s)
	if loc == nil {
		return s
	}
	var b []byte
	b = re.Expand(b, []byte(repl), []byte(s), loc)
	return s[:loc[0]] + string(b) + s[loc[1]:]
}

// lookupAdditionalSuggestionsRegexp ports ADDITIONAL_SUGGESTIONS scan for putRepl,
// put(regex, fixed), multi-list regex puts, and replace-style lambdas.
// Approximate LinkedHashMap first-match order among these groups.
func lookupAdditionalSuggestionsRegexp(word string) []string {
	if word == "" || len(word) > additionalSugMaxMatchLen {
		return nil
	}
	for _, e := range additionalSugRepls {
		if e.word.MatchString(word) {
			return []string{replaceFirst(e.find, word, e.repl)}
		}
	}
	for _, e := range additionalSugPatternFixed {
		if e.word.MatchString(word) {
			return []string{e.repl}
		}
	}
	for _, e := range additionalSugMulti {
		if e.word.MatchString(word) {
			return append([]string(nil), e.repls...)
		}
	}
	if sugs := lookupAdditionalSuggestionsLambda(word); len(sugs) > 0 {
		return sugs
	}
	return nil
}

