package de

import "github.com/lucasew/lang/internal/languagetool/org/languagetool/rules/patterns"

// MissingCommaRelativeAntiPatterns ports MissingCommaRelativeClauseRule anti-patterns.
// Coverage: 25/25; 0 omitted.
var MissingCommaRelativeAntiPatterns = [][]*patterns.PatternToken{
	{
		patterns.Regex("gerade|wenn"),
		patterns.Token("das"),
	},
	{
		patterns.Token("anstelle"),
		patterns.Regex("diese[rsm]|de[rsm]|dessen|jene[rsm]|[dms]?eine[rsm]|ihre[rs]|eure[sr]|unse?re[sr]"),
	},
	{
		patterns.Token("im"),
		patterns.Token("Zuge"),
		patterns.Token("dessen"),
	},
	{
		patterns.CsToken("mit"),
		patterns.Regex("de[mr]"),
		patterns.Regex("de[mrs]"),
		patterns.PosRegex("SUB:.+"),
		patterns.CsToken("verbindet"),
	},
	{
		patterns.Regex("eine"),
		patterns.CsToken("menge"),
		patterns.PosRegex("SUB:.+"),
	},
	{
		patterns.Regex("wie"),
		patterns.CsToken("folgt"),
		patterns.PosRegex("VER:.+"),
	},
	{
		patterns.Regex("gut"),
		patterns.CsToken("überlegt"),
		patterns.CsToken("sein"),
	},
	{
		patterns.CsToken("samt"),
		patterns.PosRegex("SUB:DAT.*"),
	},
	{
		patterns.PosRegex("PA2:PRD:GRU:VER|VER:PA2.*"),
		patterns.CsToken("sind"),
		patterns.PosRegex("PKT"),
	},
	{
		patterns.CsToken("am"),
		patterns.Pos("ADJ:PRD:SUP"),
		patterns.PosRegex("PRP:.+"),
		patterns.Regex("d(e[mnr]|ie|as|e([nr]|ss)en)"),
	},
	{
		patterns.Pos("SENT_START"),
		patterns.Token("Aber"),
		patterns.Regex("der|die|denen|das|jenen|einigen|anderen|vielen|manchen|allen"),
	},
	{
		patterns.PosRegex("PA2.*|VER:PA2.*"),
		patterns.Token("werden"),
		patterns.Regex("[\\.\\!\\?…\\:;]+"),
	},
	{
		patterns.Token("werden"),
		patterns.NewPatternTokenBuilder().PosRegex("SENT_END").MatchInflectedForms().TokenRegex("sollen|können|müssen").Build(),
	},
	{
		patterns.PosRegex("PA2.*|VER:PA2.*"),
		patterns.NewPatternTokenBuilder().PosRegex("SENT_END").MatchInflectedForms().TokenRegex("haben|werden").Build(),
	},
	{
		patterns.PosRegex("VER:INF.*"),
		patterns.NewPatternTokenBuilder().PosRegex("SENT_END").MatchInflectedForms().TokenRegex("können|werden|sollen|dürfen|müssen|wollen|mögen").Build(),
	},
	{
		patterns.Regex("ja|mal"),
		patterns.CsToken("was"),
	},
	{
		patterns.PosRegex("SENT_START|PKT"),
		patterns.CsToken("aber"),
		patterns.Regex("solange|wenn|wo|wie|was"),
		patterns.Regex("du|er|sie|sich|man|euch|uns|die|der|das"),
	},
	{
		patterns.CsToken("selbst"),
		patterns.CsToken("wenn"),
		patterns.Regex("du|er|sie|sich|man|euch|uns|die|der|das"),
		patterns.Regex("die|der|das"),
	},
	{
		patterns.CsToken("wie"),
		patterns.Regex("die|der|das"),
	},
	{
		patterns.NewPatternTokenBuilder().SetSkip(12).MatchInflectedForms().Token("weder").Build(),
		patterns.Token("noch"),
	},
	{
		patterns.PosRegex("VER:.*1:SIN:KJ1:.+"),
		patterns.PosRegex("VER:MOD:[12]:.+"),
		patterns.PosRegex("PKT|KON:NEB"),
	},
	{
		patterns.PosRegex("VER:.+"),
		patterns.CsToken("bzw"),
		patterns.CsToken("."),
		patterns.PosRegex("VER:.+"),
	},
	{
		patterns.Regex("w[eu]rden"),
		patterns.PosRegex("PA2:PRD:GRU:VER|VER:PA2.*"),
		patterns.Pos("PKT"),
	},
	{
		patterns.PosRegex("PA2:PRD:GRU:VER|VER:PA2.*"),
		patterns.Regex("haben?|hatten?"),
		patterns.PosRegex("VER:EIZ.*"),
		patterns.Pos("PKT"),
	},
	{
		patterns.PosRegex("VER.*"),
		patterns.Regex("\\u2063"),
	},
}
