package de

// lowercaseProhibitedPairs ports ProhibitedCompoundRule.lowercasePairs (active Java entries only).
var lowercaseProhibitedPairs = []prohibitedPair{
	{"knoten", "Verschlingung von Fäden", "konten", "Plural von 'Konto'"},
	{"schaf", "Tier", "schaft", "'-schaft' (Element zur Wortbildung, z. B. 'Freundschaft')"},
	{"schafen", "Dativ Plural von 'Schaf'", "schaften", "'-schaften' (Element zur Wortbildung, z. B. 'Freundschaften')"},
	{"alpen", "Hochgebirge in Mittel- und Südeuropa", "alben", "Plural von 'Album'"},
	{"pillen", "Tabletten", "pullen", "Plural von 'Pulle' (Flasche)"},
	{"tauben", "Vogelart", "trauben", "Obstsorte"},
	{"panel", "ausgewählte Personengruppe", "paneel", "Platte für Wand- und Deckenverkleidungen"},
	{"nabe", "Mittelteil eines Rades", "narbe", "verheilende Wunde"},
	{"first", "höchste Kante an einem geneigten Dach", "frist", "spätester Zeitpunkt"},
	{"koma", "Zustand tiefer Bewusstlosigkeit", "komma", "Satzzeichen"},
	{"korn", "Getreide sowie dessen Frucht", "kron", "Vorsilbe z.B. in 'Kronkorken'"},
	{"bauten", "Form von 'Bau' (Bauwerk, Haus, ...)", "beuten", "Form von 'Beute'"},
	{"file", "engl. 'Datei'", "filet", "ein Stück Fleisch oder Fisch"},
	{"zecke", "blutsaugender Parasit", "zwecke", "Dativ von 'Zweck' (Ziel)"},
	{"frucht", "Teil einer Pflanze; Obst", "furcht", "Angst"},
	{"rate", "Verhältnis zwischen zwei Größen", "ratte", "Nagetier"},
	{"posten", "Arbeitsplatz, Wachposten", "posen", "Pose: betonte Körperhaltung"},
	{"himmel", "Bereich über der Erde", "hummel", "Insekt"},
	{"server", "Computer", "servier", "zu 'servieren'"},
	{"ziege", "Tier", "ziegel", "Ziegelstein"},
	{"robe", "Kleidungsstück", "probe", "Test, Kontrolle"},
	{"mode", "Kleidung", "monde", "Begleiter eines Planeten"},
	{"eigen", "'selbst', z.B. 'Eigenzitat'", "eingen", "Möglicher Tippfehler"},
	{"stümpfe", "Rest eines Körpergliedes", "strümpfe", "Bekleidungsstück für den Fuß"},
	{"gelände", "Gebiet", "geländer", "Konstruktion zum Festhalten entlang von Treppen"},
	{"tropen", "feuchtwarme Gebiete am Äquator", "tropfen", "kleine Menge Flüssigkeit"},
	{"enge", "Mangel an Platz", "menge", "Anzahl an Einheiten"},
	{"ritt", "Reiten", "tritt", "Aufsetzen eines Fußes"},
	{"beine", "Körperteil", "biene", "Insekt"},
	{"rebe", "Weinrebe", "reibe", "Küchenreibe"},
	{"ass", "Spielkarte", "pass", "Reisepass; Übergang durch ein Gebirge"},
	{"türmer", "Turmwächter", "türme", "Plural von 'Turm' (Bauwerk)"},
	{"soge", "ziehende Strömungen", "sorge", "bedrückendes Gefühl"},
	{"panne", "technischer Defekt", "spanne", "Zeitraum"},
	{"elfer", "Elfmeter", "helfer", "Person, die hilft"},
	{"gase", "Plural von 'Gas' (Aggregatzustand)", "gasse", "kleine Straße"},
	{"ekel", "Abscheu", "enkel", "Kind eines eigenen Kindes"},
	{"reis", "Nahrungsmittel", "reise", "Ausflug/Fahrt"},
	{"hüte", "Kopfbedeckungen", "häute", "Plural von 'Haut'"},
	{"werbereich", "", "erbereich", ""},
	{"lage", "Position", "alge", "im Wasser lebende Organismen"},
	{"sphäre", "Kugel", "spähreh", ""},
	{"schenke", "Gastwirtschaft (auch: Schänke)", "schenkel", "Ober- und Unterschenkel"},
	{"mai", "Monat nach April", "mail", "E-Mail"},
	{"pump", "'auf Pump': umgangssprachlich für 'auf Kredit'", "pumpe", "Gerät zur Beförderung von Flüssigkeiten"},
	{"mitte", "zentral", "mittel", "Methode, um etwas zu erreichen"},
	{"fein", "feinkörnig, genau, gut", "feind", "Gegner"},
	{"traum", "Erleben während des Schlafes", "trauma", "Verletzung"},
	{"name", "Bezeichnung (z.B. 'Vorname')", "nahme", "zu 'nehmen' (z.B. 'Teilnahme')"},
	{"bart", "Haarbewuchs im Gesicht", "dart", "Wurfpfeil"},
	{"hart", "fest", "dart", "Wurfpfeil"},
	{"speiche", "Verbindung zwischen Nabe und Felge beim Rad", "speicher", "Lagerraum"},
	{"kart", "Gokart (Fahrzeug)", "karte", "Fahrkarte, Postkarte, Landkarte, ..."},
	{"karts", "Kart = Gokart (Fahrzeug)", "karte", "Fahrkarte, Postkarte, Landkarte, ..."},
	{"kiefer", "knöcherner Teil des Schädels", "kiefern", "Kieferngewächse (Baum)"},
	{"gel", "dickflüssige Masse", "geld", "Zahlungsmittel"},
	{"kamp", "Flurname für ein Stück Land", "kampf", "Auseinandersetzung"},
	{"läuse", "Insekt", "läufe", "Bewegungsart"},
	{"läusen", "Insekt", "läufen", "Bewegungsart"},
	{"ruck", "plötzliche Bewegung", "druck", "Belastung"},
	{"brüste", "Plural von Brust", "bürste", "Gerät mit Borsten, z.B. zum Reinigen"},
	{"attraktion", "Sehenswürdigkeit", "akttaktion", "vermutlicher Tippfehler"},
	{"turn", "zu 'turnen'", "turm", "hohes Bauwerk"},
	{"mit", "Präposition", "miet", "zu 'Miete' (Überlassung gegen Bezahlung)"},
	{"bart", "Behaarung im Gesicht", "brat", "zu 'braten', z.B. 'Bratkartoffel'"},
	{"uhr", "Instrument zur Zeitmessung", "ur", "ursprünglich"},
	{"abschluss", "Ende", "abschuss", "Vorgang des Abschießens, z.B. mit einer Waffe"},
	{"brache", "verlassenes Grundstück", "branche", "Wirtschaftszweig"},
	{"wieder", "erneut, wiederholt, nochmal (Wiederholung, Wiedervorlage, ...)", "wider", "gegen, entgegen (Widerwille, Widerstand, Widerspruch, ...)"},
	{"leer", "ohne Inhalt", "lehr", "bezogen auf Ausbildung und Wissen"},
	{"gewerbe", "wirtschaftliche Tätigkeit", "gewebe", "gewebter Stoff; Verbund ähnlicher Zellen"},
	{"klima", "langfristige Wetterzustände", "lima", "Hauptstadt von Peru"},
	{"modell", "vereinfachtes Abbild der Wirklichkeit", "model", "Fotomodell"},
	{"häufigkeit", "Anzahl von Ereignissen", "häutigkeit", "z.B. in Dunkelhäutigkeit"},
	{"hin", "in Richtung", "hirn", "Gehirn, Denkapparat"},
	{"verklärung", "Beschönigung, Darstellung in einem besseren Licht", "erklärung", "Darstellung, Erläuterung"},
	{"punk", "Jugendkultur", "punkt", "Satzzeichen"},
	{"haft", "Freiheitsentzug", "schaft", "-schaft (Element zur Wortbildung)"},
	{"stande", "zu 'Stand'", "stange", "länglicher Gegenstand"},
}
