package de

import (
	"github.com/lucasew/lang/internal/languagetool/org/languagetool"
	"github.com/lucasew/lang/internal/languagetool/org/languagetool/rules/patterns"
)

// VerbAgreementAntiPatterns ports VerbAgreementRule.ANTI_PATTERNS (auto-converted from Java).
// Coverage: 96/96. Do not invent missing ones.
var VerbAgreementAntiPatterns = [][]*patterns.PatternToken{
	{
		patterns.Token("du"),
		patterns.Token("wärst"),
		patterns.Token("ich"),
	},
	{
		patterns.Token("*"),
		patterns.PosRegex("VER:1:SIN:PRÄ:.*"),
		patterns.Token("*"),
	},
	{
		patterns.NewPatternTokenBuilder().Token("weder").SetSkip(8).Build(),
		patterns.Token("noch"),
		patterns.Token("ich"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:2:SIN:PRÄ:.*"),
		patterns.PosRegex("PRO:.*"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:2:SIN:PRÄ:.*"),
		patterns.TokenRegex("einfach|denn|schon"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:2:SIN:PRÄ:.*"),
		patterns.PosRegex("PRP:.*"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:2:SIN:PRÄ:.*"),
		patterns.PosRegex("ADJ:PRD:.*"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:2:SIN:PRÄ:.*"),
		patterns.Pos("ZUS"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.Pos("VER:MOD:2:SIN:KJ2"),
		patterns.PosRegex("PRO:.*"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.Pos("VER:MOD:2:SIN:PRÄ"),
		patterns.NewPatternTokenBuilder().Token("ich|er|sie|es|wir|ihr|sie").Negate().Build(),
	},
	{
		patterns.Token("wir"),
		patterns.Token("frische"),
	},
	{
		patterns.Token("zum"),
		patterns.CsToken("Du"),
		patterns.NewPatternTokenBuilder().TokenRegex("wechseln|übergehen|schwenken").MatchInflectedForms().Build(),
	},
	{
		patterns.Token("ich"),
		patterns.Token("schlafen"),
		patterns.Token("gehe"),
	},
	{
		patterns.Token("ich"),
		patterns.TokenRegex("bin|war"),
		patterns.Token("du"),
	},
	{
		patterns.TokenRegex("darum|deswegen|dann|bitte|so|,|-"),
		patterns.PosRegex("VER:IMP:SIN.*"),
		patterns.Token("du"),
	},
	{
		patterns.TokenRegex("[-–]"),
		patterns.PosRegex("VER:.*(AUX|MOD).*"),
		patterns.Token("du"),
		patterns.PosRegex("VER:INF.*"),
	},
	{
		patterns.TokenRegex("-(du|ich|er|sie|wir|ihr)"),
		patterns.PosRegex("VER.*"),
	},
	{
		patterns.TokenRegex("bin|war|wär"),
		patterns.TokenRegex("i|icke?"),
	},
	{
		patterns.TokenRegex("i|icke?"),
		patterns.TokenRegex("bin|war|wär"),
	},
	{
		patterns.Token("du"),
		patterns.Token("schlafen"),
		patterns.Token("gehst"),
	},
	{
		patterns.Token("per"),
		patterns.Token("du"),
		patterns.TokenRegex("sind|waren|sein|wären|war|ist|gewesen"),
	},
	{
		patterns.Token("schnellst"),
		patterns.Token("möglich"),
	},
	{
		patterns.Token("er"),
		patterns.Token("schlafen"),
		patterns.Token("geht"),
	},
	{
		patterns.Token("vermittelst"),
	},
	{
		patterns.Token("du"),
		patterns.Token("denkst"),
		patterns.Token("ich"),
	},
	{
		patterns.Token("na"),
		patterns.Token("komm"),
	},
	{
		patterns.TokenRegex("muß|mußten?|müßt?en?"),
		patterns.TokenRegex("ich|wir|sie|er|es"),
	},
	{
		patterns.TokenRegex("ich|wir|sie|er|es"),
		patterns.PosRegex("VER.*INF.*"),
		patterns.TokenRegex("muß|mußten?|müßt?en?"),
	},
	{
		patterns.TokenRegex("mußt|müßtest|mußtest"),
		patterns.Token("du"),
	},
	{
		patterns.Token("du"),
		patterns.PosRegex("VER.*INF.*"),
		patterns.TokenRegex("mußt|müßtest|mußtest"),
	},
	{
		patterns.Token("ich"),
		patterns.TokenRegex("würd|könnt|werd|wollt|sollt|müsst|fürcht"),
		patterns.TokenRegex("['’`´‘]"),
	},
	{
		patterns.TokenRegex("wir|sie|zu"),
		patterns.TokenRegex("seh|steh|geh"),
		patterns.TokenRegex("['’`´‘]"),
		patterns.Token("n"),
	},
	{
		patterns.Token("ick"),
		patterns.TokenRegex("bin|war|wär|hab|hatte"),
	},
	{
		patterns.Token("#"),
		patterns.PosRegex("VER.*"),
	},
	{
		patterns.Token("wie"),
		patterns.TokenRegex("du|ihr|er|es|sie"),
		patterns.PosRegex("VER.*"),
	},
	{
		patterns.TokenRegex("[-:]"),
		patterns.PosRegex("VER.*(MOD|AUX).*"),
	},
	{
		patterns.PosRegex("UNKNOWN|EIG.*"),
		patterns.Token("bin"),
		patterns.PosRegex("UNKNOWN|EIG.*"),
	},
	{
		patterns.TokenRegex("du|sie"),
		patterns.TokenRegex("schei(ß|ss)"),
		patterns.PosRegex("SUB.*|UNKNOWN"),
	},
	{
		patterns.Token("Du"),
		patterns.TokenRegex("bist|warst|wärst"),
	},
	{
		patterns.Token("als"),
		patterns.Token("auch"),
		patterns.TokenRegex("er|sie|wir|du|ich|ihr"),
	},
	{
		patterns.TokenRegex("so|wie|zu"),
		patterns.Token("lange"),
		patterns.TokenRegex("er|sie|wir|du|ich|ihr"),
	},
	{
		patterns.NewPatternTokenBuilder().TokenRegex("so|genauso|ähnlich").MatchInflectedForms().SetSkip(2).Build(),
		patterns.Token("wie"),
		patterns.TokenRegex("er|sie|du|ihr|ich"),
		patterns.PosRegex("VER.*"),
	},
	{
		patterns.PosRegex("VER.*(MOD|AUX).*"),
		patterns.Token("wie"),
		patterns.TokenRegex("er|sie|du|ihr|ich"),
		patterns.PosRegex("VER.*INF.*"),
	},
	{
		patterns.Token("wie"),
		patterns.PosRegex("ADJ:PRD:GRU.*"),
		patterns.TokenRegex("er|sie|du|ihr|ich"),
		patterns.PosRegex("VER.*"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:2:SIN:.*"),
		patterns.PosRegex("ART.*|ADV.*|PRO:POS.*"),
	},
	{
		patterns.Token(","),
		patterns.PosRegex("EIG:.*|UNKNOWN"),
		patterns.Regex("und|oder"),
		patterns.Token("auch"),
		patterns.Token("ich"),
	},
	{
		patterns.PosRegex("VER.*"),
		patterns.TokenRegex("er|sie|ich|wir|du|es|ihr"),
		patterns.TokenRegex("gleich|bereit|lange|schnelle?|halt|bitte|dank"),
	},
	{
		patterns.PosRegex("ADV.*|KON.*"),
		patterns.TokenRegex("er|sie|ich|wir|du|es|ihr"),
		patterns.TokenRegex("gleich|bereit|lange|schnelle?|halt|bitte|dank"),
	},
	{
		patterns.PosRegex("ADV.*|KON.*"),
		patterns.TokenRegex("er|sie|ich|wir|du|es|ihr"),
		patterns.TokenRegex("verlegen"),
		patterns.PosRegex("VER.*"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:2:SIN:.*"),
		patterns.Token("nicht"),
	},
	{
		patterns.NewPatternTokenBuilder().Token("machen").MatchInflectedForms().SetSkip(-1).Build(),
		patterns.Token("halt"),
	},
	{
		patterns.PosRegex("VER:.*"),
		patterns.TokenRegex("du|ihr"),
		patterns.Token("auch"),
	},
	{
		patterns.Token("für"),
		patterns.Token("Sie"),
		patterns.Pos("VER:3:SIN:KJ1:SFT"),
		patterns.Token("ich"),
	},
	{
		patterns.TokenRegex("(irgend)?einer?|(irgend)?jemand"),
		patterns.Token("wie"),
		patterns.Token("du"),
		patterns.PosRegex("VER:3:.*"),
	},
	{
		patterns.Pos("VER:MOD:2:SIN:PRÄ"),
		patterns.PosRegex("PRO:PER:.*"),
	},
	{
		patterns.TokenRegex("die|welche"),
		patterns.TokenRegex(".*"),
		patterns.TokenRegex("mehr|weniger"),
		patterns.Token("als"),
		patterns.TokenRegex("ich|du|e[rs]|sie"),
	},
	{
		patterns.Token("wenn"),
		patterns.Token("du"),
		patterns.Token("anstelle"),
	},
	{
		patterns.TokenRegex("ok(ay)?|ja|nein|vielleicht|oh"),
		patterns.TokenRegex("bin|sind"),
	},
	{
		patterns.Token("das"),
		patterns.CsToken("Du"),
		patterns.NewPatternTokenBuilder().Token("anbieten").MatchInflectedForms().Build(),
	},
	{
		patterns.CsToken("Du"),
		patterns.NewPatternTokenBuilder().TokenRegex("anreden|ansprechen").MatchInflectedForms().Build(),
	},
	{
		patterns.PosRegex("SUB:.*PLU.*"),
		patterns.Token("wie"),
		patterns.Token("Du"),
		patterns.PosRegex("VER:3:PLU.*"),
	},
	{
		patterns.Token("würd"),
		patterns.TokenRegex("[nm]ich|man|ichs|'"),
	},
	{
		patterns.Token(","),
		patterns.PosRegex("VER:MOD:2:.*"),
	},
	{
		patterns.CsToken("Soll"),
		patterns.Token("ich"),
	},
	{
		patterns.CsToken("Solltest"),
		patterns.Token("du"),
	},
	{
		patterns.CsToken("Müsstest"),
		patterns.Token("dir"),
	},
	{
		patterns.CsToken("Könntest"),
		patterns.Token("dir"),
	},
	{
		patterns.CsToken("Sollte"),
		patterns.TokenRegex("er|sie"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.TokenRegex("Bin|Kannst|Musst"),
	},
	{
		patterns.Token(","),
		patterns.TokenRegex("bin|hast|kannst|musst"),
	},
	{
		patterns.Token("er"),
		patterns.PosRegex("VER:.*"),
		patterns.Token("wird"),
	},
	{
		patterns.TokenRegex("wie|als"),
		patterns.Token("ich"),
		patterns.PosRegex("VER:.*"),
	},
	{
		patterns.TokenRegex("glaube?|denke?|hoffe?|vermute?|behaupte?|wette?"),
		patterns.Token("ich"),
		patterns.PosRegex("ADV.*|SUB.*|UNKNOWN|ADJ.*|PA[12].*|ART.*|PRP.*|PRO.*"),
	},
	{
		patterns.TokenRegex("ich"),
		patterns.Pos("VER:INF:NON"),
		patterns.Token("werde"),
	},
	{
		patterns.PosRegex("VER:IMP:SIN:.*"),
		patterns.Token("du"),
		patterns.TokenRegex("dich|dein|deine[srnm]?|mal"),
	},
	{
		patterns.PosRegex("VER:IMP:SIN:.*"),
		patterns.Token("du"),
		patterns.Token("!"),
	},
	{
		patterns.Token("sei"),
		patterns.Token("du"),
		patterns.Token("selbst"),
	},
	{
		patterns.Token("bin"),
		patterns.TokenRegex("dran|dabei"),
	},
	{
		patterns.Token("als"),
		patterns.Token("ich"),
		patterns.PosRegex("PA2:.*"),
		patterns.Token("bin"),
	},
	{
		patterns.Token("als"),
		patterns.TokenRegex("du|e[rs]|sie|ich"),
		patterns.NewPatternTokenBuilder().Token("sein").MatchInflectedForms().Build(),
		patterns.TokenRegex("[\\.,]"),
	},
	{
		patterns.TokenRegex("D[au]rf.*|Muss.*"),
		patterns.PosRegex("PRO:PER:NOM:.+"),
		patterns.PosRegex("VER:INF:.+"),
		patterns.Pos("PKT"),
		patterns.TokenRegex("(?!die).+"),
	},
	{
		patterns.CsToken("("),
		patterns.PosRegex("VER:2:SIN:.+"),
		patterns.CsToken(")"),
	},
	{
		patterns.PosRegex("VER:MOD:1:PLU:.+"),
		patterns.CsToken("wir"),
		patterns.CsToken("bitte"),
	},
	{
		patterns.Token("ohne"),
		patterns.Token("sie"),
		patterns.Token("hätte"),
		patterns.Token("ich"),
	},
	{
		patterns.Pos(languagetool.SentenceStartTagName),
		patterns.PosRegex("VER:IMP:SIN.+"),
		patterns.Token("du"),
		patterns.NewPatternTokenBuilder().CsToken("?").Negate().Build(),
	},
	{
		patterns.TokenRegex("[^a-zäöüß]+du"),
		patterns.Pos("VER:2:SIN:PRÄ:SFT"),
	},
	{
		patterns.PosRegex("PRO:IND.*"),
		patterns.PosRegex("SUB:.+:PLU.*"),
		patterns.TokenRegex("wie|als"),
		patterns.PosRegex("PRO:PER.+"),
		patterns.PosRegex("VER:[1-3]:PLU.*"),
	},
	{
		patterns.Pos("ADV:MOD"),
		patterns.TokenRegex("als"),
		patterns.PosRegex("PRO:PER.+"),
		patterns.PosRegex("VER:3:SIN.*"),
		patterns.PosRegex("PRO:IND:NOM:SIN.*"),
	},
	{
		patterns.PosRegex("PRO:IND.*"),
		patterns.TokenRegex("wie"),
		patterns.PosRegex("PRO:PER.+"),
		patterns.PosRegex("VER:.*:SIN.*"),
		patterns.PosRegex("PRO:PER:NOM:SIN.*"),
	},
	{
		patterns.TokenRegex("kein|keine"),
		patterns.TokenRegex("anderer|andere"),
		patterns.Token("als"),
		patterns.TokenRegex("ich|du|er|sie|es"),
		patterns.PosRegex("VER:MOD.*:PRÄ"),
	},
	{
		patterns.PosRegex("ART:DEF.*"),
		patterns.TokenRegex("gleich(e|en)|selb(e|en)"),
		patterns.PosRegex("SUB:.+"),
		patterns.Token("wie"),
		patterns.PosRegex("PRO:PER:NOM:SIN.*"),
		patterns.PosRegex("VER:INF.*"),
	},
	{
		patterns.Token("wenn"),
		patterns.PosRegex("PRO:PER:NOM:SIN.+"),
		patterns.PosRegex("PRO:PER:NOM.+"),
		patterns.PosRegex("VER:AUX:[1-3]:SIN:KJ2"),
	},
	{
		patterns.Token("wenn"),
		patterns.PosRegex("PRO:PER:NOM:PLU.+"),
		patterns.PosRegex("PRO:PER:NOM.+"),
		patterns.PosRegex("VER:AUX:[1-3]:PLU:KJ2"),
	},
	{
		patterns.Token("wenn"),
		patterns.Token("du"),
		patterns.Token("gehen"),
		patterns.Token("willst"),
		patterns.Token(","),
		patterns.Token("dann"),
		patterns.Token("geh"),
	},
	{
		patterns.Token("ob"),
		patterns.Token("ich"),
		patterns.PosRegex("VER:1.+"),
		patterns.Token("oder"),
		patterns.PosRegex("VER:1.+"),
		patterns.NewPatternTokenBuilder().Token("gehen").MatchInflectedForms().Build(),
		patterns.PosRegex("VER:MOD:1.*"),
	},
	{
		patterns.Token("mal"),
		patterns.Token("seh"),
		patterns.TokenRegex("’|'"),
		patterns.Token("n"),
	},
}
