package en

import "strings"

// english_top_suggestions ports AbstractEnglishSpellerRule.getTopSuggestions /
// getTopSuggestionsIgnoreCase and the ys→ies arm of getAdditionalTopSuggestions.
// Maps extracted 1:1 from Java static initializers (no invent).

var englishTopSuggestionsIgnoreCase = map[string][]string{
	"json":        {"Jason"},
	"bmps":        {"BMPs"},
	"ppts":        {"PPTs"},
	"italia":      {"Italy"},
	"copenhague":  {"Copenhagen"},
	"applepay":    {"Apple Pay"},
	"&&":          {"&"},
	"wensday":     {"Wednesday"},
	"interweb":    {"internet"},
	"interwebs":   {"internet"},
	"srilanka":    {"Sri Lanka"},
	"pcs":         {"PCs"},
	"oconnor":     {"O'Connor"},
	"oconor":      {"O'Conor"},
	"obrien":      {"O'Brien"},
	"odonnell":    {"O'Donnell"},
	"oneill":      {"O'Neill"},
	"oneil":       {"O'Neil"},
	"oconnell":    {"O'Connell"},
	"todo":        {"To-do", "To do"},
	"todos":       {"To-dos"},
	"elearning":   {"e-learning"},
	"g-mail":      {"Gmail"},
	"playstation": {"PlayStation"},
	"iam":         {"I am", "I'm"},
	"kpop":        {"K-pop"},
	"defenate":    {"definite"},
	"defenately":  {"definitely"},
	"trumpian":    {"Trumpist"},
	"trumpians":   {"Trumpists"},
	"UberEats":    {"Uber Eats"},
	"KWH":         {"kWh"},
	"MWH":         {"MWh"},
	"xray":        {"X-ray"},
	"xrays":       {"X-rays"},
	"soo":         {"so", "too", "son"},
}

var englishTopSuggestions = map[string][]string{
	"Ths":               {"This", "The"},
	"prev":              {"previous"},
	"kilotonne":         {"kiloton"},
	"kilotonnes":        {"kilotons"},
	"litehouse":         {"lighthouse"},
	"Litehouse":         {"Lighthouse"},
	"whitout":           {"without", "white out"},
	"Whitout":           {"Without", "White out"},
	"compability":       {"compatibility"},
	"Compability":       {"Compatibility"},
	"enroute":           {"en route"},
	"teasered":          {"teased"},
	"teasering":         {"teasing"},
	"stealed":           {"stole", "stolen"},
	"stealt":            {"stole", "stolen"},
	"ignight":           {"ignite"},
	"Ignight":           {"Ignite"},
	"ignights":          {"ignites"},
	"Ignights":          {"Ignites"},
	"ignighted":         {"ignited"},
	"Ignighted":         {"Ignited"},
	"ignighting":        {"igniting"},
	"Ignighting":        {"Igniting"},
	"transcripted":      {"transcribed"},
	"transcripting":     {"transcribing"},
	"incase":            {"in case"},
	"Incase":            {"In case"},
	"admittably":        {"admittedly"},
	"Admittably":        {"Admittedly"},
	"fam":               {"family", "fame"},
	"awnser":            {"answer"},
	"Awnser":            {"Answer"},
	"awnsers":           {"answers"},
	"Awnsers":           {"Answers"},
	"megatonne":         {"megaton"},
	"Megatonne":         {"Megaton"},
	"megatonnes":        {"megatons"},
	"Megatonnes":        {"Megatons"},
	"retd":              {"retd.", "retired"},
	"Retd":              {"Retd.", "Retired"},
	"intransparent":     {"non-transparent", "lacking transparency"},
	"repetion":          {"repetition"},
	"Repetion":          {"Repetition"},
	"repetions":         {"repetitions"},
	"Repetions":         {"Repetitions"},
	"rom":               {"room"},
	"th":                {"the"},
	"transman":          {"trans man"},
	"Transman":          {"Trans man"},
	"transmen":          {"trans men"},
	"Transmen":          {"Trans men"},
	"transwoman":        {"trans woman"},
	"Transwoman":        {"Trans woman"},
	"transwomen":        {"trans women"},
	"Transwomen":        {"Trans women"},
	"litterly":          {"literally"},
	"Litterly":          {"Literally"},
	"abt":               {"about"},
	"ley":               {"let"},
	"Ley":               {"Let"},
	"becuz":             {"because"},
	"becus":             {"because"},
	"lullabys":          {"lullabies"},
	"Lullabys":          {"Lullabies"},
	"forceably":         {"forcibly"},
	"Forceably":         {"Forcibly"},
	"accidently":        {"accidentally"},
	"Accidently":        {"Accidentally"},
	"aer":               {"are", "air"},
	"Aer":               {"Are", "Air"},
	"downie":            {"downy"},
	"Downie":            {"Downy"},
	"happing":           {"happening"},
	"Happing":           {"Happening"},
	"se":                {"see"},
	"maam":              {"ma'am", "madam"},
	"Maam":              {"Ma'am", "Madam"},
	"mam":               {"ma'am"},
	"Mam":               {"Ma'am"},
	"evidents":          {"evidence"},
	"Evidents":          {"Evidence"},
	"greatfull":         {"grateful"},
	"Greatfull":         {"Grateful"},
	"verticle":          {"vertical"},
	"Verticle":          {"Vertical"},
	"definaly":          {"definitely"},
	"Definaly":          {"Definitely"},
	"definally":         {"definitely"},
	"Definally":         {"Definitely"},
	"handable":          {"handleable"},
	"Handable":          {"Handleable"},
	"sal-ammoniac":      {"sal ammoniac"},
	"mumbo-jumbo":       {"mumbo jumbo"},
	"Mumbo-jumbo":       {"Mumbo jumbo"},
	"Mumbo-Jumbo":       {"Mumbo Jumbo"},
	"Tuffed":            {"Toughed"},
	"tuffed":            {"toughed"},
	"biosim":            {"biosimilar"},
	"biosims":           {"biosimilars"},
	"Tuffest":           {"Toughest"},
	"tuffest":           {"toughest"},
	"Tuffer":            {"Tougher"},
	"tuffer":            {"tougher"},
	"devast":            {"devastate"},
	"devasts":           {"devastates"},
	"devasted":          {"devastated"},
	"devasting":         {"devastating"},
	"Fundrace":          {"Fundraise"},
	"fundrace":          {"fundraise"},
	"Fundraces":         {"Fundraises"},
	"fundraces":         {"fundraises"},
	"Fundracing":        {"Fundraising"},
	"fundracing":        {"fundraising"},
	"Fundraced":         {"Fundraised"},
	"fundraced":         {"fundraised"},
	"withing":           {"within"},
	"Withing":           {"Within"},
	"hollyday":          {"holiday"},
	"Hollyday":          {"Holiday"},
	"hollydays":         {"holidays"},
	"Hollydays":         {"Holidays"},
	"overnite":          {"overnight"},
	"Overnite":          {"Overnight"},
	"tonite":            {"tonight"},
	"Tonite":            {"Tonight"},
	"nite":              {"night"},
	"Nite":              {"Night"},
	"nites":             {"nights"},
	"Nites":             {"Nights"},
	"upto":              {"up to", "unto"},
	"Upto":              {"Up to", "Unto"},
	"prolly":            {"probably"},
	"corse":             {"course"},
	"util":              {"utility"},
	"Util":              {"Utility"},
	"prorata":           {"pro rata"},
	"pro-rata":          {"pro rata"},
	"Prorata":           {"Pro rata"},
	"Pro-rata":          {"Pro rata"},
	"wast":              {"was", "waste", "waist", "wasn't"},
	"Wast":              {"Was", "Waste", "Waist", "Wasn't"},
	"drag&drop":         {"drag & drop"},
	"Drag&drop":         {"Drag & drop"},
	"Drag&Drop":         {"Drag & Drop"},
	"copy&paste":        {"copy & paste"},
	"Copy&paste":        {"Copy & paste"},
	"Copy&Paste":        {"Copy & Paste"},
	"hiphop":            {"hip-hop"},
	"Hiphop":            {"Hip-hop", "Hip-Hop"},
	"ap":                {"app", "up", "AP"},
	"Ap":                {"App", "Up", "AP"},
	"aps":               {"apps"},
	"Aps":               {"Apps"},
	"hehe":              {"he-he"},
	"Hehe":              {"He-he"},
	"politeful":         {"polite"},
	"Politeful":         {"Polite"},
	"defacto":           {"de facto"},
	"Defacto":           {"De facto"},
	"rethoric":          {"rhetoric"},
	"Rethoric":          {"Rhetoric"},
	"differently-abled": {"differently abled"},
	"Differently-abled": {"Differently abled"},
	"data-uri":          {"data URI"},
	"Ppl":               {"People"},
	"Si":                {"Is"},
	"si":                {"is"},
	"pcs":               {"PCs"},
	"constits":          {"consists"},
	"ect":               {"etc"},
	"fastly":            {"fast"},
	"carrie":            {"carry"},
	"bare-bone":         {"bare-bones", "bare-boned"},
	"Bare-bone":         {"Bare-bones", "Bare-boned"},
	"mae":               {"make", "MAE", "may", "May", "man"},
	"transportion":      {"transportation"},
	"Transportion":      {"Transportation"},
	"presention":        {"presentation"},
	"Presention":        {"Presentation"},
	"presension":        {"presentation"},
	"Presension":        {"Presentation"},
	"realtime":          {"real-time"},
	"Realtime":          {"Real-time"},
	"morphium":          {"morphine"},
	"Morphium":          {"Morphine"},
	"morphiums":         {"morphines"},
	"Morphiums":         {"Morphines"},
	"approvement":       {"approval"},
	"Approvement":       {"Approval"},
	"approvements":      {"approvals"},
	"Approvements":      {"Approvals"},
	"ciggarets":         {"cigarettes"},
	"Ciggarets":         {"Cigarettes"},
	"pro-bono":          {"pro bono"},
	"Pro-bono":          {"Pro bono"},
	"probono":           {"pro bono"},
	"Probono":           {"Pro bono"},
	"electronical":      {"electronic", "electronically"},
	"Electronical":      {"Electronic", "Electronically"},
	"unpolite":          {"impolite"},
	"armys":             {"armies"},
	"Armys":             {"Armies"},
	"tarrif":            {"tariff"},
	"Tarrif":            {"Tariff"},
	"tarrifs":           {"tariffs"},
	"Tarrifs":           {"Tariffs"},
	"techy":             {"techie"},
	"Techy":             {"Techie"},
	"techys":            {"techies"},
	"Techys":            {"Techies"},
	"non-techy":         {"non-techie"},
	"pharmasuitable":    {"pharmaceutical"},
	"storie":            {"story", "store", "stories"},
	"Storie":            {"Story", "Store", "Stories"},
	"ensuite":           {"en suite"},
	"Ensuite":           {"En suite"},
	"insite":            {"insight"},
	"insites":           {"insights"},
	"Insite":            {"Insight"},
	"Insites":           {"Insights"},
	"thouraly":          {"thoroughly"},
	"heiaracky":         {"hierarchy"},
	"on-prem":           {"on-premise"},
	"sin-off":           {"sign-off"},
	"sin-offs":          {"sign-offs"},
	"Sin-off":           {"Sign-off"},
	"Sin-offs":          {"Sign-offs"},
	"Alot":              {"A lot"},
	"alot":              {"a lot"},
	"DDOS":              {"DDoS"},
	"disencouraged":     {"discouraged"},
	"Disencouraged":     {"Discouraged"},
	"async":             {"asynchronous", "asynchronously"},
	"Async":             {"Asynchronous", "Asynchronously"},
	"endevours":         {"endeavours"},
	"endevors":          {"endeavors"},
	"endevour":          {"endeavour"},
	"endevor":           {"endeavor"},
	"industrys":         {"industries", "industry's", "industry"},
	"Industrys":         {"Industries", "Industry's", "Industry"},
	"partys":            {"parties", "party's", "party"},
	"Partys":            {"Parties", "Party's", "Party"},
	"countrys":          {"countries", "country's", "country"},
	"Countrys":          {"Countries", "Country's", "Country"},
	"bodys":             {"bodies", "body's", "body"},
	"Bodys":             {"Bodies", "Body's", "Body"},
	"ladys":             {"ladies", "lady's", "lady"},
	"Ladys":             {"Ladies", "Lady's", "Lady"},
	"citys":             {"cities", "city's", "city"},
	"Citys":             {"Cities", "City's", "City"},
	"batterys":          {"batteries", "battery's", "battery"},
	"Batterys":          {"Batteries", "Battery's", "Battery"},
	"technologys":       {"technologies", "technology's", "technology"},
	"Technologys":       {"Technologies", "Technology's", "Technology"},
	"childrens":         {"children's", "children"},
	"Childrens":         {"Children's", "Children"},
	"countys":           {"counties", "county's", "county"},
	"Countys":           {"Counties", "County's", "County"},
	"familys":           {"families", "family's", "family"},
	"Familys":           {"Families", "Family's", "Family"},
	"Thak":              {"Thank"},
	"thak":              {"thank"},
	"dieing":            {"dying"},
	"Dieing":            {"Dying"},
	"Supposably":        {"Supposedly"},
	"supposably":        {"supposedly"},
	"dem":               {"them"},
	"Dem":               {"Them"},
	"infact":            {"in fact"},
	"Infact":            {"In fact"},
	"ad-hoc":            {"ad hoc"},
	"adhoc":             {"ad hoc"},
	"Ad-hoc":            {"Ad hoc"},
	"Adhoc":             {"Ad hoc"},
	"ad-on":             {"add-on"},
	"add-o":             {"add-on"},
	"acc":               {"account", "accusative"},
	"Acc":               {"Account", "Accusative"},
	"ÂºC":               {"Â°C"},
	"jus":               {"just", "juice"},
	"Jus":               {"Just", "Juice"},
	"sayed":             {"said"},
	"sess":              {"says", "session", "cess"},
	"Addon":             {"Add-on"},
	"Addons":            {"Add-ons"},
	"ios":               {"iOS"},
	"yrs":               {"years"},
	"standup":           {"stand-up"},
	"standups":          {"stand-ups"},
	"Standup":           {"Stand-up"},
	"Standups":          {"Stand-ups"},
	"Playdough":         {"Play-Doh"},
	"playdough":         {"Play-Doh"},
	"biggy":             {"biggie"},
	"lieing":            {"lying"},
	"preffered":         {"preferred"},
	"preffering":        {"preferring"},
	"reffered":          {"referred"},
	"reffering":         {"referring"},
	"passthrough":       {"pass-through"},
	"&&":                {"&"},
	"cmon":              {"c'mon"},
	"Cmon":              {"C'mon"},
	"da":                {"the"},
	"Da":                {"The"},
	"Vue":               {"Vue.JS"},
	"errornous":         {"erroneous"},
	"brang":             {"brought"},
	"brung":             {"brought"},
	"thru":              {"through"},
	"pitty":             {"pity"},
	"barbwire":          {"barbed wire"},
	"barbwires":         {"barbed wires"},
	"monkie":            {"monkey"},
	"Monkie":            {"Monkey"},
	"monkies":           {"monkeys"},
	"Monkies":           {"Monkeys"},
	"Daddys":            {"Daddy's", "Daddies"},
	"Mommys":            {"Mommy's", "Mommies"},
	"daddys":            {"daddy's", "daddies"},
	"mommys":            {"mommy's", "mommies"},
	"dat":               {"that", "day"},
	"Dat":               {"That", "Day"},
	"speach":            {"speech"},
	"icecreem":          {"ice cream"},
	"math":              {"maths"},
	"fora":              {"for a"},
	"fomr":              {"form", "from"},
	"lotsa":             {"lots of"},
	"tryna":             {"trying to"},
	"coulda":            {"could have"},
	"shoulda":           {"should have"},
	"woulda":            {"would have"},
	"tellem":            {"tell them"},
	"Tellem":            {"Tell them"},
	"Webex":             {"WebEx"},
	"didint":            {"didn't"},
	"Didint":            {"Didn't"},
	"wasint":            {"wasn't"},
	"hasint":            {"hasn't"},
	"doesint":           {"doesn't"},
	"ist":               {"is"},
	"Boing":             {"Boeing"},
	"te":                {"the"},
	"todays":            {"today's"},
	"Todays":            {"Today's"},
	"todo":              {"to-do", "to do"},
	"todos":             {"to-dos", "to do"},
	"heres":             {"here's"},
	"Heres":             {"Here's"},
	"aways":             {"always"},
	"McDonalds":         {"McDonald's"},
	"ux":                {"UX"},
	"ive":               {"I've"},
	"infos":             {"informations"},
	"Infos":             {"Informations"},
	"prios":             {"priorities"},
	"Prio":              {"Priority"},
	"prio":              {"priority"},
	"Ecommerce":         {"E-Commerce"},
	"ezine":             {"e-zine"},
	"Ezine":             {"E-zine"},
	"ezines":            {"e-zines"},
	"Ezines":            {"E-zines"},
	"ebook":             {"e-book"},
	"ebooks":            {"e-books"},
	"eBook":             {"e-book"},
	"eBooks":            {"e-books"},
	"Ebook":             {"E-Book"},
	"Ebooks":            {"E-Books"},
	"Esport":            {"E-Sport"},
	"Esports":           {"E-Sports"},
	"R&B":               {"R & B", "R 'n' B"},
	"ie":                {"i.e."},
	"eg":                {"e.g."},
	"ppl":               {"people"},
	"kiddin":            {"kidding"},
	"doin":              {"doing"},
	"nothin":            {"nothing"},
	"SPOC":              {"SpOC"},
	"Thx":               {"Thanks"},
	"thx":               {"thanks"},
	"ty":                {"thank you", "thanks"},
	"Sry":               {"Sorry"},
	"sry":               {"sorry"},
	"im":                {"I'm"},
	"spoilt":            {"spoiled"},
	"Lil":               {"Little"},
	"lil":               {"little"},
	"gmail":             {"Gmail"},
	"Sucka":             {"Sucker"},
	"sucka":             {"sucker"},
	"whaddya":           {"what are you", "what do you"},
	"Whaddya":           {"What are you", "What do you"},
	"sinc":              {"sync"},
	"sweety":            {"sweetie"},
	"sweetys":           {"sweeties"},
	"sowwy":             {"sorry"},
	"Sowwy":             {"Sorry"},
	"shouldent":         {"shouldn't"},
	"couldent":          {"couldn't"},
	"grandmum":          {"grandma", "grandmother"},
	"grandmom":          {"grandma", "grandmother"},
	"Grandmum":          {"Grandma", "Grandmother"},
	"Grandmom":          {"Grandma", "Grandmother"},
	"enlighting":        {"enlightening"},
	"Enlighting":        {"Enlightening"},
	"center":            {"centre"},
	"ur":                {"your", "you are"},
	"Ur":                {"Your", "You are"},
	"ure":               {"your", "you are"},
	"Ure":               {"Your", "You are"},
	"mins":              {"minutes", "min"},
	"geo":               {"geography", "geographic"},
	"Geo":               {"Geography", "Geographic"},
	"addon":             {"add-on"},
	"addons":            {"add-ons"},
	"afterparty":        {"after-party"},
	"Afterparty":        {"After-party"},
	"wellbeing":         {"well-being"},
	"cuz":               {"because"},
	"Cuz":               {"Because"},
	"coz":               {"because"},
	"Coz":               {"Because"},
	"pls":               {"please"},
	"Pls":               {"Please"},
	"plz":               {"please"},
	"Plz":               {"Please"},
	"addendums":         {"addenda"},
	"algas":             {"algae"},
	"alumnas":           {"alumnae"},
	"alumnuses":         {"alumni"},
	"analysises":        {"analyses"},
	"appendixs":         {"appendices"},
	"axises":            {"axes"},
	"bacilluses":        {"bacilli"},
	"bacteriums":        {"bacteria"},
	"basises":           {"bases"},
	"beaus":             {"beaux"},
	"bisons":            {"bison"},
	"buffalos":          {"buffaloes"},
	"calfs":             {"calves"},
	"Childs":            {"Children", "Child's"},
	"childs":            {"children", "child's"},
	"crisises":          {"crises"},
	"criterions":        {"criteria"},
	"curriculums":       {"curricula"},
	"datums":            {"data"},
	"deers":             {"deer"},
	"diagnosises":       {"diagnoses"},
	"echos":             {"echoes"},
	"elfs":              {"elves"},
	"ellipsises":        {"ellipses"},
	"ir":                {"it"},
	"embargos":          {"embargoes"},
	"erratums":          {"errata"},
	"firemans":          {"firemen"},
	"fishs":             {"fishes", "fish"},
	"genuses":           {"genera"},
	"gooses":            {"geese"},
	"halfs":             {"halves"},
	"heros":             {"heroes"},
	"indexs":            {"indices", "indexes"},
	"lifes":             {"lives"},
	"mans":              {"men", "man's"},
	"mens":              {"men", "men's"},
	"matrixs":           {"matrices"},
	"meanses":           {"means"},
	"mediums":           {"media"},
	"memorandums":       {"memoranda"},
	"mooses":            {"moose"},
	"mosquitos":         {"mosquitoes"},
	"moskitos":          {"mosquitoes"},
	"moskito":           {"mosquito"},
	"neurosises":        {"neuroses"},
	"nucleuses":         {"nuclei"},
	"oasises":           {"oases"},
	"ovums":             {"ova"},
	"oxs":               {"oxen"},
	"oxes":              {"oxen"},
	"paralysises":       {"paralyses"},
	"potatos":           {"potatoes"},
	"radiuses":          {"radii"},
	"selfs":             {"selves"},
	"serieses":          {"series"},
	"sheeps":            {"sheep"},
	"shelfs":            {"shelves"},
	"scissorses":        {"scissors"},
	"specieses":         {"species"},
	"stimuluses":        {"stimuli"},
	"stratums":          {"strata"},
	"tableaus":          {"tableaux"},
	"thats":             {"those"},
	"thesises":          {"theses"},
	"thiefs":            {"thieves"},
	"thises":            {"these"},
	"tomatos":           {"tomatoes"},
	"tooths":            {"teeth"},
	"torpedos":          {"torpedoes"},
	"vertebras":         {"vertebrae"},
	"vetos":             {"vetoes"},
	"vitas":             {"vitae"},
	"watchs":            {"watches"},
	"wifes":             {"wives", "wife's"},
	"womans":            {"women", "woman's"},
	"Womans":            {"Women", "Woman's"},
	"womens":            {"women's"},
	"Womens":            {"Women's"},
	"deauthorized":      {"unauthorized"},
	"tippy-top":         {"tip-top", "top most"},
	"tippytop":          {"tip-top", "top most"},
	"imma":              {"I'm going to", "I'm a"},
	"Imma":              {"I'm going to", "I'm a"},
	"dontcha":           {"don't you"},
	"tobe":              {"to be"},
	"Gi":                {"Hi"},
	"Ji":                {"Hi"},
	"Dontcha":           {"don't you"},
	"greatfruit":        {"grapefruit", "great fruit"},
	"Insta":             {"Instagram"},
	"IO":                {"I/O"},
	"wierd":             {"weird"},
	"Wierd":             {"Weird"},
	"HipHop":            {"Hip-Hop"},
	"gove":              {"love", "give", "gave", "move"},
	"birdseye":          {"bird's-eye"},
	"Birdseye":          {"Bird's-eye"},
	"al":                {"all", "Al"},
	"publically":        {"publicly"},
	"fo":                {"for"},
	"shawty":            {"shorty"},
	"Shawty":            {"Shorty"},
	"savy":              {"savvy"},
	"Savy":              {"Savvy"},
	"automization":      {"automatization"},
	"automisation":      {"automatisation"},
	"Automization":      {"Automatization"},
	"Automisation":      {"Automatisation"},
	"aswell":            {"as well"},
	"Continuesly":       {"Continuously"},
	"continuesly":       {"continuously"},
	"humain":            {"humane", "human"},
	"protene":           {"protein"},
	"throught":          {"thought", "through", "throat"},
	"specifity":         {"specificity"},
	"specicity":         {"specificity"},
	"Specifity":         {"Specificity"},
	"Specicity":         {"Specificity"},
	"specifities":       {"specificities"},
	"specicities":       {"specificities"},
	"Specifities":       {"Specificities"},
	"Specicities":       {"Specificities"},
	"Neonazi":           {"Neo-Nazi"},
	"Neonazis":          {"Neo-Nazis"},
	"neonazi":           {"neo-Nazi"},
	"neonazis":          {"neo-Nazis"},
	"fiveteen":          {"fifteen"},
	"Fiveteen":          {"Fifteen"},
	"critism":           {"criticism"},
	"Critism":           {"Criticism"},
	"Hobbie":            {"Hobby"},
	"hobbie":            {"hobby"},
	"Hobbys":            {"Hobbies"},
	"hobbys":            {"hobbies"},
	"Copie":             {"Copy"},
	"Copys":             {"Copies"},
	"copie":             {"copy"},
	"copys":             {"copies"},
	"unconform":         {"nonconform"},
	"Unconform":         {"Nonconform"},
	"rideshare":         {"ride-share"},
	"Rideshare":         {"Ride-share"},
	"Rideshares":        {"Ride-shares"},
	"dropoff":           {"drop-off"},
	"Dropoff":           {"Drop-off"},
	"reportings":        {"reports", "reporting"},
	"Reportings":        {"Reports", "Reporting"},
	"luv":               {"love"},
	"luvs":              {"loves"},
	"Luv":               {"Love"},
	"Luvs":              {"Loves"},
	"islam":             {"Islam"},
	"andit":             {"and it"},
	"wud":               {"what", "mud", "bud"},
	"Wud":               {"What", "Mud", "Bud"},
	"fablet":            {"phablet", "tablet"},
	"Fablet":            {"Phablet", "Tablet"},
	"companys":          {"companies", "company's", "company"},
	"Companys":          {"Companies", "Company's", "Company"},
	"unencode":          {"decode"},
	"unencodes":         {"decodes"},
	"unencoded":         {"decoded"},
	"unencoding":        {"decoding"},
	"cheq":              {"check"},
	"southwest":         {"south-west"},
	"southeast":         {"south-east"},
	"northwest":         {"north-west"},
	"northeast":         {"north-east"},
	"Marylin":           {"Marilyn"},
	"blest":             {"blessed"},
	"yeld":              {"yelled"},
	"os":                {"OS", "is", "so"},
	"abel":              {"able"},
	"param":             {"parameter"},
	"params":            {"parameters"},
	"Param":             {"Parameter"},
	"Params":            {"Parameters"},
	"amature":           {"amateur"},
	"amatures":          {"amateurs"},
	"egoic":             {"egoistic"},
	"tarpit":            {"tar pit"},
	"tarpits":           {"tar pits"},
	"Tarpit":            {"Tar pit"},
	"Tarpits":           {"Tar pits"},
	"wheater":           {"weather"},
	"Wheater":           {"Weather"},
	"defi":              {"defibrillator", "DeFi"},
	"Defi":              {"Defibrillator", "DeFi"},
	"topup":             {"top-up"},
	"topups":            {"top-ups"},
	"nacked":            {"backed", "naked"},
	"no-profit":         {"non-profit"},
	"No-profit":         {"Non-profit"},
	"wrose":             {"worse"},
	"Wrose":             {"Worse"},
	"reak":              {"wreak"},
	"Reak":              {"Wreak"},
	"reaks":             {"wreaks"},
	"Reaks":             {"Wreaks"},
	"reaked":            {"wreaked"},
	"Reaked":            {"Wreaked"},
	"reaking":           {"wreaking"},
	"Reaking":           {"Wreaking"},
	"hight":             {"height"},
	"Hight":             {"Height"},
	"fulltime":          {"full-time"},
	"Fulltime":          {"Full-time"},
	"slimiar":           {"similar"},
	"Slimiar":           {"Similar"},
}

// EnglishAdditionalTopSuggestions ports getAdditionalTopSuggestions curated arms.
// isMisspelled used for ys→ies (false means suggestion is accepted by dict).
// Empty means caller may still apply SpellingCheckRule LanguageTool tops.
func EnglishAdditionalTopSuggestions(word string, isMisspelled func(string) bool) []string {
	if word == "" {
		return nil
	}
	if v, ok := englishTopSuggestions[word]; ok {
		return append([]string(nil), v...)
	}
	if v, ok := englishTopSuggestionsIgnoreCase[strings.ToLower(word)]; ok {
		return append([]string(nil), v...)
	}
	if strings.HasSuffix(word, "ys") && len(word) > 2 {
		// Java: word.replaceFirst("ys$", "ies")
		sug := word[:len(word)-2] + "ies"
		if isMisspelled != nil && !isMisspelled(sug) {
			return []string{sug}
		}
	}
	return nil
}
