package en

// EnglishDoNotSuggestWords ports AbstractEnglishSpellerRule.lcDoNotSuggestWords (full Java list).
var EnglishDoNotSuggestWords = map[string]struct{}{
	"asshole":        {},
	"assholes":       {},
	"bullshit":       {},
	"bullshitted":    {},
	"bullshitter":    {},
	"bullshitters":   {},
	"bullshitting":   {},
	"chickenshit":    {},
	"chickenshits":   {},
	"cocksucker":     {},
	"cocksuckers":    {},
	"coon":           {},
	"coon ass":       {},
	"coon asses":     {},
	"cunt":           {},
	"germane":        {},
	"double check":   {},
	"flat screen":    {},
	"full time":      {},
	"part time":      {},
	"java script":    {},
	"off topic":      {},
	"hard coding":    {},
	"hard coded":     {},
	"fine tune":      {},
	"fine tuned":     {},
	"fine tuning":    {},
	"kick started":   {},
	"kick starting":  {},
	"kicks tarting":  {},
	"kicks tarted":   {},
	"with holdings":  {},
	"hands free":     {},
	"screens hare":   {},
	"screens hares":  {},
	"screens hared":  {},
	"screens haring": {},
	"in flight":      {},
	"in car":         {},
	"client side":    {},
	"server side":    {},
	"worry some":     {},
	"skillet":        {},
	"skillets":       {},
	"code named":     {},
	"code naming":    {},
	"in house":       {},
	"back office":    {},
	"faggot":         {},
	"faggots":        {},
	"fuckable":       {},
	"fuck":           {},
	"fucker":         {},
	"fuckhead":       {},
	"fuckheads":      {},
	"horseshit":      {},
	"kraut":          {},
	"krauts":         {},
	"blackie":        {},
	"blackies":       {},
	"motherfucker":   {},
	"motherfuckers":  {},
	"motherfucking":  {},
	"nigga":          {},
	"niggas":         {},
	"niggaz":         {},
	"negro":          {},
	"nigger":         {},
	"nigger lip":     {},
	"nigger lips":    {},
	"niggers":        {},
	"shit":           {},
	"shits":          {},
	"shitfaced":      {},
	"shithead":       {},
	"shitheads":      {},
	"shitload":       {},
	"shitted":        {},
	"shitting":       {},
	"shitty":         {},
	"wop":            {},
	"wops":           {},
	"niggard":        {},
	"niggardly":      {},
}
